
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Oct  8 2026 21:20:54 -03 (Oct  9 2026 00:20:54 UTC)

// Verification Directory fv/fir_serial 

module fir_serial(i_data, i_clock, o_data);
  input [7:0] i_data;
  input i_clock;
  output [18:0] o_data;
  wire [7:0] i_data;
  wire i_clock;
  wire [18:0] o_data;
  wire [18:0] data_sum;
  wire [7:0] \shift_reg[5] ;
  wire [7:0] \shift_reg[6] ;
  wire [7:0] \shift_reg[4] ;
  wire [7:0] \shift_reg[3] ;
  wire [7:0] \shift_reg[2] ;
  wire [7:0] \shift_reg[1] ;
  wire [7:0] \shift_reg[0] ;
  wire [7:0] data_in_reg;
  wire UNCONNECTED, UNCONNECTED0, csa_tree_ADD_TC_OP_13_groupi_n_3,
       csa_tree_ADD_TC_OP_13_groupi_n_4,
       csa_tree_ADD_TC_OP_13_groupi_n_10,
       csa_tree_ADD_TC_OP_13_groupi_n_14,
       csa_tree_ADD_TC_OP_13_groupi_n_17,
       csa_tree_ADD_TC_OP_13_groupi_n_18;
  wire csa_tree_ADD_TC_OP_13_groupi_n_22,
       csa_tree_ADD_TC_OP_13_groupi_n_24,
       csa_tree_ADD_TC_OP_13_groupi_n_29,
       csa_tree_ADD_TC_OP_13_groupi_n_42,
       csa_tree_ADD_TC_OP_13_groupi_n_45,
       csa_tree_ADD_TC_OP_13_groupi_n_47,
       csa_tree_ADD_TC_OP_13_groupi_n_48,
       csa_tree_ADD_TC_OP_13_groupi_n_51;
  wire csa_tree_ADD_TC_OP_13_groupi_n_52,
       csa_tree_ADD_TC_OP_13_groupi_n_54,
       csa_tree_ADD_TC_OP_13_groupi_n_58,
       csa_tree_ADD_TC_OP_13_groupi_n_61,
       csa_tree_ADD_TC_OP_13_groupi_n_63,
       csa_tree_ADD_TC_OP_13_groupi_n_64,
       csa_tree_ADD_TC_OP_13_groupi_n_65,
       csa_tree_ADD_TC_OP_13_groupi_n_72;
  wire csa_tree_ADD_TC_OP_13_groupi_n_83,
       csa_tree_ADD_TC_OP_13_groupi_n_89,
       csa_tree_ADD_TC_OP_13_groupi_n_90,
       csa_tree_ADD_TC_OP_13_groupi_n_92,
       csa_tree_ADD_TC_OP_13_groupi_n_94,
       csa_tree_ADD_TC_OP_13_groupi_n_97,
       csa_tree_ADD_TC_OP_13_groupi_n_98,
       csa_tree_ADD_TC_OP_13_groupi_n_99;
  wire csa_tree_ADD_TC_OP_13_groupi_n_105,
       csa_tree_ADD_TC_OP_13_groupi_n_108,
       csa_tree_ADD_TC_OP_13_groupi_n_112,
       csa_tree_ADD_TC_OP_13_groupi_n_139,
       csa_tree_ADD_TC_OP_13_groupi_n_202,
       csa_tree_ADD_TC_OP_13_groupi_n_203,
       csa_tree_ADD_TC_OP_13_groupi_n_214,
       csa_tree_ADD_TC_OP_13_groupi_n_215;
  wire csa_tree_ADD_TC_OP_13_groupi_n_216,
       csa_tree_ADD_TC_OP_13_groupi_n_217,
       csa_tree_ADD_TC_OP_13_groupi_n_218,
       csa_tree_ADD_TC_OP_13_groupi_n_219,
       csa_tree_ADD_TC_OP_13_groupi_n_220,
       csa_tree_ADD_TC_OP_13_groupi_n_221,
       csa_tree_ADD_TC_OP_13_groupi_n_230,
       csa_tree_ADD_TC_OP_13_groupi_n_231;
  wire csa_tree_ADD_TC_OP_13_groupi_n_235,
       csa_tree_ADD_TC_OP_13_groupi_n_236,
       csa_tree_ADD_TC_OP_13_groupi_n_237,
       csa_tree_ADD_TC_OP_13_groupi_n_241,
       csa_tree_ADD_TC_OP_13_groupi_n_242,
       csa_tree_ADD_TC_OP_13_groupi_n_244,
       csa_tree_ADD_TC_OP_13_groupi_n_251,
       csa_tree_ADD_TC_OP_13_groupi_n_252;
  wire csa_tree_ADD_TC_OP_13_groupi_n_253,
       csa_tree_ADD_TC_OP_13_groupi_n_254,
       csa_tree_ADD_TC_OP_13_groupi_n_255,
       csa_tree_ADD_TC_OP_13_groupi_n_256,
       csa_tree_ADD_TC_OP_13_groupi_n_257,
       csa_tree_ADD_TC_OP_13_groupi_n_261,
       csa_tree_ADD_TC_OP_13_groupi_n_263,
       csa_tree_ADD_TC_OP_13_groupi_n_264;
  wire csa_tree_ADD_TC_OP_13_groupi_n_265,
       csa_tree_ADD_TC_OP_13_groupi_n_268,
       csa_tree_ADD_TC_OP_13_groupi_n_269,
       csa_tree_ADD_TC_OP_13_groupi_n_270,
       csa_tree_ADD_TC_OP_13_groupi_n_271,
       csa_tree_ADD_TC_OP_13_groupi_n_279,
       csa_tree_ADD_TC_OP_13_groupi_n_298,
       csa_tree_ADD_TC_OP_13_groupi_n_310;
  wire csa_tree_ADD_TC_OP_13_groupi_n_312,
       csa_tree_ADD_TC_OP_13_groupi_n_319,
       csa_tree_ADD_TC_OP_13_groupi_n_320,
       csa_tree_ADD_TC_OP_13_groupi_n_321,
       csa_tree_ADD_TC_OP_13_groupi_n_322,
       csa_tree_ADD_TC_OP_13_groupi_n_347,
       csa_tree_ADD_TC_OP_13_groupi_n_348,
       csa_tree_ADD_TC_OP_13_groupi_n_352;
  wire csa_tree_ADD_TC_OP_13_groupi_n_353,
       csa_tree_ADD_TC_OP_13_groupi_n_354,
       csa_tree_ADD_TC_OP_13_groupi_n_355,
       csa_tree_ADD_TC_OP_13_groupi_n_361,
       csa_tree_ADD_TC_OP_13_groupi_n_362,
       csa_tree_ADD_TC_OP_13_groupi_n_375,
       csa_tree_ADD_TC_OP_13_groupi_n_378,
       csa_tree_ADD_TC_OP_13_groupi_n_379;
  wire csa_tree_ADD_TC_OP_13_groupi_n_388,
       csa_tree_ADD_TC_OP_13_groupi_n_389, n_484, n_500, n_516, n_518,
       n_520, n_521;
  wire n_522, n_530, n_531, n_538, n_539, n_540, n_542, n_544;
  wire n_545, n_619, n_621, n_622, n_672, n_675, n_681, n_682;
  wire n_689, n_710, n_748, n_749, n_770, n_771, n_797, n_800;
  wire n_900, n_922, n_923, n_924, n_925, n_926, n_927, n_982;
  wire n_983, n_984, n_985, n_986, n_1034, n_1037, n_1100, n_1118;
  wire n_1119, n_1148, n_1178, n_1182, n_1199, n_1200, n_1204, n_1205;
  wire n_1217, n_1218, n_1238, n_1240, n_1241, n_1242, n_1243, n_1244;
  wire n_1246, n_1247, n_1251, n_1252, n_1258, n_1261, n_1262, n_1275;
  wire n_1277, n_1278, n_1282, n_1283, n_1298, n_1302, n_1303, n_1304;
  wire n_1316, n_1335, n_1336, n_1337, n_1340, n_1341, n_1342, n_1346;
  wire n_1355, n_1365, n_1376, n_1379, n_1399, n_1400, n_1429, n_1430;
  wire n_1436, n_1443, n_1445, n_1448, n_1450, n_1451, n_1453, n_1457;
  wire n_1469, n_1473, n_1476, n_1481, n_1482, n_1483, n_1488, n_1492;
  wire n_1493, n_1498, n_1499, n_1500, n_1503, n_1506, n_1507, n_1508;
  wire n_1527, n_1529, n_1534, n_1535, n_1536, n_1537, n_1539, n_1540;
  wire n_1548, n_1549, n_1550, n_1555, n_1557, n_1558, n_1566, n_1580;
  wire n_1581, n_1583, n_1592, n_1636, n_1649, n_1674, n_1676, n_1681;
  wire n_1682, n_1695, n_1697, n_1700, n_1708, n_1710, n_1715, n_1716;
  wire n_1717, n_1718, n_1719, n_1720, n_1721, n_1722, n_1728, n_1729;
  wire n_1731, n_1732, n_1752, n_1753, n_1754, n_1755, n_1758, n_1760;
  wire n_1762, n_1764, n_1780, n_1783, n_1784, n_1785, n_1787, n_1794;
  wire n_1797, n_1798, n_1799, n_1806, n_1824, n_1827, n_1828, n_1829;
  wire n_1830, n_1834, n_1835, n_1836, n_1837, n_1838, n_1839, n_1840;
  wire n_1841, n_1845, n_1847, n_1848, n_1849, n_1851, n_1854, n_1855;
  wire n_1857, n_1858, n_1863, n_1870, n_1871, n_1873, n_1874, n_1875;
  wire n_1877, n_1878, n_1879, n_1881, n_1882, n_1883, n_1884, n_1885;
  wire n_1886, n_1887, n_1888, n_1889, n_1890, n_1891, n_1892, n_1893;
  wire n_1895, n_1897, n_1898, n_1900, n_1901, n_1908, n_1909, n_1910;
  wire n_1911, n_1912, n_1913, n_1915, n_1919, n_1920, n_1921, n_1922;
  wire n_1923, n_1924, n_1925, n_1926, n_1927, n_1928, n_1929, n_1934;
  wire n_1941, n_1942, n_1945, n_1946, n_1948, n_1949, n_1952, n_1954;
  wire n_1958, n_1961, n_1965, n_1966, n_1967, n_1968, n_1969, n_1980;
  wire n_1981, n_2004, n_2007, n_2008, n_2014, n_2016, n_2017, n_2018;
  wire n_2019, n_2020, n_2021, n_2022, n_2023, n_2024, n_2025, n_2026;
  wire n_2027, n_2031, n_2037, n_2038, n_2039, n_2041, n_2042, n_2043;
  wire n_2044, n_2045, n_2046, n_2047, n_2055, n_2056, n_2057, n_2084;
  wire n_2085, n_2086, n_2087, n_2088, n_2089, n_2090, n_2092, n_2093;
  wire n_2094, n_2096, n_2098, n_2106, n_2109, n_2161, n_2162, n_2163;
  wire n_2164, n_2165, n_2166, n_2167, n_2168, n_2169, n_2170, n_2171;
  wire n_2172, n_2174, n_2175, n_2176, n_2177, n_2178, n_2179, n_2180;
  wire n_2181, n_2182, n_2184, n_2187, n_2188, n_2190, n_2191, n_2192;
  wire n_2193, n_2194, n_2195, n_2196, n_2197, n_2198, n_2199, n_2200;
  wire n_2201, n_2202, n_2203, n_2205, n_2206, n_2207, n_2208, n_2209;
  wire n_2210, n_2214, n_2215, n_2216, n_2217, n_2219, n_2220, n_2226;
  wire n_2231, n_2233, n_2234, n_2235, n_2237, n_2239, n_2240, n_2242;
  wire n_2243, n_2244, n_2246, n_2247, n_2248, n_2249, n_2251, n_2254;
  wire n_2255, n_2257, n_2259, n_2260, n_2261, n_2266, n_2267, n_2269;
  wire n_2270, n_2271, n_2272, n_2273, n_2282, n_2291, n_2292, n_2293;
  wire n_2294, n_2296, n_2297, n_2304, n_2305, n_2306, n_2308, n_2309;
  wire n_2311, n_2312, n_2313, n_2320, n_2327, n_2333, n_2334, n_2336;
  wire n_2337, n_2338, n_2348, n_2349, n_2350, n_2351, n_2352, n_2353;
  wire n_2355, n_2368, n_2372, n_2373, n_2374, n_2379, n_2383, n_2384;
  wire n_2385, n_2387, n_2388, n_2389, n_2390, n_2397, n_2400, n_2402;
  wire n_2403, n_2406, n_2415, n_2421, n_2423, n_2425, n_2428, n_2429;
  wire n_2432, n_2433, n_2434, n_2435, n_2436, n_2437, n_2439, n_2440;
  wire n_2441, n_2442, n_2444, n_2445, n_2446, n_2448, n_2452, n_2453;
  wire n_2454, n_2455, n_2456, n_2457, n_2458, n_2460, n_2468, n_2469;
  wire n_2470, n_2475, n_2478, n_2479, n_2480, n_2483, n_2485, n_2486;
  wire n_2489, n_2494, n_2495, n_2496, n_2497, n_2498, n_2499, n_2500;
  wire n_2501, n_2502, n_2503, n_2504, n_2505, n_2506, n_2507, n_2508;
  wire n_2509, n_2510, n_2511, n_2512, n_2513, n_2514, n_2521, n_2522;
  wire n_2529, n_2531, n_2533, n_2534, n_2536, n_2539, n_2540, n_2541;
  wire n_2542, n_2544, n_2545, n_2549, n_2550, n_2551, n_2553, n_2554;
  wire n_2555, n_2566, n_2567, n_2571, n_2572, n_2573, n_2574, n_2575;
  wire n_2576, n_2577, n_2578, n_2580, n_2581, n_2582, n_2585, n_2586;
  wire n_2587, n_2588, n_2589, n_2590, n_2591, n_2600, n_2601, n_2602;
  wire n_2603, n_2604, n_2605, n_2606, n_2607, n_2608, n_2609, n_2610;
  wire n_2615, n_2617, n_2618, n_2619, n_2620, n_2621, n_2622, n_2623;
  wire n_2634, n_2635, n_2636, n_2637, n_2638, n_2639, n_2640, n_2641;
  wire n_2642, n_2643, n_2644, n_2646, n_2647, n_2648, n_2649, n_2656;
  wire n_2657, n_2658, n_2659, n_2660, n_2662, n_2663, n_2664, n_2667;
  wire n_2668, n_2669, n_2670, n_2671, n_2672, n_2673, n_2729, n_2730;
  wire n_2733, n_2734, n_2735, n_2741, n_2742, n_2743, n_2744, n_2745;
  wire n_2746, n_2747, n_2748, n_2749, n_2750, n_2773, n_2774, n_2775;
  wire n_2782, n_2783, n_2784, n_2785, n_2786, n_2803, n_2804, n_2837;
  wire n_2839, n_2841, n_2842, n_2843, n_2847, n_2848, n_2849, n_2850;
  wire n_2855, n_2856, n_2857, n_2858, n_2859, n_2860, n_2861, n_2862;
  wire n_2863, n_2864, n_2874, n_2900, n_2901, n_2902, n_2903, n_2904;
  wire n_2918, n_2919, n_2920, n_2926, n_2927, n_2928, n_2929, n_2939;
  wire n_2940, n_2941, n_2942, n_2943, n_3006, n_3007, n_3008, n_3013;
  wire n_3014, n_3015, n_3016, n_3017, n_3018, n_3043, n_3044, n_3049;
  wire n_3052, n_3053, n_3054, n_3055, n_3056, n_3058, n_3059, n_3061;
  wire n_3062, n_3064, n_3065, n_3067, n_3068, n_3069, n_3070, n_3071;
  wire n_3072, n_3073, n_3074, n_3075, n_3076, n_3077, n_3079, n_3081;
  wire n_3082, n_3084, n_3085, n_3087;
  assign o_data[15] = o_data[18];
  assign o_data[16] = o_data[18];
  assign o_data[17] = o_data[18];
  DFFHQX1LVT \data_out_reg_reg[12] (.CK (i_clock), .D (n_2864), .Q
       (o_data[12]));
  DFFHQX1LVT \data_out_reg_reg[2] (.CK (i_clock), .D (data_sum[2]), .Q
       (o_data[2]));
  DFFHQX1LVT \data_out_reg_reg[1] (.CK (i_clock), .D (data_sum[1]), .Q
       (o_data[1]));
  DFFHQX1LVT \data_out_reg_reg[14] (.CK (i_clock), .D (n_1529), .Q
       (o_data[14]));
  DFFHQX1LVT \data_out_reg_reg[0] (.CK (i_clock), .D (data_sum[0]), .Q
       (o_data[0]));
  DFFHQX1LVT \data_out_reg_reg[8] (.CK (i_clock), .D (n_1037), .Q
       (o_data[8]));
  DFFHQX1LVT \data_out_reg_reg[6] (.CK (i_clock), .D (n_3055), .Q
       (o_data[6]));
  DFFHQX1LVT \data_out_reg_reg[7] (.CK (i_clock), .D (n_2943), .Q
       (o_data[7]));
  DFFHQX1LVT \data_out_reg_reg[10] (.CK (i_clock), .D (n_2743), .Q
       (o_data[10]));
  DFFHQX1LVT \data_out_reg_reg[9] (.CK (i_clock), .D (n_1182), .Q
       (o_data[9]));
  DFFHQX1LVT \data_out_reg_reg[3] (.CK (i_clock), .D (data_sum[3]), .Q
       (o_data[3]));
  DFFHQX1LVT \data_out_reg_reg[13] (.CK (i_clock), .D (n_1443), .Q
       (o_data[13]));
  DFFHQX1LVT \data_out_reg_reg[11] (.CK (i_clock), .D (n_1540), .Q
       (o_data[11]));
  DFFHQX1LVT \data_out_reg_reg[4] (.CK (i_clock), .D (data_sum[4]), .Q
       (o_data[4]));
  DFFHQX1LVT \data_out_reg_reg[5] (.CK (i_clock), .D (n_2637), .Q
       (o_data[5]));
  DFFHQX1LVT \data_out_reg_reg[15] (.CK (i_clock), .D (n_900), .Q
       (o_data[18]));
  DFFHQX4LVT \shift_reg_reg[6][7] (.CK (i_clock), .D (\shift_reg[5]
       [7]), .Q (\shift_reg[6] [7]));
  DFFHQX4LVT \shift_reg_reg[6][0] (.CK (i_clock), .D (\shift_reg[5]
       [0]), .Q (\shift_reg[6] [0]));
  DFFHQX4LVT \shift_reg_reg[6][5] (.CK (i_clock), .D (n_2648), .Q
       (\shift_reg[6] [5]));
  DFFHQX4LVT \shift_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5]
       [3]), .Q (\shift_reg[6] [3]));
  DFFHQX4LVT \shift_reg_reg[6][4] (.CK (i_clock), .D (\shift_reg[5]
       [4]), .Q (\shift_reg[6] [4]));
  DFFQX2LVT \shift_reg_reg[5][7] (.CK (i_clock), .D (\shift_reg[4]
       [7]), .Q (\shift_reg[5] [7]));
  DFFHQX8LVT \shift_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4]
       [3]), .Q (\shift_reg[5] [3]));
  DFFHQX8LVT \shift_reg_reg[5][1] (.CK (i_clock), .D (\shift_reg[4]
       [1]), .Q (\shift_reg[5] [1]));
  DFFHQX8LVT \shift_reg_reg[4][6] (.CK (i_clock), .D (\shift_reg[3]
       [6]), .Q (\shift_reg[4] [6]));
  DFFHQX4LVT \shift_reg_reg[4][4] (.CK (i_clock), .D (\shift_reg[3]
       [4]), .Q (\shift_reg[4] [4]));
  DFFQX2LVT \shift_reg_reg[4][5] (.CK (i_clock), .D (n_1337), .Q
       (\shift_reg[4] [5]));
  DFFHQX4LVT \shift_reg_reg[4][0] (.CK (i_clock), .D (\shift_reg[3]
       [0]), .Q (\shift_reg[4] [0]));
  DFFHQX4LVT \shift_reg_reg[4][2] (.CK (i_clock), .D (n_2667), .Q
       (\shift_reg[4] [2]));
  DFFHQX4LVT \shift_reg_reg[3][2] (.CK (i_clock), .D (\shift_reg[2]
       [2]), .Q (\shift_reg[3] [2]));
  DFFHQX4LVT \shift_reg_reg[3][5] (.CK (i_clock), .D (\shift_reg[2]
       [5]), .Q (\shift_reg[3] [5]));
  DFFHQX8LVT \shift_reg_reg[3][1] (.CK (i_clock), .D (\shift_reg[2]
       [1]), .Q (\shift_reg[3] [1]));
  DFFHQX4LVT \shift_reg_reg[3][3] (.CK (i_clock), .D (n_2660), .Q
       (\shift_reg[3] [3]));
  DFFHQX4LVT \shift_reg_reg[2][0] (.CK (i_clock), .D (\shift_reg[1]
       [0]), .Q (\shift_reg[2] [0]));
  DFFQX2LVT \shift_reg_reg[2][5] (.CK (i_clock), .D (\shift_reg[1]
       [5]), .Q (\shift_reg[2] [5]));
  DFFHQX4LVT \shift_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1]
       [3]), .Q (\shift_reg[2] [3]));
  DFFHQX8LVT \shift_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [3]), .Q (\shift_reg[1] [3]));
  DFFQX2LVT \shift_reg_reg[1][0] (.CK (i_clock), .D (n_2533), .Q
       (\shift_reg[1] [0]));
  DFFHQX4LVT \shift_reg_reg[1][4] (.CK (i_clock), .D (n_2669), .Q
       (\shift_reg[1] [4]));
  DFFHQX4LVT \shift_reg_reg[1][6] (.CK (i_clock), .D (\shift_reg[0]
       [6]), .Q (\shift_reg[1] [6]));
  DFFHQX8LVT \shift_reg_reg[1][2] (.CK (i_clock), .D (\shift_reg[0]
       [2]), .Q (\shift_reg[1] [2]));
  DFFHQX4LVT \shift_reg_reg[0][7] (.CK (i_clock), .D (data_in_reg[7]),
       .Q (\shift_reg[0] [7]));
  DFFHQX4LVT \shift_reg_reg[0][4] (.CK (i_clock), .D (data_in_reg[4]),
       .Q (\shift_reg[0] [4]));
  DFFHQX8LVT \shift_reg_reg[0][3] (.CK (i_clock), .D (data_in_reg[3]),
       .Q (\shift_reg[0] [3]));
  DFFHQX4LVT \data_in_reg_reg[6] (.CK (i_clock), .D (i_data[6]), .Q
       (data_in_reg[6]));
  DFFHQX4LVT \data_in_reg_reg[5] (.CK (i_clock), .D (i_data[5]), .Q
       (data_in_reg[5]));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_001_0__2398(.A
       (\shift_reg[6] [1]), .B (\shift_reg[0] [0]), .CI
       (data_in_reg[1]), .CO (csa_tree_ADD_TC_OP_13_groupi_n_361), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_362));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_003_2__5526(.A
       (n_3076), .B (\shift_reg[1] [1]), .CI (n_542), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_355), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_354));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_003_3__6783(.A
       (n_521), .B (n_530), .CI (n_2582), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_310), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_378));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_004_0__1617(.A
       (\shift_reg[6] [4]), .B (csa_tree_ADD_TC_OP_13_groupi_n_58), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_17), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_353), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_352));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_004_3__5122(.A
       (n_2534), .B (\shift_reg[4] [0]), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_64), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_348), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_347));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_004_7__1881(.A
       (n_545), .B (csa_tree_ADD_TC_OP_13_groupi_n_355), .CI (n_1874),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_242), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_379));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_006_10__1617(.A
       (n_926), .B (n_3074), .CI (n_2575), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_231), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_230));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_007_2__7098(.A
       (\shift_reg[1] [5]), .B (\shift_reg[5] [6]), .CI
       (\shift_reg[4] [3]), .CO (csa_tree_ADD_TC_OP_13_groupi_n_322),
       .S (csa_tree_ADD_TC_OP_13_groupi_n_321));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_007_3__6131(.A
       (\shift_reg[1] [3]), .B (csa_tree_ADD_TC_OP_13_groupi_n_63), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_29), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_320), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_319));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_007_10__9945(.A
       (n_2195), .B (n_2196), .CI (n_2018), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_203), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_202));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_008_4__2398(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_47), .B (\shift_reg[5] [7]), .CI
       (n_1764), .CO (csa_tree_ADD_TC_OP_13_groupi_n_298), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_312));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_008_5__5107(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_322), .B (n_2216), .CI (n_3069),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_271), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_270));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_008_6__6260(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_320), .B (n_985), .CI (n_1483),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_269), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_268));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_4__7098(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_22), .B (n_2668), .CI (n_1473),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_265), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_264));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_5__6131(.A
       (n_984), .B (n_2672), .CI (n_2260), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_263), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_257));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_6__1881(.A
       (n_1508), .B (n_3014), .CI (n_749), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_256), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_255));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_7__5115(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_298), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_271), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_264), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_221), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_220));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_8__7482(.A
       (n_2200), .B (csa_tree_ADD_TC_OP_13_groupi_n_269), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_257), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_219), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_218));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_010_1__2883(.A
       (\shift_reg[1] [6]), .B (data_in_reg[7]), .CI (\shift_reg[3]
       [4]), .CO (csa_tree_ADD_TC_OP_13_groupi_n_261), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_279));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_010_3__1666(.A
       (n_1681), .B (n_1507), .CI (n_748), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_254), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_253));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_010_4__7410(.A
       (n_1527), .B (n_3061), .CI (csa_tree_ADD_TC_OP_13_groupi_n_279),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_252), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_251));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_010_6__5477(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_251), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_263), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_256), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_217), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_216));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_011_3__6783(.A
       (n_2486), .B (n_771), .CI (csa_tree_ADD_TC_OP_13_groupi_n_254),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_215), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_214));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_012_0__1705(.A
       (\shift_reg[3] [6]), .B (\shift_reg[2] [6]), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_54), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_237), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_244));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_012_1__5122(.A
       (n_2485), .B (n_770), .CI (csa_tree_ADD_TC_OP_13_groupi_n_244),
       .CO (csa_tree_ADD_TC_OP_13_groupi_n_236), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_241));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_013_0__6131(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_48), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_61), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_237), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_389), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_235));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_013_1__1881(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_236), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_235), .CI (n_681), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_375), .S
       (csa_tree_ADD_TC_OP_13_groupi_n_388));
  BUFX3LVT csa_tree_ADD_TC_OP_13_groupi_g1124(.A (n_2266), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_139));
  NAND2X1LVT csa_tree_ADD_TC_OP_13_groupi_g1154__7482(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_389), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_375), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_112));
  OR2X4LVT csa_tree_ADD_TC_OP_13_groupi_g1159__9315(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_389), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_375), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_108));
  INVX3 csa_tree_ADD_TC_OP_13_groupi_g1162(.A (n_1674), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_105));
  XNOR2X1LVT csa_tree_ADD_TC_OP_13_groupi_g1164__2346(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_97), .B (n_621), .Y
       (data_sum[4]));
  NOR2X6LVT csa_tree_ADD_TC_OP_13_groupi_g1168__5477(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_379), .B (n_1708), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_99));
  INVX2LVT csa_tree_ADD_TC_OP_13_groupi_g1169(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_97), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_98));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_g1170__2398(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_378), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_94), .CI (n_1710), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_97), .S (data_sum[3]));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_g1171__5107(.A (n_531), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_92), .CI (n_2591), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_94), .S (data_sum[2]));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_g1172__6260(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_18), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_90), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_362), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_92), .S (data_sum[1]));
  ADDHX1LVT csa_tree_ADD_TC_OP_13_groupi_g1173__4319(.A
       (data_in_reg[0]), .B (\shift_reg[6] [0]), .CO
       (csa_tree_ADD_TC_OP_13_groupi_n_90), .S (data_sum[0]));
  OAI22X2LVT csa_tree_ADD_TC_OP_13_groupi_g1174__8428(.A0
       (\shift_reg[6] [6]), .A1 (\shift_reg[3] [0]), .B0
       (csa_tree_ADD_TC_OP_13_groupi_n_52), .B1 (n_1506), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_89));
  NAND2X2LVT csa_tree_ADD_TC_OP_13_groupi_g1182__1705(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_52), .B (n_1506), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_83));
  INVX1LVT csa_tree_ADD_TC_OP_13_groupi_g1228(.A (\shift_reg[3] [1]),
       .Y (csa_tree_ADD_TC_OP_13_groupi_n_42));
  INVX1LVT csa_tree_ADD_TC_OP_13_groupi_g1249(.A (\shift_reg[5] [7]),
       .Y (csa_tree_ADD_TC_OP_13_groupi_n_22));
  INVX1 csa_tree_ADD_TC_OP_13_groupi_g1253(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_17), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_18));
  INVX3LVT csa_tree_ADD_TC_OP_13_groupi_g1257(.A (\shift_reg[6] [3]),
       .Y (csa_tree_ADD_TC_OP_13_groupi_n_14));
  CLKBUFX8LVT csa_tree_ADD_TC_OP_13_groupi_fopt1(.A (n_1908), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_10));
  AND2X6LVT csa_tree_ADD_TC_OP_13_groupi_g1263__5115(.A
       (\shift_reg[6] [4]), .B (\shift_reg[6] [7]), .Y
       (csa_tree_ADD_TC_OP_13_groupi_n_4));
  OAI2BB1X4LVT csa_tree_ADD_TC_OP_13_groupi_g1264__7482(.A0N
       (csa_tree_ADD_TC_OP_13_groupi_n_108), .A1N (n_2514), .B0
       (n_1450), .Y (csa_tree_ADD_TC_OP_13_groupi_n_3));
  INVX3LVT g1291(.A (n_2255), .Y (n_500));
  NAND2X2LVT g191(.A (n_1785), .B (n_2440), .Y (n_520));
  NOR3BX4LVT g195(.AN (\shift_reg[1] [3]), .B (\shift_reg[5] [1]), .C
       (\shift_reg[2] [2]), .Y (n_516));
  NOR2X2LVT g197(.A (\shift_reg[1] [3]), .B (\shift_reg[5] [1]), .Y
       (n_518));
  NOR2X4LVT g198(.A (n_2210), .B (csa_tree_ADD_TC_OP_13_groupi_n_51),
       .Y (n_521));
  AOI2BB1X2LVT g196(.A0N (\shift_reg[6] [2]), .A1N (\shift_reg[5] [1]),
       .B0 (n_521), .Y (n_522));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_002_0__1299(.A
       (\shift_reg[0] [1]), .B (\shift_reg[1] [0]), .CI
       (data_in_reg[2]), .CO (n_530), .S (n_531));
  NOR2X4LVT g30(.A (n_540), .B (n_1217), .Y (n_542));
  NOR2X4LVT g31(.A (\shift_reg[6] [0]), .B (n_539), .Y (n_540));
  CLKINVX4LVT fopt1303(.A (n_538), .Y (n_539));
  BUFX3LVT fopt34(.A (\shift_reg[6] [3]), .Y (n_538));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_004_4__1304(.A
       (\shift_reg[0] [3]), .B (csa_tree_ADD_TC_OP_13_groupi_n_42), .CI
       (n_540), .CO (n_544), .S (n_545));
  NAND2BX1LVT g27(.AN (csa_tree_ADD_TC_OP_13_groupi_n_99), .B (n_619),
       .Y (n_621));
  NAND2X8LVT g1319(.A (csa_tree_ADD_TC_OP_13_groupi_n_379), .B
       (n_1708), .Y (n_619));
  OAI21X4LVT g28(.A0 (csa_tree_ADD_TC_OP_13_groupi_n_98), .A1
       (csa_tree_ADD_TC_OP_13_groupi_n_99), .B0 (n_619), .Y (n_622));
  ADDFHX1LVT g287(.A (n_2047), .B (n_2901), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_265), .CO (n_672), .S (n_682));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_012_2__1342(.A
       (n_2903), .B (csa_tree_ADD_TC_OP_13_groupi_n_215), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_241), .CO (n_681), .S (n_675));
  NOR2X6LVT g1348(.A (n_3052), .B (n_2423), .Y (n_689));
  NOR2X4LVT g206(.A (n_2266), .B (n_484), .Y (n_710));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_009_1__1379(.A
       (n_2658), .B (n_1580), .CI (csa_tree_ADD_TC_OP_13_groupi_n_65),
       .CO (n_748), .S (n_749));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_011_1__1390(.A
       (n_1555), .B (\shift_reg[5] [7]), .CI (\shift_reg[4] [7]), .CO
       (n_770), .S (n_771));
  ADDFHX1LVT g1394(.A (\shift_reg[4] [4]), .B (\shift_reg[2] [0]), .CI
       (n_2656), .CO (n_797), .S (n_800));
  AOI21X4LVT g126(.A0 (n_2056), .A1 (n_1961), .B0
       (csa_tree_ADD_TC_OP_13_groupi_n_3), .Y (n_900));
  ADDFHX2LVT g262(.A (n_520), .B (n_1205), .CI (n_925), .CO (n_926), .S
       (n_927));
  CLKXOR2X1LVT g265(.A (n_2521), .B (n_924), .Y (n_925));
  OAI22X4LVT g266(.A0 (\shift_reg[1] [1]), .A1 (n_922), .B0
       (\shift_reg[4] [3]), .B1 (n_923), .Y (n_924));
  OAI21X2LVT g104(.A0 (\shift_reg[2] [5]), .A1 (n_982), .B0 (n_983), .Y
       (n_984));
  NOR2X6LVT g109(.A (\shift_reg[2] [2]), .B (n_1148), .Y (n_982));
  NAND2X4LVT g110(.A (\shift_reg[2] [2]), .B (n_1148), .Y (n_983));
  XNOR3X1LVT g105(.A (\shift_reg[4] [6]), .B (\shift_reg[2] [2]), .C
       (\shift_reg[2] [5]), .Y (n_985));
  NAND2X8LVT g1493(.A (n_2320), .B (n_2352), .Y (n_1034));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_13_groupi_g1087__1497(.A (n_2859), .B
       (n_1034), .Y (n_1037));
  NOR2X1LVT csa_tree_ADD_TC_OP_13_groupi_g1150__1543(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_105), .B (n_2351), .Y (n_1100));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_004_2__1558(.A
       (\shift_reg[1] [0]), .B (data_in_reg[4]), .CI (\shift_reg[5]
       [3]), .CO (n_1118), .S (n_1119));
  BUFX4LVT fopt1581(.A (\shift_reg[4] [6]), .Y (n_1148));
  OAI2BB2X4LVT g1592(.A0N (n_1178), .A1N (n_2858), .B0 (n_1178), .B1
       (n_2858), .Y (n_1182));
  NOR2BX2LVT g1593(.AN (n_1275), .B (n_484), .Y (n_1178));
  OAI21X4LVT g1605(.A0 (n_1204), .A1 (n_2247), .B0 (n_1199), .Y
       (n_1200));
  NAND2BX4LVT g1606(.AN (data_in_reg[2]), .B (\shift_reg[5] [4]), .Y
       (n_1199));
  XNOR3X1LVT g1610(.A (\shift_reg[4] [1]), .B (data_in_reg[2]), .C
       (\shift_reg[5] [4]), .Y (n_1205));
  NOR2BX4LVT g1732(.AN (\shift_reg[6] [0]), .B (n_538), .Y (n_1217));
  NOR2BX2LVT g1733(.AN (n_2842), .B (n_1566), .Y (n_1218));
  AOI21X4LVT g566(.A0 (n_1858), .A1 (n_1244), .B0 (n_1857), .Y
       (n_1246));
  NAND2X8LVT g586(.A (n_1240), .B (n_1243), .Y (n_1244));
  NAND3X4LVT g592(.A (csa_tree_ADD_TC_OP_13_groupi_n_203), .B (n_1946),
       .C (n_1945), .Y (n_1240));
  CLKINVX6LVT g627(.A (n_2187), .Y (n_1238));
  NAND2X6LVT g590(.A (n_1241), .B (n_1242), .Y (n_1243));
  CLKINVX6LVT g629(.A (csa_tree_ADD_TC_OP_13_groupi_n_203), .Y
       (n_1241));
  NAND2X6LVT g599(.A (n_1946), .B (n_1945), .Y (n_1242));
  BUFX6LVT g1860(.A (csa_tree_ADD_TC_OP_13_groupi_n_218), .Y (n_1247));
  CLKINVX6LVT g575(.A (n_1261), .Y (n_1262));
  NOR2X6LVT g587(.A (n_2042), .B (n_2039), .Y (n_1261));
  CLKINVX6LVT g612(.A (n_1251), .Y (n_1252));
  CLKINVX6LVT g614(.A (csa_tree_ADD_TC_OP_13_groupi_n_255), .Y
       (n_1251));
  CLKINVX6LVT g621(.A (csa_tree_ADD_TC_OP_13_groupi_n_220), .Y
       (n_1258));
  OR2X6LVT g559(.A (n_1246), .B (n_1915), .Y (n_1275));
  NOR2X4LVT g606(.A (n_1928), .B (n_1277), .Y (n_1278));
  INVX3LVT g613(.A (n_1251), .Y (n_1277));
  NAND2X4LVT g611(.A (n_1282), .B (n_1247), .Y (n_1283));
  BUFX4LVT g618(.A (n_2194), .Y (n_1282));
  CLKINVX6LVT g578(.A (n_1244), .Y (n_1298));
  OAI21X4LVT g560(.A0 (n_2610), .A1 (n_1302), .B0 (n_1303), .Y
       (n_1304));
  NOR2X4LVT g569(.A (n_1262), .B (n_2007), .Y (n_1302));
  NAND2X2LVT g573(.A (n_1262), .B (n_2007), .Y (n_1303));
  NAND2X6LVT g162(.A (n_1336), .B (n_1341), .Y (n_1342));
  NOR2X4LVT g165(.A (n_2664), .B (n_1335), .Y (n_1336));
  NOR3X4LVT g167(.A (n_2667), .B (n_2483), .C (n_2521), .Y (n_1335));
  NOR2X6LVT g1865(.A (n_2663), .B (n_1340), .Y (n_1341));
  CLKINVX8LVT fopt182(.A (n_2483), .Y (n_1337));
  NOR3X4LVT g168(.A (n_2522), .B (n_1337), .C (n_2667), .Y (n_1340));
  INVX1LVT g161(.A (csa_tree_ADD_TC_OP_13_groupi_n_242), .Y (n_1346));
  CLKINVX4LVT g155(.A (csa_tree_ADD_TC_OP_13_groupi_n_230), .Y
       (n_1355));
  INVX2LVT g154(.A (n_1355), .Y (n_1365));
  OAI22X2LVT g20(.A0 (n_2841), .A1 (n_1583), .B0 (n_1581), .B1
       (n_2874), .Y (n_1376));
  NAND2X6LVT g22(.A (n_2874), .B (n_1581), .Y (n_1379));
  ADDFHX2LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_012_3__1887(.A
       (n_3059), .B (n_675), .CI (n_1754), .CO (n_1399), .S (n_1400));
  NAND3X6LVT g2079(.A (n_1429), .B (n_2506), .C (n_2784), .Y (n_1443));
  NAND2X4LVT g2084(.A (n_2508), .B (n_1794), .Y (n_1429));
  NAND2X2LVT g2092(.A (n_1566), .B (n_1581), .Y (n_1430));
  INVX2LVT g2096(.A (n_1218), .Y (n_1436));
  INVX2LVT g79(.A (n_1316), .Y (n_1445));
  NAND2X8LVT g1900(.A (n_1798), .B (n_1948), .Y (n_1448));
  BUFX2LVT g1901(.A (csa_tree_ADD_TC_OP_13_groupi_n_112), .Y (n_1450));
  NAND2X4LVT g67(.A (n_2057), .B (n_2496), .Y (n_1457));
  CLKINVX4LVT g72(.A (n_1451), .Y (n_1316));
  NAND2X4LVT g73(.A (csa_tree_ADD_TC_OP_13_groupi_n_108), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_112), .Y (n_1451));
  BUFX6LVT g1902(.A (n_2646), .Y (n_1453));
  OAI21X4LVT g120(.A0 (n_1557), .A1 (n_1469), .B0 (n_2403), .Y
       (n_1473));
  CLKAND2X6LVT g1915(.A (\shift_reg[6] [5]), .B (\shift_reg[0] [4]), .Y
       (n_1469));
  NAND2X4LVT g119(.A (n_2400), .B (n_1482), .Y (n_1483));
  NOR3X2LVT g124(.A (n_1558), .B (\shift_reg[6] [5]), .C (n_2397), .Y
       (n_1476));
  NOR2X2LVT g122(.A (n_2402), .B (n_1481), .Y (n_1482));
  NOR3X4LVT g123(.A (n_1555), .B (n_1592), .C (n_2669), .Y (n_1481));
  CLKINVX6 g1929(.A (\shift_reg[5] [3]), .Y (n_1488));
  NAND2X4LVT g1931(.A (n_3062), .B (n_1499), .Y (n_1500));
  NOR3X2LVT g1933(.A (\shift_reg[5] [3]), .B (\shift_reg[3] [1]), .C
       (n_1492), .Y (n_1493));
  NOR2X4LVT g1937(.A (n_2109), .B (n_1498), .Y (n_1499));
  NOR3X2LVT g1939(.A (\shift_reg[0] [3]), .B (\shift_reg[3] [1]), .C
       (n_1488), .Y (n_1498));
  NAND2X6LVT g9(.A (n_2483), .B (n_2522), .Y (n_1503));
  ADDFX1LVT g1940(.A (\shift_reg[4] [5]), .B (n_1506), .CI (n_2649),
       .CO (n_1507), .S (n_1508));
  OAI21X4LVT g1950(.A0 (n_3016), .A1 (\shift_reg[4] [7]), .B0 (n_3015),
       .Y (n_1527));
  NAND3X6LVT g16(.A (n_1457), .B (n_1797), .C (n_1448), .Y (n_1529));
  OAI32X4LVT g230(.A0 (n_1535), .A1 (n_1537), .A2 (n_2495), .B0
       (n_1536), .B1 (n_1539), .Y (n_1540));
  BUFX4LVT g237(.A (n_1534), .Y (n_1535));
  INVX2LVT g238(.A (n_1909), .Y (n_1534));
  INVX2LVT g235(.A (n_1536), .Y (n_1537));
  NOR2X4LVT g236(.A (n_3052), .B (n_2646), .Y (n_1536));
  NOR2X6LVT g233(.A (n_1535), .B (n_2495), .Y (n_1539));
  CLKBUFX2LVT fopt1961(.A (n_1549), .Y (n_1548));
  CLKINVX8LVT fopt1962(.A (n_2636), .Y (n_1549));
  CLKINVX6LVT fopt1963(.A (n_2271), .Y (n_1550));
  CLKINVX6LVT fopt1966(.A (n_1558), .Y (n_1555));
  CLKINVX4 fopt1967(.A (n_1558), .Y (n_1557));
  CLKINVX8LVT fopt1968(.A (\shift_reg[0] [7]), .Y (n_1558));
  CLKINVX4LVT fopt1988(.A (n_1581), .Y (n_1583));
  CLKINVX12LVT fopt1989(.A (n_2842), .Y (n_1581));
  CLKINVX6LVT fopt1994(.A (n_1760), .Y (n_1592));
  CLKAND2X6LVT csa_tree_ADD_TC_OP_13_groupi_g1119__2038(.A (n_1954), .B
       (n_2855), .Y (n_1636));
  NAND2X8LVT g275(.A (n_3085), .B (n_2804), .Y (n_1649));
  OR2X4LVT g2050(.A (n_2207), .B (n_2209), .Y (n_1674));
  CLKINVX6LVT g281(.A (n_1549), .Y (n_1676));
  BUFX2LVT g2052(.A (\shift_reg[2] [4]), .Y (n_1681));
  NAND2X8LVT g14(.A (n_2446), .B (n_2425), .Y (n_1695));
  BUFX2LVT g131(.A (csa_tree_ADD_TC_OP_13_groupi_n_310), .Y (n_1697));
  INVX2LVT g2063(.A (n_2551), .Y (n_1700));
  CLKINVX4LVT g2065(.A (n_1828), .Y (n_1708));
  XOR3X1LVT g2067(.A (n_2551), .B (n_2586), .C
       (csa_tree_ADD_TC_OP_13_groupi_n_354), .Y (n_1710));
  NOR3X6LVT g2081(.A (n_1716), .B (n_1719), .C (n_1720), .Y (n_1721));
  INVX3LVT g2082(.A (n_1715), .Y (n_1716));
  BUFX6LVT g4(.A (n_672), .Y (n_1715));
  NOR2X6LVT g2089(.A (n_1717), .B (n_1718), .Y (n_1719));
  BUFX6LVT fopt291(.A (csa_tree_ADD_TC_OP_13_groupi_n_252), .Y
       (n_1717));
  CLKINVX4LVT g2090(.A (n_2904), .Y (n_1718));
  CLKAND2X6LVT g2097(.A (n_1717), .B (n_1718), .Y (n_1720));
  NOR2X6LVT g2099(.A (n_1719), .B (n_1720), .Y (n_1722));
  CLKINVX6LVT g2102(.A (csa_tree_ADD_TC_OP_13_groupi_n_214), .Y
       (n_1728));
  BUFX6LVT g2103(.A (csa_tree_ADD_TC_OP_13_groupi_n_217), .Y (n_1729));
  CLKINVX12LVT g2105(.A (n_1728), .Y (n_1731));
  CLKINVX4LVT g2106(.A (n_1729), .Y (n_1732));
  OAI21X4LVT g2115(.A0 (n_2480), .A1 (n_1752), .B0 (n_1753), .Y
       (n_1754));
  NOR2X8LVT g2116(.A (n_1729), .B (n_1731), .Y (n_1752));
  NAND2X6LVT g2118(.A (n_1729), .B (n_1731), .Y (n_1753));
  INVX2LVT g2121(.A (n_1718), .Y (n_1755));
  OA21X1LVT g2123(.A0 (n_1717), .A1 (n_1755), .B0 (n_1715), .Y
       (n_1758));
  NOR2X4LVT g2125(.A (n_1592), .B (csa_tree_ADD_TC_OP_13_groupi_n_51),
       .Y (n_1762));
  CLKINVX8LVT g2126(.A (\shift_reg[6] [5]), .Y (n_1760));
  NOR2X4LVT g70(.A (\shift_reg[6] [4]), .B (\shift_reg[6] [7]), .Y
       (n_1764));
  CLKINVX6LVT g49(.A (n_2233), .Y (n_1780));
  NOR2X4LVT g2135(.A (n_1784), .B (n_516), .Y (n_1785));
  NOR2X4LVT g2136(.A (n_1783), .B (n_986), .Y (n_1784));
  NAND2X4LVT g2137(.A (\shift_reg[5] [1]), .B (\shift_reg[1] [3]), .Y
       (n_1783));
  NOR2X8LVT g2138(.A (n_3052), .B (n_2423), .Y (n_1787));
  NAND2X6LVT g2142(.A (n_1787), .B (n_1695), .Y (n_1794));
  OAI21X4LVT g87(.A0 (n_2514), .A1 (n_2312), .B0 (n_1445), .Y (n_1797));
  NOR2X4LVT g2144(.A (n_2513), .B (n_2312), .Y (n_1798));
  CLKAND2X12LVT g2147(.A (n_710), .B (n_2425), .Y (n_1799));
  NAND2X8LVT g2152(.A (n_1799), .B (n_1034), .Y (n_1806));
  ADDFHX1LVT g309(.A (csa_tree_ADD_TC_OP_13_groupi_n_352), .B (n_1119),
       .CI (csa_tree_ADD_TC_OP_13_groupi_n_347), .CO (n_1824), .S
       (n_1827));
  XOR3X1LVT g304(.A (csa_tree_ADD_TC_OP_13_groupi_n_310), .B (n_1827),
       .C (n_2590), .Y (n_1828));
  AOI2BB1X1LVT g306(.A0N (n_1829), .A1N (n_1697), .B0 (n_2590), .Y
       (n_1830));
  BUFX2LVT g308(.A (n_1827), .Y (n_1829));
  NOR2X8LVT g187(.A (n_1837), .B (n_1840), .Y (n_1841));
  NOR2X8LVT g2166(.A (n_1835), .B (n_1836), .Y (n_1837));
  CLKINVX6LVT g2167(.A (n_1834), .Y (n_1835));
  BUFX6LVT g2168(.A (n_2017), .Y (n_1834));
  INVX2LVT g2169(.A (csa_tree_ADD_TC_OP_13_groupi_n_268), .Y (n_1836));
  NOR2X6LVT g194(.A (n_1838), .B (n_1839), .Y (n_1840));
  CLKINVX6LVT g204(.A (n_2573), .Y (n_1838));
  NOR2X4LVT g2170(.A (csa_tree_ADD_TC_OP_13_groupi_n_268), .B (n_1834),
       .Y (n_1839));
  CLKINVX6LVT g183(.A (n_1854), .Y (n_1855));
  NOR2X8LVT g184(.A (n_1911), .B (n_1913), .Y (n_1854));
  CLKINVX6LVT g203(.A (n_1838), .Y (n_1845));
  NAND3X8LVT g192(.A (n_1835), .B (n_1848), .C (n_1845), .Y (n_1849));
  CLKINVX6LVT g200(.A (n_1847), .Y (n_1848));
  BUFX6LVT g2171(.A (csa_tree_ADD_TC_OP_13_groupi_n_268), .Y (n_1847));
  NAND3X4LVT g2172(.A (n_1835), .B (n_1847), .C (n_1838), .Y (n_1851));
  CLKAND2X2LVT g182(.A (n_1855), .B (n_1949), .Y (n_1857));
  OR2X6LVT g181(.A (n_1855), .B (n_1949), .Y (n_1858));
  INVX1LVT g2176(.A (n_2351), .Y (n_1863));
  ADDFHX2LVT g2178(.A (n_2374), .B (n_1118), .CI (n_2027), .CO
       (n_1870), .S (n_1871));
  ADDFHX1LVT g2182(.A (n_2372), .B (n_2581), .CI (n_2550), .CO
       (n_1873), .S (n_1874));
  NAND2X8LVT g2184(.A (n_1878), .B (n_1881), .Y (n_1882));
  OR2X4LVT g2185(.A (n_1875), .B (n_1877), .Y (n_1878));
  CLKINVX4LVT g2186(.A (n_1873), .Y (n_1875));
  CLKINVX6LVT g2187(.A (n_1871), .Y (n_1877));
  NAND2X4LVT g2189(.A (n_1879), .B (n_927), .Y (n_1881));
  NAND2X4LVT g2190(.A (n_1875), .B (n_1877), .Y (n_1879));
  NOR2X4LVT g2192(.A (csa_tree_ADD_TC_OP_13_groupi_n_230), .B (n_1883),
       .Y (n_1884));
  INVX3LVT g2193(.A (n_1882), .Y (n_1883));
  NAND2X8LVT g2195(.A (n_1889), .B (n_1892), .Y (n_1893));
  OAI21X4LVT g2196(.A0 (n_1885), .A1 (n_1887), .B0 (n_1888), .Y
       (n_1889));
  NOR2X6LVT g2197(.A (n_1875), .B (n_1871), .Y (n_1885));
  NOR2X6LVT g2198(.A (n_1886), .B (n_1877), .Y (n_1887));
  CLKINVX4LVT g2199(.A (n_1875), .Y (n_1886));
  INVX2LVT g2200(.A (n_927), .Y (n_1888));
  NAND3X6LVT g2201(.A (n_1890), .B (n_927), .C (n_1891), .Y (n_1892));
  INVX3LVT g2202(.A (n_1885), .Y (n_1890));
  CLKINVX6LVT g2203(.A (n_1887), .Y (n_1891));
  INVX3LVT g2205(.A (n_1893), .Y (n_1895));
  NOR2X2LVT g2206(.A (n_1346), .B (n_1895), .Y (n_1897));
  CLKINVX6LVT g38(.A (n_1283), .Y (n_1898));
  NOR2X8LVT g36(.A (n_1841), .B (n_1900), .Y (n_1901));
  NOR2X8LVT g37(.A (n_1282), .B (n_1247), .Y (n_1900));
  NOR2X8LVT g2210(.A (n_1304), .B (n_2735), .Y (n_1908));
  NAND2X8LVT g2212(.A (n_1304), .B (n_2735), .Y (n_1909));
  NAND2X8LVT g2213(.A (n_1910), .B (n_1849), .Y (n_1911));
  NAND2X6LVT g12(.A (n_1837), .B (n_1845), .Y (n_1910));
  NAND2X6LVT g2214(.A (n_1912), .B (n_1851), .Y (n_1913));
  NAND3X6LVT g23(.A (n_1834), .B (n_1838), .C (n_1848), .Y (n_1912));
  NOR2X8LVT g2215(.A (n_2432), .B (n_2775), .Y (n_1915));
  NOR2X6LVT g2217(.A (n_1884), .B (n_1919), .Y (n_1920));
  NOR2X8LVT g2218(.A (n_1882), .B (n_1355), .Y (n_1919));
  CLKINVX12LVT g118(.A (n_1927), .Y (n_1928));
  NOR2X8LVT g2219(.A (n_1923), .B (n_1926), .Y (n_1927));
  NOR2X4LVT g129(.A (n_1921), .B (n_1922), .Y (n_1923));
  CLKINVX6LVT g133(.A (n_2578), .Y (n_1921));
  CLKINVX4LVT g2220(.A (csa_tree_ADD_TC_OP_13_groupi_n_312), .Y
       (n_1922));
  NOR2X8LVT g2221(.A (n_1924), .B (n_1925), .Y (n_1926));
  CLKINVX6LVT g2222(.A (csa_tree_ADD_TC_OP_13_groupi_n_270), .Y
       (n_1924));
  CLKAND2X6LVT g2223(.A (n_1921), .B (n_1922), .Y (n_1925));
  CLKINVX4LVT g117(.A (n_1928), .Y (n_1929));
  CLKAND2X6LVT g115(.A (n_1941), .B (n_2187), .Y (n_1942));
  CLKINVX6LVT g116(.A (n_2730), .Y (n_1941));
  CLKINVX4LVT g2232(.A (n_1921), .Y (n_1934));
  NAND2X6LVT g113(.A (n_1941), .B (n_1238), .Y (n_1945));
  NAND2X4LVT g114(.A (n_2730), .B (n_2187), .Y (n_1946));
  NAND2X8LVT g2236(.A (n_2313), .B (n_2496), .Y (n_1948));
  ADDFHX4LVT g2240(.A (n_2025), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_231), .CI (n_2574), .CO
       (n_1949), .S (n_1952));
  OAI21X4LVT g2241(.A0 (n_2384), .A1 (n_2745), .B0 (n_2383), .Y
       (n_1954));
  NOR2X8LVT g34(.A (n_2849), .B (n_2848), .Y (n_1958));
  NAND2X8LVT g2247(.A (n_1806), .B (n_1958), .Y (n_1961));
  NAND2X4LVT g2253(.A (csa_tree_ADD_TC_OP_13_groupi_n_216), .B
       (n_1966), .Y (n_1967));
  INVX3LVT g2254(.A (n_1965), .Y (n_1966));
  BUFX6LVT g2255(.A (csa_tree_ADD_TC_OP_13_groupi_n_219), .Y (n_1965));
  NAND2X8LVT g2256(.A (n_1965), .B (n_1968), .Y (n_1969));
  CLKINVX6LVT g2257(.A (csa_tree_ADD_TC_OP_13_groupi_n_216), .Y
       (n_1968));
  NAND2X6LVT g2262(.A (n_1966), .B (n_1968), .Y (n_1980));
  NOR2X4LVT g2263(.A (n_1966), .B (n_1968), .Y (n_1981));
  CLKINVX6LVT g56(.A (n_3044), .Y (n_2007));
  NOR2X4LVT g60(.A (n_2187), .B (n_1941), .Y (n_2004));
  CLKINVX6LVT g63(.A (n_1262), .Y (n_2008));
  ADDFHX1LVT g214(.A (n_2016), .B (n_2254), .CI (n_2436), .CO (n_2017),
       .S (n_2018));
  ADDFHX1LVT g218(.A (\shift_reg[0] [5]), .B (n_2014), .CI (n_2545),
       .CO (n_2016), .S (n_2019));
  NOR2X6LVT g222(.A (\shift_reg[6] [2]), .B (n_1760), .Y (n_2014));
  OAI21X4LVT g216(.A0 (n_2020), .A1 (n_2023), .B0 (n_2024), .Y
       (n_2025));
  INVXLLVT g217(.A (n_2019), .Y (n_2020));
  NOR2X6LVT g220(.A (n_2021), .B (n_2022), .Y (n_2023));
  BUFX3LVT g224(.A (n_1870), .Y (n_2021));
  BUFX12LVT g225(.A (n_2437), .Y (n_2022));
  NAND2X4LVT g221(.A (n_2021), .B (n_2022), .Y (n_2024));
  XOR3X1LVT g215(.A (n_2019), .B (n_1870), .C (n_2437), .Y (n_2026));
  NOR2X2LVT g219(.A (n_2014), .B (n_1762), .Y (n_2027));
  NOR3X8LVT g2273(.A (n_1549), .B (n_2208), .C (n_2390), .Y (n_2031));
  NOR3X4LVT g81(.A (n_1258), .B (n_2037), .C (n_2038), .Y (n_2039));
  NOR2X4LVT g85(.A (n_1928), .B (n_1251), .Y (n_2037));
  NOR2X6LVT g84(.A (n_1929), .B (n_1252), .Y (n_2038));
  NOR2X6LVT g2277(.A (csa_tree_ADD_TC_OP_13_groupi_n_220), .B (n_2041),
       .Y (n_2042));
  NOR2X4LVT g83(.A (n_2037), .B (n_2038), .Y (n_2041));
  OAI21X4LVT g2279(.A0 (n_2098), .A1 (n_500), .B0 (n_2044), .Y
       (n_2045));
  OR2X1LVT g2280(.A (data_in_reg[4]), .B (n_2043), .Y (n_2044));
  ADDFHX1LVT g2281(.A (\shift_reg[2] [7]), .B (\shift_reg[4] [6]), .CI
       (n_2043), .CO (n_2046), .S (n_2047));
  NOR2BX1LVT g149(.AN (csa_tree_ADD_TC_OP_13_groupi_n_108), .B
       (n_2055), .Y (n_2056));
  NAND2X6LVT g2285(.A (n_2498), .B (n_2843), .Y (n_2055));
  NOR4X8LVT g144(.A (n_2055), .B (n_1316), .C
       (csa_tree_ADD_TC_OP_13_groupi_n_10), .D (n_1453), .Y (n_2057));
  NOR2X8LVT g103(.A (n_2087), .B (n_2460), .Y (n_2088));
  INVX3LVT g2295(.A (n_2086), .Y (n_2087));
  NOR2X6LVT g106(.A (n_2084), .B (n_2085), .Y (n_2086));
  NOR2X4LVT g108(.A (n_1729), .B (n_1728), .Y (n_2084));
  NOR2X8LVT g2296(.A (n_1731), .B (n_1732), .Y (n_2085));
  NOR2X6LVT g102(.A (n_2544), .B (n_2089), .Y (n_2090));
  NOR2X6LVT g2297(.A (n_2084), .B (n_2085), .Y (n_2089));
  OAI21X4LVT g101(.A0 (n_2086), .A1 (n_2839), .B0 (n_2092), .Y
       (n_2093));
  NAND2X6LVT g2298(.A (n_2089), .B (n_2839), .Y (n_2092));
  NOR2X4LVT g2301(.A (n_2094), .B (n_2043), .Y (n_2096));
  NOR2X2LVT g2304(.A (\shift_reg[0] [6]), .B (n_2094), .Y (n_2098));
  NOR2X2LVT g48(.A (\shift_reg[5] [3]), .B (\shift_reg[0] [3]), .Y
       (n_2106));
  NOR3BX4LVT g47(.AN (\shift_reg[3] [1]), .B (n_1488), .C (n_1492), .Y
       (n_2109));
  CLKINVX12LVT g1386(.A (n_3008), .Y (n_2187));
  NOR2X8LVT g2313(.A (n_2166), .B (n_2168), .Y (n_2169));
  NOR3X4LVT g1406(.A (n_2161), .B (n_2164), .C (n_2165), .Y (n_2166));
  INVX2LVT g1424(.A (n_1342), .Y (n_2161));
  NOR2X6LVT g1416(.A (n_2162), .B (n_2163), .Y (n_2164));
  CLKINVX6LVT g1423(.A (n_2045), .Y (n_2162));
  BUFX6LVT g2314(.A (n_2673), .Y (n_2163));
  CLKAND2X12LVT g1414(.A (n_2162), .B (n_2163), .Y (n_2165));
  NOR2X6LVT g1405(.A (n_1342), .B (n_2167), .Y (n_2168));
  NOR2X8LVT g1412(.A (n_2164), .B (n_2165), .Y (n_2167));
  NOR2X6LVT g1392(.A (n_2179), .B (n_2181), .Y (n_2182));
  NOR2X6LVT g2315(.A (n_2172), .B (n_2178), .Y (n_2179));
  NAND2X8LVT g2316(.A (n_2170), .B (n_2171), .Y (n_2172));
  NAND2X2LVT g1419(.A (n_2670), .B (n_3017), .Y (n_2170));
  OAI21X4LVT g1407(.A0 (n_2670), .A1 (n_3017), .B0 (n_1500), .Y
       (n_2171));
  NOR2X4LVT g1410(.A (n_2174), .B (n_2177), .Y (n_2178));
  CLKAND2X6LVT g1417(.A (csa_tree_ADD_TC_OP_13_groupi_n_321), .B
       (n_3068), .Y (n_2174));
  NOR2X8LVT g1411(.A (n_2175), .B (n_2176), .Y (n_2177));
  INVX2LVT g1421(.A (csa_tree_ADD_TC_OP_13_groupi_n_319), .Y (n_2175));
  NOR2X4LVT g1415(.A (csa_tree_ADD_TC_OP_13_groupi_n_321), .B (n_3068),
       .Y (n_2176));
  CLKAND2X6LVT g2317(.A (n_2172), .B (n_2180), .Y (n_2181));
  NOR2X6LVT g1409(.A (n_2174), .B (n_2177), .Y (n_2180));
  CLKINVX6LVT g1397(.A (n_2169), .Y (n_2184));
  NAND2X8LVT g1390(.A (n_2190), .B (n_2193), .Y (n_2194));
  NAND2X6LVT g1396(.A (n_2172), .B (n_2184), .Y (n_2190));
  INVX3 g1399(.A (n_2172), .Y (n_2188));
  NAND2X6LVT g1391(.A (n_2191), .B (n_2192), .Y (n_2193));
  INVX2LVT g1400(.A (n_2180), .Y (n_2191));
  NAND2X6LVT g1393(.A (n_2188), .B (n_2169), .Y (n_2192));
  XOR3X1LVT g1403(.A (n_2670), .B (n_3017), .C (n_1500), .Y (n_2195));
  XOR3X1LVT g1408(.A (n_3070), .B (csa_tree_ADD_TC_OP_13_groupi_n_321),
       .C (csa_tree_ADD_TC_OP_13_groupi_n_319), .Y (n_2196));
  OAI21X4LVT g1402(.A0 (n_2161), .A1 (n_2198), .B0 (n_2199), .Y
       (n_2200));
  NOR2X6LVT g1413(.A (n_2163), .B (n_2197), .Y (n_2198));
  CLKINVX6LVT g1422(.A (n_2162), .Y (n_2197));
  NAND2X4LVT g1418(.A (n_2163), .B (n_2197), .Y (n_2199));
  NOR3X6LVT g2318(.A (n_2202), .B (n_2206), .C (n_2207), .Y (n_2208));
  INVX2LVT g2319(.A (n_2201), .Y (n_2202));
  NAND2X4LVT g2320(.A (n_1920), .B (n_2640), .Y (n_2201));
  INVX2LVT g2321(.A (n_2205), .Y (n_2206));
  NAND2X8LVT g2322(.A (n_2203), .B (n_2529), .Y (n_2205));
  INVX2LVT g2323(.A (n_1920), .Y (n_2203));
  OR2X6LVT g2325(.A (n_2642), .B (n_1897), .Y (n_2207));
  NAND2X8LVT g2326(.A (n_2201), .B (n_2205), .Y (n_2209));
  CLKINVX12LVT g2328(.A (\shift_reg[5] [1]), .Y (n_2210));
  OAI21X4LVT g2329(.A0 (\shift_reg[5] [3]), .A1 (n_2214), .B0 (n_2215),
       .Y (n_2216));
  NOR2X6LVT g2331(.A (\shift_reg[3] [1]), .B (n_1492), .Y (n_2214));
  CLKINVX8LVT g2332(.A (\shift_reg[0] [3]), .Y (n_1492));
  NAND2X4LVT g2333(.A (\shift_reg[3] [1]), .B (n_1492), .Y (n_2215));
  CLKINVX6LVT g2335(.A (n_2237), .Y (n_2217));
  CLKINVX6LVT g2336(.A (n_2217), .Y (n_2219));
  CLKINVX6LVT g2337(.A (n_2240), .Y (n_2220));
  CLKAND2X3LVT g2339(.A (n_2240), .B (n_2219), .Y (n_2226));
  NOR2X8LVT g2343(.A (n_2231), .B (n_2747), .Y (n_2233));
  AOI21X4LVT g2344(.A0 (n_2379), .A1 (n_1649), .B0 (n_1952), .Y
       (n_2231));
  OAI21X2LVT g75(.A0 (n_1901), .A1 (n_2234), .B0 (n_2217), .Y (n_2239));
  BUFX2LVT fopt2346(.A (n_1898), .Y (n_2234));
  NOR2X6LVT g2347(.A (n_2235), .B (n_3049), .Y (n_2237));
  NOR2X4LVT g2348(.A (n_1258), .B (n_1278), .Y (n_2235));
  NOR2X8LVT g2350(.A (n_1898), .B (n_1901), .Y (n_2240));
  OAI21X4LVT g2351(.A0 (n_2522), .A1 (n_2242), .B0 (n_2243), .Y
       (n_2244));
  NOR2X4LVT g2352(.A (\shift_reg[1] [1]), .B (\shift_reg[4] [3]), .Y
       (n_2242));
  NAND2X2LVT g2353(.A (\shift_reg[1] [1]), .B (\shift_reg[4] [3]), .Y
       (n_2243));
  NOR2X4LVT g2355(.A (\shift_reg[5] [4]), .B (n_2246), .Y (n_2247));
  NAND2X4LVT g2358(.A (n_1244), .B (n_2271), .Y (n_2248));
  NAND2X6LVT g2359(.A (n_1298), .B (n_1550), .Y (n_2249));
  OAI2BB2X4LVT g2360(.A0N (n_2251), .A1N (n_3064), .B0 (n_2251), .B1
       (n_3064), .Y (n_2254));
  NOR2X4LVT g41(.A (n_1764), .B (csa_tree_ADD_TC_OP_13_groupi_n_4), .Y
       (n_2251));
  NOR2X6LVT g40(.A (csa_tree_ADD_TC_OP_13_groupi_n_4), .B (n_1764), .Y
       (n_2255));
  XNOR3X1LVT g2363(.A (\shift_reg[3] [3]), .B (n_2259), .C
       (\shift_reg[0] [5]), .Y (n_2260));
  NOR2X4LVT g2370(.A (n_1954), .B (n_2855), .Y (n_2266));
  CLKINVX4LVT g2371(.A (n_2267), .Y (n_484));
  NAND2X8LVT g2372(.A (n_1246), .B (n_1915), .Y (n_2267));
  NOR2X8LVT g2373(.A (n_2269), .B (n_2270), .Y (n_2271));
  NOR2X4LVT g2374(.A (n_1949), .B (n_1854), .Y (n_2269));
  NOR2X6LVT g50(.A (n_1855), .B (n_2536), .Y (n_2270));
  NOR2X4LVT g2376(.A (n_2217), .B (n_2240), .Y (n_2272));
  NOR2X8LVT g2377(.A (n_2219), .B (n_2220), .Y (n_2273));
  NOR2X6LVT g2386(.A (n_2272), .B (n_2273), .Y (n_2282));
  NAND2X6LVT g2391(.A (n_2406), .B (n_2293), .Y (n_2294));
  INVX3LVT g2392(.A (n_2292), .Y (n_2293));
  CLKAND2X6LVT g111(.A (n_2475), .B (n_2291), .Y (n_2292));
  CLKINVX4LVT g2394(.A (n_1981), .Y (n_2291));
  NAND2X4LVT g2395(.A (n_2296), .B (n_2093), .Y (n_2297));
  NAND2X4LVT g2396(.A (n_2475), .B (n_2541), .Y (n_2296));
  CLKINVX6LVT fopt2404(.A (n_2305), .Y (n_2306));
  CLKINVX12LVT fopt66(.A (n_2304), .Y (n_2305));
  NOR2X8LVT g2405(.A (n_2750), .B (n_2478), .Y (n_2304));
  NAND2X6LVT g2407(.A (n_2308), .B (n_2305), .Y (n_2309));
  CLKINVX4LVT fopt67(.A (n_2226), .Y (n_2308));
  NOR2X6LVT g2408(.A (n_2311), .B (n_1787), .Y (n_2312));
  NAND2X6LVT g2409(.A (n_2843), .B (n_2498), .Y (n_2311));
  NOR3X8LVT g2410(.A (n_2311), .B (csa_tree_ADD_TC_OP_13_groupi_n_10),
       .C (n_1453), .Y (n_2313));
  NAND3X6LVT g2415(.A (n_1674), .B (n_1676), .C (n_2388), .Y (n_2320));
  NAND2X8LVT g2423(.A (n_2389), .B (n_1780), .Y (n_2327));
  INVX1LVT fopt2428(.A (n_2334), .Y (n_2333));
  INVX3LVT fopt1(.A (n_2390), .Y (n_2334));
  CLKINVX6LVT fopt2429(.A (n_2338), .Y (n_2336));
  CLKBUFX2LVT fopt2430(.A (n_2338), .Y (n_2337));
  CLKINVX12LVT fopt2431(.A (n_2327), .Y (n_2338));
  AOI21X4LVT g2440(.A0 (n_2351), .A1 (n_2334), .B0 (n_2338), .Y
       (n_2352));
  CLKBUFX6LVT g2441(.A (n_2350), .Y (n_2351));
  NOR2X8LVT g2442(.A (n_2348), .B (n_2349), .Y (n_2350));
  INVX2LVT g2443(.A (n_2207), .Y (n_2348));
  CLKINVX6LVT g2444(.A (n_2209), .Y (n_2349));
  CLKINVX6LVT g2445(.A (n_2350), .Y (n_2353));
  OAI21X4LVT g2447(.A0 (n_2389), .A1 (n_1780), .B0 (n_2350), .Y
       (n_2355));
  CLKAND2X6LVT g2459(.A (\shift_reg[3] [5]), .B (data_in_reg[5]), .Y
       (n_2368));
  XOR3X1LVT g2462(.A (\shift_reg[4] [2]), .B (\shift_reg[1] [2]), .C
       (csa_tree_ADD_TC_OP_13_groupi_n_24), .Y (n_2372));
  OAI2BB1X4LVT g2463(.A0N (\shift_reg[1] [2]), .A1N
       (csa_tree_ADD_TC_OP_13_groupi_n_24), .B0 (n_2373), .Y (n_2374));
  OAI21X4LVT g2464(.A0 (\shift_reg[1] [2]), .A1
       (csa_tree_ADD_TC_OP_13_groupi_n_24), .B0 (n_2531), .Y (n_2373));
  NAND2X6LVT g2467(.A (n_3087), .B (n_2639), .Y (n_2379));
  NAND2X2LVT g2472(.A (n_2639), .B (n_3085), .Y (n_2383));
  NOR2X8LVT g2473(.A (n_2803), .B (n_3085), .Y (n_2384));
  NAND2X4LVT g2474(.A (n_2233), .B (n_2387), .Y (n_2388));
  NOR2X8LVT g2475(.A (n_2385), .B (n_3065), .Y (n_2387));
  AND2X2LVT g2476(.A (n_1882), .B (n_1365), .Y (n_2385));
  CLKINVX6LVT g2478(.A (n_2387), .Y (n_2389));
  CLKAND2X12LVT g2479(.A (n_2387), .B (n_2233), .Y (n_2390));
  CLKINVX12LVT fopt2488(.A (\shift_reg[0] [4]), .Y (n_2397));
  AOI31X4LVT g2489(.A0 (n_1555), .A1 (n_1592), .A2 (n_2397), .B0
       (n_1476), .Y (n_2400));
  NOR3X4LVT g2491(.A (n_1555), .B (n_1760), .C (n_2397), .Y (n_2402));
  NAND2X6LVT g2493(.A (n_1760), .B (n_2397), .Y (n_2403));
  NOR2X4LVT g2494(.A (n_2088), .B (n_2090), .Y (n_2406));
  NAND2X8LVT g2503(.A (n_2355), .B (n_2336), .Y (n_2415));
  NOR2X8LVT g44(.A (n_2647), .B (n_1909), .Y (n_2423));
  NAND2X8LVT g2509(.A (n_2239), .B (n_2309), .Y (n_2421));
  NOR2X8LVT g2510(.A (n_2646), .B (n_1908), .Y (n_2425));
  NOR2X6LVT g89(.A (n_1262), .B (n_3044), .Y (n_2428));
  NOR2X8LVT g90(.A (n_2008), .B (n_2007), .Y (n_2429));
  NOR3X6LVT g2515(.A (n_2428), .B (n_2429), .C (n_2610), .Y (n_2432));
  ADDFHX2LVT g2516(.A (n_1200), .B (n_2435), .CI (n_2244), .CO
       (n_2436), .S (n_2437));
  OAI21X4LVT g2517(.A0 (\shift_reg[2] [2]), .A1 (n_2433), .B0 (n_2434),
       .Y (n_2435));
  NOR2X4LVT g2518(.A (\shift_reg[1] [3]), .B (n_2210), .Y (n_2433));
  NAND2X4LVT g2519(.A (\shift_reg[1] [3]), .B (n_2210), .Y (n_2434));
  OAI21X4LVT g2520(.A0 (n_986), .A1 (n_518), .B0 (n_2439), .Y (n_2440));
  OAI21X4LVT g2521(.A0 (\shift_reg[1] [3]), .A1 (n_2210), .B0 (n_986),
       .Y (n_2439));
  NOR3X8LVT g2522(.A (n_2338), .B (n_2441), .C (n_2031), .Y (n_2442));
  NOR2X8LVT g2523(.A (n_2353), .B (n_2390), .Y (n_2441));
  NOR2X8LVT g2524(.A (n_2929), .B (n_2415), .Y (n_2444));
  NAND2X8LVT g2526(.A (n_1275), .B (n_2445), .Y (n_2446));
  NAND2X8LVT g2527(.A (n_2267), .B (n_1636), .Y (n_2445));
  OR2X6LVT g2530(.A (n_1954), .B (n_2855), .Y (n_2448));
  CLKMX2X3LVT g2531(.A (n_2837), .B (n_2480), .S0 (n_2539), .Y
       (n_2460));
  NOR2X4LVT g175(.A (n_2452), .B (n_2453), .Y (n_2454));
  CLKINVX6LVT g180(.A (csa_tree_ADD_TC_OP_13_groupi_n_221), .Y
       (n_2452));
  CLKINVX6LVT g2532(.A (csa_tree_ADD_TC_OP_13_groupi_n_253), .Y
       (n_2453));
  AOI21X4LVT g172(.A0 (n_2452), .A1 (n_2453), .B0 (n_2457), .Y
       (n_2458));
  CLKINVX6LVT fopt186(.A (n_2456), .Y (n_2457));
  CLKINVX8LVT fopt187(.A (n_2455), .Y (n_2456));
  CLKINVX6LVT fopt188(.A (n_682), .Y (n_2455));
  NAND2X8LVT g163(.A (n_2617), .B (n_1980), .Y (n_2475));
  NAND2X4LVT g173(.A (n_2468), .B (n_2469), .Y (n_2470));
  NAND2X6LVT g177(.A (csa_tree_ADD_TC_OP_13_groupi_n_253), .B (n_2455),
       .Y (n_2468));
  NAND2X8LVT g176(.A (n_2453), .B (n_2456), .Y (n_2469));
  AOI21X4LVT g164(.A0 (n_1967), .A1 (n_1969), .B0 (n_2617), .Y
       (n_2478));
  NOR2X8LVT g2540(.A (n_1721), .B (n_2479), .Y (n_2480));
  NOR2X4LVT g2541(.A (n_1715), .B (n_1722), .Y (n_2479));
  CLKINVX12LVT g2543(.A (\shift_reg[3] [5]), .Y (n_2483));
  ADDFX1LVT g65(.A (\shift_reg[2] [5]), .B (n_1337), .CI
       (csa_tree_ADD_TC_OP_13_groupi_n_65), .CO (n_2485), .S (n_2486));
  NAND2X8LVT g2549(.A (n_1275), .B (n_2445), .Y (n_2489));
  NOR2X8LVT g82(.A (csa_tree_ADD_TC_OP_13_groupi_n_10), .B (n_2494), .Y
       (n_2495));
  NOR2X8LVT g2551(.A (n_2489), .B (n_2554), .Y (n_2494));
  CLKINVX8LVT g2552(.A (n_2494), .Y (n_2496));
  AOI21X4LVT g2553(.A0 (n_1799), .A1 (n_2502), .B0 (n_2505), .Y
       (n_2506));
  NOR2X4LVT g2554(.A (n_2501), .B (n_2444), .Y (n_2502));
  NAND2X2LVT g2555(.A (n_2499), .B (n_2500), .Y (n_2501));
  NAND2X4LVT g2556(.A (n_2497), .B (n_2498), .Y (n_2499));
  NAND2X4LVT g2557(.A (csa_tree_ADD_TC_OP_13_groupi_n_388), .B
       (n_1399), .Y (n_2497));
  OR2X6LVT g121(.A (csa_tree_ADD_TC_OP_13_groupi_n_388), .B (n_1399),
       .Y (n_2498));
  NAND2X4LVT g2558(.A (n_2841), .B (n_2842), .Y (n_2500));
  NOR2X4LVT g2559(.A (n_2503), .B (n_2504), .Y (n_2505));
  INVX3LVT g2560(.A (n_2499), .Y (n_2503));
  BUFX6LVT g2561(.A (n_1430), .Y (n_2504));
  NAND2X6LVT g2562(.A (n_2503), .B (n_2504), .Y (n_2507));
  NOR2X2LVT g2563(.A (n_2503), .B (n_1218), .Y (n_2508));
  NOR2X8LVT g2564(.A (n_2509), .B (n_2444), .Y (n_2510));
  INVX2LVT g2565(.A (n_2500), .Y (n_2509));
  OAI21X4LVT g2566(.A0 (n_2511), .A1 (n_1379), .B0 (n_2512), .Y
       (n_2513));
  INVX2LVT g2567(.A (n_2498), .Y (n_2511));
  NOR2BX2LVT g2568(.AN (n_2497), .B (n_1451), .Y (n_2512));
  OAI21X4LVT g2569(.A0 (n_2511), .A1 (n_1379), .B0 (n_2497), .Y
       (n_2514));
  CLKINVX6LVT fopt2573(.A (n_2522), .Y (n_2521));
  CLKINVX12LVT fopt2575(.A (data_in_reg[5]), .Y (n_2522));
  CLKINVX6LVT fopt2577(.A (n_2640), .Y (n_2529));
  BUFX3LVT fopt2578(.A (\shift_reg[4] [2]), .Y (n_2531));
  INVX1LVT fopt2579(.A (n_2534), .Y (n_2533));
  CLKINVX6LVT fopt2581(.A (n_1949), .Y (n_2536));
  NOR2X8LVT g2583(.A (n_2454), .B (n_2458), .Y (n_2539));
  NOR2X4LVT g2584(.A (n_2540), .B (n_1981), .Y (n_2541));
  CLKINVX6LVT g2585(.A (n_2539), .Y (n_2540));
  BUFX2 g2587(.A (n_2540), .Y (n_2542));
  OAI22X4LVT g2588(.A0 (n_2480), .A1 (n_2540), .B0 (n_2539), .B1
       (n_2837), .Y (n_2544));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_003_1__2593(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_52), .B (\shift_reg[0] [2]), .CI
       (\shift_reg[5] [2]), .CO (n_2550), .S (n_2551));
  NOR2X8LVT g2(.A (n_2553), .B (n_2442), .Y (n_2554));
  OAI2BB1X4LVT g2595(.A0N (n_1246), .A1N (n_1915), .B0 (n_2448), .Y
       (n_2553));
  NAND2X8LVT g2596(.A (n_2555), .B (n_2297), .Y (n_1566));
  OAI2BB1X4LVT g2597(.A0N (n_2475), .A1N (n_2291), .B0 (n_2542), .Y
       (n_2555));
  ADDFHX2LVT g428(.A (n_2622), .B (n_2571), .CI (n_2572), .CO (n_2573),
       .S (n_2574));
  BUFX6LVT g2598(.A (n_3072), .Y (n_2566));
  BUFX6LVT g2599(.A (n_2671), .Y (n_2567));
  ADDFHX2LVT g430(.A (csa_tree_ADD_TC_OP_13_groupi_n_89), .B (n_800),
       .CI (n_3018), .CO (n_2571), .S (n_2575));
  ADDFHX1LVT g429(.A (csa_tree_ADD_TC_OP_13_groupi_n_83), .B (n_797),
       .CI (n_2623), .CO (n_2578), .S (n_2572));
  XNOR2X1LVT g432(.A (n_2619), .B (n_2576), .Y (n_2577));
  CLKXOR2X1LVT g433(.A (n_2566), .B (n_2567), .Y (n_2576));
  ADDFX1LVT g2601(.A (\shift_reg[4] [1]), .B (n_2580), .CI
       (data_in_reg[3]), .CO (n_2581), .S (n_2582));
  OAI21X4LVT g2603(.A0 (csa_tree_ADD_TC_OP_13_groupi_n_354), .A1
       (n_2588), .B0 (n_2589), .Y (n_2590));
  NOR2X6LVT g2605(.A (n_1700), .B (n_2587), .Y (n_2588));
  CLKINVX6LVT g2606(.A (n_2586), .Y (n_2587));
  OAI2BB1X4LVT g2607(.A0N (\shift_reg[4] [0]), .A1N (n_522), .B0
       (n_2585), .Y (n_2586));
  OAI21X4LVT g2609(.A0 (\shift_reg[4] [0]), .A1 (n_522), .B0
       (csa_tree_ADD_TC_OP_13_groupi_n_361), .Y (n_2585));
  NAND2X4LVT g2610(.A (n_1700), .B (n_2587), .Y (n_2589));
  XOR3X1LVT g2611(.A (\shift_reg[4] [0]), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_361), .C (n_522), .Y (n_2591));
  NOR2X8LVT g71(.A (n_2606), .B (n_2609), .Y (n_2610));
  NOR2BX4LVT g2618(.AN (n_1247), .B (n_2605), .Y (n_2606));
  NOR2X8LVT g2619(.A (n_2601), .B (n_2604), .Y (n_2605));
  NOR2X4LVT g78(.A (n_2600), .B (n_1841), .Y (n_2601));
  CLKINVX4LVT fopt81(.A (n_2194), .Y (n_2600));
  NOR2X8LVT g2620(.A (n_2602), .B (n_2603), .Y (n_2604));
  CLKINVX6LVT fopt2621(.A (n_2600), .Y (n_2602));
  CLKINVX6LVT g2622(.A (n_1841), .Y (n_2603));
  NOR2X6LVT g2623(.A (n_2607), .B (n_2608), .Y (n_2609));
  BUFX2LVT fopt82(.A (n_1247), .Y (n_2607));
  CLKINVX4LVT g74(.A (n_2605), .Y (n_2608));
  NAND2X8LVT g2624(.A (n_2615), .B (n_3067), .Y (n_2617));
  NAND2X6LVT g21(.A (n_2452), .B (n_2470), .Y (n_2615));
  OAI21X4LVT g2627(.A0 (n_2619), .A1 (n_2620), .B0 (n_2621), .Y
       (n_2622));
  INVX3LVT g2628(.A (n_2618), .Y (n_2619));
  ADDFHX2LVT g2629(.A (csa_tree_ADD_TC_OP_13_groupi_n_14), .B (n_2549),
       .CI (csa_tree_ADD_TC_OP_13_groupi_n_72), .CO (n_2623), .S
       (n_2618));
  NOR2X6LVT g2630(.A (n_2566), .B (n_2567), .Y (n_2620));
  NAND2X6LVT g2631(.A (n_2566), .B (n_2567), .Y (n_2621));
  ADDFHX4LVT g346(.A (n_3058), .B (n_622), .CI (n_2635), .CO (n_2636),
       .S (n_2637));
  XOR3X1LVT g347(.A (csa_tree_ADD_TC_OP_13_groupi_n_242), .B (n_2634),
       .C (n_1893), .Y (n_2635));
  ADDFHX2LVT g351(.A (n_544), .B (n_1824), .CI (n_3075), .CO (n_2638),
       .S (n_2634));
  ADDFHX2LVT g348(.A (n_2577), .B (n_2026), .CI (n_2638), .CO (n_2639),
       .S (n_2640));
  AOI21X4LVT g349(.A0 (n_1346), .A1 (n_1895), .B0 (n_2641), .Y
       (n_2642));
  INVX1LVT g350(.A (n_2634), .Y (n_2641));
  NAND2X8LVT g2643(.A (n_2643), .B (n_2294), .Y (n_2644));
  OAI21X4LVT g2644(.A0 (n_2090), .A1 (n_2088), .B0 (n_2292), .Y
       (n_2643));
  NOR2X8LVT g2645(.A (n_2644), .B (n_2421), .Y (n_2646));
  NOR2X6LVT g2646(.A (n_2644), .B (n_2421), .Y (n_2647));
  INVX1LVT fopt2647(.A (n_2649), .Y (n_2648));
  CLKINVX8LVT fopt2653(.A (\shift_reg[2] [3]), .Y (n_2656));
  CLKINVX6LVT fopt2654(.A (n_2657), .Y (n_2658));
  BUFX4LVT fopt2655(.A (n_2656), .Y (n_2657));
  INVX1LVT fopt2656(.A (n_2659), .Y (n_2660));
  BUFX2LVT g2657(.A (n_2657), .Y (n_2659));
  NOR3X6LVT g2658(.A (n_2662), .B (n_1337), .C (n_2521), .Y (n_2663));
  BUFX3LVT g2659(.A (n_3071), .Y (n_2662));
  NOR3X2LVT g2661(.A (n_2522), .B (n_3071), .C (n_2483), .Y (n_2664));
  CLKINVX6LVT fopt2663(.A (n_3071), .Y (n_2667));
  OAI21X4LVT g2664(.A0 (n_3071), .A1 (n_2368), .B0 (n_1503), .Y
       (n_2668));
  INVX3LVT fopt2665(.A (n_2397), .Y (n_2669));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_006_3__2666(.A
       (\shift_reg[1] [4]), .B (\shift_reg[5] [5]), .CI
       (\shift_reg[4] [2]), .CO (n_2670), .S (n_2671));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_008_1__2667(.A
       (\shift_reg[4] [4]), .B (\shift_reg[1] [6]), .CI
       (\shift_reg[1] [4]), .CO (n_2672), .S (n_2673));
  NAND2X8LVT g2701(.A (n_2729), .B (n_3056), .Y (n_2730));
  NAND2X4LVT g2702(.A (n_1924), .B (n_2920), .Y (n_2729));
  NAND2X8LVT g2705(.A (n_2733), .B (n_2734), .Y (n_2735));
  NAND2X4LVT g2706(.A (n_2282), .B (n_2305), .Y (n_2733));
  NAND2X6LVT g2707(.A (n_2306), .B (n_3079), .Y (n_2734));
  OAI22X4LVT g2711(.A0 (n_3054), .A1 (n_3053), .B0 (n_2742), .B1
       (n_2741), .Y (n_2743));
  CLKINVX4LVT g2714(.A (n_3053), .Y (n_2741));
  INVX3LVT g2715(.A (n_3054), .Y (n_2742));
  NOR3X8LVT g2716(.A (n_2744), .B (n_2745), .C (n_2746), .Y (n_2747));
  CLKINVX4LVT g2717(.A (n_2379), .Y (n_2744));
  CLKINVX8LVT g2718(.A (n_1952), .Y (n_2745));
  NOR2X8LVT g2719(.A (n_2803), .B (n_3084), .Y (n_2746));
  NOR2X6LVT g2720(.A (n_2748), .B (n_2749), .Y (n_2750));
  NAND2X4LVT g2721(.A (n_2617), .B (n_1967), .Y (n_2748));
  INVX3LVT g2722(.A (n_1969), .Y (n_2749));
  NOR2X8LVT g2744(.A (n_2773), .B (n_2774), .Y (n_2775));
  CLKINVX4LVT g2745(.A (n_2610), .Y (n_2773));
  NOR2X6LVT g2746(.A (n_2428), .B (n_2429), .Y (n_2774));
  NAND2X6LVT g2752(.A (n_2782), .B (n_2783), .Y (n_2784));
  NAND2X6LVT g42(.A (n_1436), .B (n_1794), .Y (n_2782));
  AOI21X4LVT g2753(.A0 (n_1799), .A1 (n_2510), .B0 (n_2507), .Y
       (n_2783));
  CLKAND2X6LVT g2756(.A (n_1799), .B (n_1034), .Y (n_2785));
  CLKINVX4LVT g2757(.A (n_1958), .Y (n_2786));
  CLKINVX6LVT fopt2768(.A (n_2804), .Y (n_2803));
  CLKINVX8LVT fopt2769(.A (n_2639), .Y (n_2804));
  BUFX3LVT fopt2799(.A (n_2837), .Y (n_2839));
  CLKINVX6LVT fopt2800(.A (n_2480), .Y (n_2837));
  NAND2X6LVT g2801(.A (n_2841), .B (n_2842), .Y (n_2843));
  CLKINVX8LVT g11(.A (n_1566), .Y (n_2841));
  CLKINVX8LVT g10(.A (n_1400), .Y (n_2842));
  NOR3X8LVT g43(.A (n_2847), .B (n_2849), .C (n_2848), .Y (n_2850));
  OAI22X4LVT g2804(.A0 (n_2874), .A1 (n_1581), .B0 (n_2841), .B1
       (n_1583), .Y (n_2847));
  CLKINVX8LVT g2805(.A (n_1695), .Y (n_2848));
  CLKINVX8LVT g2806(.A (n_689), .Y (n_2849));
  NAND2X8LVT g2811(.A (n_2248), .B (n_2249), .Y (n_2855));
  AOI2BB1X4LVT g2812(.A0N (csa_tree_ADD_TC_OP_13_groupi_n_139), .A1N
       (n_2442), .B0 (n_2857), .Y (n_2858));
  CLKAND2X3LVT csa_tree_ADD_TC_OP_13_groupi_g1119__7410_dup2813(.A
       (n_2856), .B (n_2855), .Y (n_2857));
  BUFX2LVT g2814(.A (n_1954), .Y (n_2856));
  NOR2X4LVT csa_tree_ADD_TC_OP_13_groupi_g1099__2815(.A (n_2857), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_139), .Y (n_2859));
  NAND3X6LVT g128(.A (n_2861), .B (n_2862), .C (n_2863), .Y (n_2864));
  NAND2X8LVT g2817(.A (n_2860), .B (n_2785), .Y (n_2861));
  BUFX6LVT g2818(.A (n_1376), .Y (n_2860));
  NAND2X8LVT g2819(.A (n_2850), .B (n_1806), .Y (n_2862));
  NAND2X8LVT g130(.A (n_2860), .B (n_2786), .Y (n_2863));
  CLKINVX8LVT g3(.A (n_2841), .Y (n_2874));
  ADDFX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_010_0__2852(.A
       (\shift_reg[6] [7]), .B (\shift_reg[3] [7]), .CI (n_2900), .CO
       (n_2902), .S (n_2901));
  ADDFHX1LVT g2854(.A (csa_tree_ADD_TC_OP_13_groupi_n_261), .B
       (n_2902), .CI (n_2046), .CO (n_2903), .S (n_2904));
  NAND2X8LVT g2867(.A (n_2918), .B (n_2919), .Y (n_2920));
  NAND2X4LVT g2868(.A (n_1921), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_312), .Y (n_2918));
  NAND2X8LVT g2869(.A (n_1922), .B (n_1934), .Y (n_2919));
  NOR2X8LVT g19(.A (n_2926), .B (n_2928), .Y (n_2929));
  CLKINVX4LVT g2875(.A (n_1676), .Y (n_2926));
  NAND2X6LVT g2876(.A (n_2927), .B (n_2388), .Y (n_2928));
  CLKINVX4LVT g2877(.A (n_2208), .Y (n_2927));
  OAI21X4LVT g2885(.A0 (n_2939), .A1 (n_2940), .B0 (n_2942), .Y
       (n_2943));
  OAI21X2LVT g2886(.A0 (csa_tree_ADD_TC_OP_13_groupi_n_105), .A1
       (n_1548), .B0 (n_1863), .Y (n_2939));
  OR2X6LVT g2888(.A (n_2333), .B (n_2337), .Y (n_2940));
  NAND2X4LVT g2889(.A (n_2941), .B (n_2940), .Y (n_2942));
  OAI21X4LVT g2890(.A0 (csa_tree_ADD_TC_OP_13_groupi_n_105), .A1
       (n_1548), .B0 (n_1863), .Y (n_2941));
  NOR2X6LVT g92(.A (n_3006), .B (n_3007), .Y (n_3008));
  NOR2X4LVT g94(.A (n_2169), .B (n_2182), .Y (n_3006));
  NOR3X6LVT g93(.A (n_2179), .B (n_2184), .C (n_2181), .Y (n_3007));
  XNOR3X1LVT g2943(.A (\shift_reg[1] [5]), .B (n_3013), .C
       (csa_tree_ADD_TC_OP_13_groupi_n_54), .Y (n_3014));
  BUFX6LVT fopt2944(.A (data_in_reg[6]), .Y (n_3013));
  NAND2BX4LVT g2945(.AN (n_3013), .B (\shift_reg[1] [5]), .Y (n_3015));
  CLKAND2X2LVT g2946(.A (data_in_reg[6]), .B (n_2257), .Y (n_3016));
  ADDFHX1LVT g2947(.A (\shift_reg[1] [2]), .B (data_in_reg[6]), .CI
       (n_3081), .CO (n_3017), .S (n_3018));
  NOR2X8LVT g2961(.A (n_1241), .B (n_1942), .Y (n_3043));
  NOR2X8LVT g2962(.A (n_2004), .B (n_3043), .Y (n_3044));
  DFFX2LVT \shift_reg_reg[5][2] (.CK (i_clock), .D (n_2531), .Q
       (\shift_reg[5] [2]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_72));
  DFFX4LVT \shift_reg_reg[1][7] (.CK (i_clock), .D (n_1555), .Q
       (\shift_reg[1] [7]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_65));
  DFFX4LVT \data_in_reg_reg[1] (.CK (i_clock), .D (i_data[1]), .Q
       (data_in_reg[1]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_64));
  DFFX4LVT \data_in_reg_reg[7] (.CK (i_clock), .D (i_data[7]), .Q
       (data_in_reg[7]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_63));
  DFFX4LVT \shift_reg_reg[2][7] (.CK (i_clock), .D (\shift_reg[1] [7]),
       .Q (\shift_reg[2] [7]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_61));
  DFFX1LVT \shift_reg_reg[6][1] (.CK (i_clock), .D (\shift_reg[5] [1]),
       .Q (\shift_reg[6] [1]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_58));
  DFFX4LVT \shift_reg_reg[4][7] (.CK (i_clock), .D (\shift_reg[3] [7]),
       .Q (\shift_reg[4] [7]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_54));
  DFFX4LVT \shift_reg_reg[3][0] (.CK (i_clock), .D (n_3077), .Q
       (\shift_reg[3] [0]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_52));
  DFFX4LVT \shift_reg_reg[6][2] (.CK (i_clock), .D (\shift_reg[5] [2]),
       .Q (\shift_reg[6] [2]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_51));
  DFFX2LVT \shift_reg_reg[3][7] (.CK (i_clock), .D (\shift_reg[2] [7]),
       .Q (\shift_reg[3] [7]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_48));
  DFFX4LVT \shift_reg_reg[5][4] (.CK (i_clock), .D (\shift_reg[4] [4]),
       .Q (\shift_reg[5] [4]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_47));
  DFFX2LVT \shift_reg_reg[0][1] (.CK (i_clock), .D (data_in_reg[1]), .Q
       (\shift_reg[0] [1]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_45));
  DFFX4LVT \shift_reg_reg[3][4] (.CK (i_clock), .D (n_1681), .Q
       (\shift_reg[3] [4]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_29));
  DFFX4LVT \shift_reg_reg[2][1] (.CK (i_clock), .D (\shift_reg[1] [1]),
       .Q (\shift_reg[2] [1]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_24));
  DFFX4LVT \shift_reg_reg[5][0] (.CK (i_clock), .D (\shift_reg[4] [0]),
       .Q (\shift_reg[5] [0]), .QN (csa_tree_ADD_TC_OP_13_groupi_n_17));
  DFFX4LVT \shift_reg_reg[4][3] (.CK (i_clock), .D (n_3082), .Q
       (\shift_reg[4] [3]), .QN (n_922));
  DFFX4LVT \shift_reg_reg[1][1] (.CK (i_clock), .D (\shift_reg[0] [1]),
       .Q (\shift_reg[1] [1]), .QN (n_923));
  DFFX4LVT \shift_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1] [2]),
       .Q (\shift_reg[2] [2]), .QN (n_986));
  DFFX4LVT \shift_reg_reg[4][1] (.CK (i_clock), .D (\shift_reg[3] [1]),
       .Q (\shift_reg[4] [1]), .QN (n_1204));
  DFFX4LVT \shift_reg_reg[6][6] (.CK (i_clock), .D (\shift_reg[5] [6]),
       .Q (\shift_reg[6] [6]), .QN (n_1506));
  DFFX4LVT \shift_reg_reg[3][6] (.CK (i_clock), .D (\shift_reg[2] [6]),
       .Q (\shift_reg[3] [6]), .QN (n_1580));
  DFFX4LVT \shift_reg_reg[2][4] (.CK (i_clock), .D (\shift_reg[1] [4]),
       .Q (\shift_reg[2] [4]), .QN (n_1682));
  DFFX4LVT \shift_reg_reg[0][6] (.CK (i_clock), .D (data_in_reg[6]), .Q
       (\shift_reg[0] [6]), .QN (n_2043));
  DFFX4LVT \data_in_reg_reg[4] (.CK (i_clock), .D (i_data[4]), .Q
       (data_in_reg[4]), .QN (n_2094));
  DFFX4LVT \data_in_reg_reg[2] (.CK (i_clock), .D (i_data[2]), .Q
       (data_in_reg[2]), .QN (n_2246));
  DFFX4LVT \shift_reg_reg[1][5] (.CK (i_clock), .D (\shift_reg[0] [5]),
       .Q (\shift_reg[1] [5]), .QN (n_2257));
  DFFX4LVT \shift_reg_reg[2][6] (.CK (i_clock), .D (\shift_reg[1] [6]),
       .Q (\shift_reg[2] [6]), .QN (n_2259));
  DFFX2LVT \shift_reg_reg[0][5] (.CK (i_clock), .D (n_2521), .Q
       (\shift_reg[0] [5]), .QN (n_2261));
  DFFX4LVT \shift_reg_reg[0][0] (.CK (i_clock), .D (data_in_reg[0]), .Q
       (\shift_reg[0] [0]), .QN (n_2534));
  DFFX4LVT \data_in_reg_reg[3] (.CK (i_clock), .D (i_data[3]), .Q
       (data_in_reg[3]), .QN (n_2545));
  DFFX2LVT \shift_reg_reg[0][2] (.CK (i_clock), .D (data_in_reg[2]), .Q
       (\shift_reg[0] [2]), .QN (n_2549));
  DFFX1LVT \data_in_reg_reg[0] (.CK (i_clock), .D (i_data[0]), .Q
       (data_in_reg[0]), .QN (n_2580));
  DFFX4LVT \shift_reg_reg[5][5] (.CK (i_clock), .D (\shift_reg[4] [5]),
       .Q (\shift_reg[5] [5]), .QN (n_2649));
  DFFX4LVT \shift_reg_reg[5][6] (.CK (i_clock), .D (n_1148), .Q
       (\shift_reg[5] [6]), .QN (n_2900));
  CLKAND2X2LVT g3035(.A (n_1928), .B (n_1277), .Y (n_3049));
  AND2X6LVT g3038(.A (n_2644), .B (n_2421), .Y (n_3052));
  OR2X4LVT g3039(.A (n_2489), .B (n_2554), .Y (n_3053));
  OR2X6LVT g3040(.A (csa_tree_ADD_TC_OP_13_groupi_n_10), .B (n_1534),
       .Y (n_3054));
  XNOR2X1LVT g3041(.A (n_1548), .B (n_1100), .Y (n_3055));
  OR2X6LVT g3042(.A (n_1924), .B (n_2920), .Y (n_3056));
  AO21X1LVT g3044(.A0 (n_1697), .A1 (n_1829), .B0 (n_1830), .Y
       (n_3058));
  AO21X2LVT g3045(.A0 (n_1755), .A1 (n_1717), .B0 (n_1758), .Y
       (n_3059));
  ADDFHX2LVT g3047(.A (n_3082), .B (n_2261), .CI (n_2259), .CO
       (n_3061), .S (UNCONNECTED));
  AOI21X4LVT g3048(.A0 (\shift_reg[3] [1]), .A1 (n_2106), .B0 (n_1493),
       .Y (n_3062));
  AOI2BB1X4LVT g3050(.A0N (\shift_reg[0] [6]), .A1N (data_in_reg[4]),
       .B0 (n_2096), .Y (n_3064));
  AOI2BB1X4LVT g3051(.A0N (n_1882), .A1N (n_1365), .B0 (n_2529), .Y
       (n_3065));
  NAND3BX4LVT g3053(.AN (n_2452), .B (n_2468), .C (n_2469), .Y
       (n_3067));
  ADDFHX2LVT g3054(.A (\shift_reg[2] [1]), .B (\shift_reg[4] [5]), .CI
       (n_1682), .CO (n_3069), .S (n_3068));
  ADDFHX1LVT g3055(.A (\shift_reg[2] [1]), .B (\shift_reg[4] [5]), .CI
       (n_1682), .CO (UNCONNECTED0), .S (n_3070));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_005_3__3056(.A
       (\shift_reg[0] [4]), .B (csa_tree_ADD_TC_OP_13_groupi_n_45), .CI
       (n_3071), .CO (n_3072), .S (n_3073));
  CLKINVX12LVT fopt3057(.A (\shift_reg[3] [2]), .Y (n_3071));
  ADDFHX1LVT csa_tree_ADD_TC_OP_13_groupi_cdnfadd_005_5__3058(.A
       (csa_tree_ADD_TC_OP_13_groupi_n_348), .B
       (csa_tree_ADD_TC_OP_13_groupi_n_353), .CI (n_3073), .CO
       (n_3074), .S (n_3075));
  INVX2LVT fopt(.A (n_3077), .Y (n_3076));
  BUFX2LVT fopt3059(.A (\shift_reg[2] [0]), .Y (n_3077));
  CLKINVX6LVT fopt3060(.A (n_2282), .Y (n_3079));
  INVX3LVT fopt3061(.A (\shift_reg[3] [3]), .Y (n_3081));
  BUFX2LVT fopt3062(.A (\shift_reg[3] [3]), .Y (n_3082));
  CLKINVX6LVT fopt3063(.A (n_3085), .Y (n_3084));
  CLKINVX12LVT fopt3064(.A (n_3087), .Y (n_3085));
  CLKINVX8LVT fopt2(.A (csa_tree_ADD_TC_OP_13_groupi_n_202), .Y
       (n_3087));
endmodule

