
//input ports
add mapped point i_data[7] i_data[7] -type PI PI
add mapped point i_data[6] i_data[6] -type PI PI
add mapped point i_data[5] i_data[5] -type PI PI
add mapped point i_data[4] i_data[4] -type PI PI
add mapped point i_data[3] i_data[3] -type PI PI
add mapped point i_data[2] i_data[2] -type PI PI
add mapped point i_data[1] i_data[1] -type PI PI
add mapped point i_data[0] i_data[0] -type PI PI
add mapped point i_reset i_reset -type PI PI
add mapped point i_clock i_clock -type PI PI

//output ports
add mapped point o_data[18] o_data[18] -type PO PO
add mapped point o_data[17] o_data[17] -type PO PO
add mapped point o_data[16] o_data[16] -type PO PO
add mapped point o_data[15] o_data[15] -type PO PO
add mapped point o_data[14] o_data[14] -type PO PO
add mapped point o_data[13] o_data[13] -type PO PO
add mapped point o_data[12] o_data[12] -type PO PO
add mapped point o_data[11] o_data[11] -type PO PO
add mapped point o_data[10] o_data[10] -type PO PO
add mapped point o_data[9] o_data[9] -type PO PO
add mapped point o_data[8] o_data[8] -type PO PO
add mapped point o_data[7] o_data[7] -type PO PO
add mapped point o_data[6] o_data[6] -type PO PO
add mapped point o_data[5] o_data[5] -type PO PO
add mapped point o_data[4] o_data[4] -type PO PO
add mapped point o_data[3] o_data[3] -type PO PO
add mapped point o_data[2] o_data[2] -type PO PO
add mapped point o_data[1] o_data[1] -type PO PO
add mapped point o_data[0] o_data[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point in_blk[0][0]/q in_blk_reg[0][0]/Q -type DFF DFF
add mapped point in_blk[0][1]/q in_blk_reg[0][1]/Q -type DFF DFF
add mapped point in_blk[0][2]/q in_blk_reg[0][2]/Q -type DFF DFF
add mapped point in_blk[0][3]/q in_blk_reg[0][3]/Q -type DFF DFF
add mapped point in_blk[0][4]/q in_blk_reg[0][4]/Q -type DFF DFF
add mapped point in_blk[0][5]/q in_blk_reg[0][5]/Q -type DFF DFF
add mapped point in_blk[0][6]/q in_blk_reg[0][6]/Q -type DFF DFF
add mapped point in_blk[0][7]/q in_blk_reg[0][7]/Q -type DFF DFF
add mapped point in_blk[1][0]/q in_blk_reg[1][0]/Q -type DFF DFF
add mapped point in_blk[1][1]/q in_blk_reg[1][1]/Q -type DFF DFF
add mapped point in_blk[1][2]/q in_blk_reg[1][2]/Q -type DFF DFF
add mapped point in_blk[1][3]/q in_blk_reg[1][3]/Q -type DFF DFF
add mapped point in_blk[1][4]/q in_blk_reg[1][4]/Q -type DFF DFF
add mapped point in_blk[1][5]/q in_blk_reg[1][5]/Q -type DFF DFF
add mapped point in_blk[1][6]/q in_blk_reg[1][6]/Q -type DFF DFF
add mapped point in_blk[1][7]/q in_blk_reg[1][7]/Q -type DFF DFF
add mapped point in_blk[2][0]/q in_blk_reg[2][0]/Q -type DFF DFF
add mapped point in_blk[2][1]/q in_blk_reg[2][1]/Q -type DFF DFF
add mapped point in_blk[2][2]/q in_blk_reg[2][2]/Q -type DFF DFF
add mapped point in_blk[2][3]/q in_blk_reg[2][3]/Q -type DFF DFF
add mapped point in_blk[2][4]/q in_blk_reg[2][4]/Q -type DFF DFF
add mapped point in_blk[2][5]/q in_blk_reg[2][5]/Q -type DFF DFF
add mapped point in_blk[2][6]/q in_blk_reg[2][6]/Q -type DFF DFF
add mapped point in_blk[2][7]/q in_blk_reg[2][7]/Q -type DFF DFF
add mapped point out_sr[1][0]/q out_sr_reg[1][0]/Q -type DFF DFF
add mapped point out_sr[1][1]/q out_sr_reg[1][1]/Q -type DFF DFF
add mapped point out_sr[1][2]/q out_sr_reg[1][2]/Q -type DFF DFF
add mapped point out_sr[1][3]/q out_sr_reg[1][3]/Q -type DFF DFF
add mapped point out_sr[1][4]/q out_sr_reg[1][4]/Q -type DFF DFF
add mapped point out_sr[1][5]/q out_sr_reg[1][5]/Q -type DFF DFF
add mapped point out_sr[1][6]/q out_sr_reg[1][6]/Q -type DFF DFF
add mapped point out_sr[1][7]/q out_sr_reg[1][7]/Q -type DFF DFF
add mapped point out_sr[1][8]/q out_sr_reg[1][8]/Q -type DFF DFF
add mapped point out_sr[1][9]/q out_sr_reg[1][9]/Q -type DFF DFF
add mapped point out_sr[1][10]/q out_sr_reg[1][10]/Q -type DFF DFF
add mapped point out_sr[1][11]/q out_sr_reg[1][11]/Q -type DFF DFF
add mapped point out_sr[1][12]/q out_sr_reg[1][12]/Q -type DFF DFF
add mapped point out_sr[1][13]/q out_sr_reg[1][13]/Q -type DFF DFF
add mapped point out_sr[1][14]/q out_sr_reg[1][14]/Q -type DFF DFF
add mapped point out_sr[1][15]/q out_sr_reg[1][15]/Q -type DFF DFF
add mapped point out_sr[2][0]/q out_sr_reg[2][0]/Q -type DFF DFF
add mapped point out_sr[2][1]/q out_sr_reg[2][1]/Q -type DFF DFF
add mapped point out_sr[2][2]/q out_sr_reg[2][2]/Q -type DFF DFF
add mapped point out_sr[2][3]/q out_sr_reg[2][3]/Q -type DFF DFF
add mapped point out_sr[2][4]/q out_sr_reg[2][4]/Q -type DFF DFF
add mapped point out_sr[2][5]/q out_sr_reg[2][5]/Q -type DFF DFF
add mapped point out_sr[2][6]/q out_sr_reg[2][6]/Q -type DFF DFF
add mapped point out_sr[2][7]/q out_sr_reg[2][7]/Q -type DFF DFF
add mapped point out_sr[2][8]/q out_sr_reg[2][8]/Q -type DFF DFF
add mapped point out_sr[2][9]/q out_sr_reg[2][9]/Q -type DFF DFF
add mapped point out_sr[2][10]/q out_sr_reg[2][10]/Q -type DFF DFF
add mapped point out_sr[2][11]/q out_sr_reg[2][11]/Q -type DFF DFF
add mapped point out_sr[2][12]/q out_sr_reg[2][12]/Q -type DFF DFF
add mapped point out_sr[2][13]/q out_sr_reg[2][13]/Q -type DFF DFF
add mapped point out_sr[2][14]/q out_sr_reg[2][14]/Q -type DFF DFF
add mapped point out_sr[2][15]/q out_sr_reg[2][15]/Q -type DFF DFF
add mapped point out_sr[3][0]/q out_sr_reg[3][0]/Q -type DFF DFF
add mapped point out_sr[3][1]/q out_sr_reg[3][1]/Q -type DFF DFF
add mapped point out_sr[3][2]/q out_sr_reg[3][2]/Q -type DFF DFF
add mapped point out_sr[3][3]/q out_sr_reg[3][3]/Q -type DFF DFF
add mapped point out_sr[3][4]/q out_sr_reg[3][4]/Q -type DFF DFF
add mapped point out_sr[3][5]/q out_sr_reg[3][5]/Q -type DFF DFF
add mapped point out_sr[3][6]/q out_sr_reg[3][6]/Q -type DFF DFF
add mapped point out_sr[3][7]/q out_sr_reg[3][7]/Q -type DFF DFF
add mapped point out_sr[3][8]/q out_sr_reg[3][8]/Q -type DFF DFF
add mapped point out_sr[3][9]/q out_sr_reg[3][9]/Q -type DFF DFF
add mapped point out_sr[3][10]/q out_sr_reg[3][10]/Q -type DFF DFF
add mapped point out_sr[3][11]/q out_sr_reg[3][11]/Q -type DFF DFF
add mapped point out_sr[3][12]/q out_sr_reg[3][12]/Q -type DFF DFF
add mapped point out_sr[3][13]/q out_sr_reg[3][13]/Q -type DFF DFF
add mapped point out_sr[3][14]/q out_sr_reg[3][14]/Q -type DFF DFF
add mapped point out_sr[3][15]/q out_sr_reg[3][15]/Q -type DFF DFF
add mapped point cnt[1]/q cnt_reg[1]/Q -type DFF DFF
add mapped point cnt[0]/q cnt_reg[0]/Q -type DFF DFF
add mapped point out_sr[0][0]/q out_sr_reg[0][0]/Q -type DFF DFF
add mapped point out_sr[0][1]/q out_sr_reg[0][1]/Q -type DFF DFF
add mapped point out_sr[0][2]/q out_sr_reg[0][2]/Q -type DFF DFF
add mapped point out_sr[0][3]/q out_sr_reg[0][3]/Q -type DFF DFF
add mapped point out_sr[0][4]/q out_sr_reg[0][4]/Q -type DFF DFF
add mapped point out_sr[0][5]/q out_sr_reg[0][5]/Q -type DFF DFF
add mapped point out_sr[0][6]/q out_sr_reg[0][6]/Q -type DFF DFF
add mapped point out_sr[0][7]/q out_sr_reg[0][7]/Q -type DFF DFF
add mapped point out_sr[0][8]/q out_sr_reg[0][8]/Q -type DFF DFF
add mapped point out_sr[0][9]/q out_sr_reg[0][9]/Q -type DFF DFF
add mapped point out_sr[0][10]/q out_sr_reg[0][10]/Q -type DFF DFF
add mapped point out_sr[0][11]/q out_sr_reg[0][11]/Q -type DFF DFF
add mapped point out_sr[0][12]/q out_sr_reg[0][12]/Q -type DFF DFF
add mapped point out_sr[0][13]/q out_sr_reg[0][13]/Q -type DFF DFF
add mapped point out_sr[0][14]/q out_sr_reg[0][14]/Q -type DFF DFF
add mapped point out_sr[0][15]/q out_sr_reg[0][15]/Q -type DFF DFF
add mapped point xs[0][0]/q xs_reg[0][0]/Q -type DFF DFF
add mapped point xs[0][1]/q xs_reg[0][1]/Q -type DFF DFF
add mapped point xs[0][2]/q xs_reg[0][2]/Q -type DFF DFF
add mapped point xs[0][3]/q xs_reg[0][3]/Q -type DFF DFF
add mapped point xs[0][4]/q xs_reg[0][4]/Q -type DFF DFF
add mapped point xs[0][5]/q xs_reg[0][5]/Q -type DFF DFF
add mapped point xs[0][6]/q xs_reg[0][6]/Q -type DFF DFF
add mapped point xs[0][7]/q xs_reg[0][7]/Q -type DFF DFF
add mapped point xs[1][0]/q xs_reg[1][0]/Q -type DFF DFF
add mapped point xs[1][1]/q xs_reg[1][1]/Q -type DFF DFF
add mapped point xs[1][2]/q xs_reg[1][2]/Q -type DFF DFF
add mapped point xs[1][3]/q xs_reg[1][3]/Q -type DFF DFF
add mapped point xs[1][4]/q xs_reg[1][4]/Q -type DFF DFF
add mapped point xs[1][5]/q xs_reg[1][5]/Q -type DFF DFF
add mapped point xs[1][6]/q xs_reg[1][6]/Q -type DFF DFF
add mapped point xs[1][7]/q xs_reg[1][7]/Q -type DFF DFF
add mapped point xs[2][0]/q xs_reg[2][0]/Q -type DFF DFF
add mapped point xs[2][1]/q xs_reg[2][1]/Q -type DFF DFF
add mapped point xs[2][2]/q xs_reg[2][2]/Q -type DFF DFF
add mapped point xs[2][3]/q xs_reg[2][3]/Q -type DFF DFF
add mapped point xs[2][4]/q xs_reg[2][4]/Q -type DFF DFF
add mapped point xs[2][5]/q xs_reg[2][5]/Q -type DFF DFF
add mapped point xs[2][6]/q xs_reg[2][6]/Q -type DFF DFF
add mapped point xs[3][0]/q xs_reg[3][0]/Q -type DFF DFF
add mapped point xs[3][1]/q xs_reg[3][1]/Q -type DFF DFF
add mapped point xs[3][2]/q xs_reg[3][2]/Q -type DFF DFF
add mapped point xs[3][3]/q xs_reg[3][3]/Q -type DFF DFF
add mapped point xs[3][4]/q xs_reg[3][4]/Q -type DFF DFF
add mapped point xs[3][5]/q xs_reg[3][5]/Q -type DFF DFF
add mapped point xs[3][6]/q xs_reg[3][6]/Q -type DFF DFF
add mapped point xs[3][7]/q xs_reg[3][7]/Q -type DFF DFF
add mapped point xs[4][0]/q xs_reg[4][0]/Q -type DFF DFF
add mapped point xs[4][1]/q xs_reg[4][1]/Q -type DFF DFF
add mapped point xs[4][2]/q xs_reg[4][2]/Q -type DFF DFF
add mapped point xs[4][3]/q xs_reg[4][3]/Q -type DFF DFF
add mapped point xs[4][4]/q xs_reg[4][4]/Q -type DFF DFF
add mapped point xs[4][5]/q xs_reg[4][5]/Q -type DFF DFF
add mapped point xs[4][6]/q xs_reg[4][6]/Q -type DFF DFF
add mapped point xs[4][7]/q xs_reg[4][7]/Q -type DFF DFF
add mapped point xs[5][0]/q xs_reg[5][0]/Q -type DFF DFF
add mapped point xs[5][1]/q xs_reg[5][1]/Q -type DFF DFF
add mapped point xs[5][2]/q xs_reg[5][2]/Q -type DFF DFF
add mapped point xs[5][3]/q xs_reg[5][3]/Q -type DFF DFF
add mapped point xs[5][4]/q xs_reg[5][4]/Q -type DFF DFF
add mapped point xs[5][5]/q xs_reg[5][5]/Q -type DFF DFF
add mapped point xs[5][6]/q xs_reg[5][6]/Q -type DFF DFF
add mapped point xs[5][7]/q xs_reg[5][7]/Q -type DFF DFF
add mapped point xs[6][0]/q xs_reg[6][0]/Q -type DFF DFF
add mapped point xs[6][1]/q xs_reg[6][1]/Q -type DFF DFF
add mapped point xs[6][2]/q xs_reg[6][2]/Q -type DFF DFF
add mapped point xs[6][3]/q xs_reg[6][3]/Q -type DFF DFF
add mapped point xs[6][4]/q xs_reg[6][4]/Q -type DFF DFF
add mapped point xs[6][5]/q xs_reg[6][5]/Q -type DFF DFF
add mapped point xs[6][6]/q xs_reg[6][6]/Q -type DFF DFF
add mapped point xs[6][7]/q xs_reg[6][7]/Q -type DFF DFF
add mapped point xs[7][0]/q xs_reg[7][0]/Q -type DFF DFF
add mapped point xs[7][1]/q xs_reg[7][1]/Q -type DFF DFF
add mapped point xs[7][2]/q xs_reg[7][2]/Q -type DFF DFF
add mapped point xs[7][3]/q xs_reg[7][3]/Q -type DFF DFF
add mapped point xs[7][4]/q xs_reg[7][4]/Q -type DFF DFF
add mapped point xs[7][5]/q xs_reg[7][5]/Q -type DFF DFF
add mapped point xs[7][6]/q xs_reg[7][6]/Q -type DFF DFF
add mapped point xs[7][7]/q xs_reg[7][7]/Q -type DFF DFF
add mapped point xs[8][0]/q xs_reg[8][0]/Q -type DFF DFF
add mapped point xs[8][1]/q xs_reg[8][1]/Q -type DFF DFF
add mapped point xs[8][2]/q xs_reg[8][2]/Q -type DFF DFF
add mapped point xs[8][3]/q xs_reg[8][3]/Q -type DFF DFF
add mapped point xs[8][4]/q xs_reg[8][4]/Q -type DFF DFF
add mapped point xs[8][5]/q xs_reg[8][5]/Q -type DFF DFF
add mapped point xs[8][6]/q xs_reg[8][6]/Q -type DFF DFF
add mapped point xs[8][7]/q xs_reg[8][7]/Q -type DFF DFF
add mapped point xs[9][0]/q xs_reg[9][0]/Q -type DFF DFF
add mapped point xs[9][1]/q xs_reg[9][1]/Q -type DFF DFF
add mapped point xs[9][2]/q xs_reg[9][2]/Q -type DFF DFF
add mapped point xs[9][4]/q xs_reg[9][4]/Q -type DFF DFF
add mapped point xs[9][5]/q xs_reg[9][5]/Q -type DFF DFF
add mapped point xs[9][7]/q xs_reg[9][7]/Q -type DFF DFF
add mapped point xs[10][0]/q xs_reg[10][0]/Q -type DFF DFF
add mapped point xs[10][1]/q xs_reg[10][1]/Q -type DFF DFF
add mapped point xs[10][2]/q xs_reg[10][2]/Q -type DFF DFF
add mapped point xs[10][3]/q xs_reg[10][3]/Q -type DFF DFF
add mapped point xs[10][4]/q xs_reg[10][4]/Q -type DFF DFF
add mapped point xs[10][5]/q xs_reg[10][5]/Q -type DFF DFF
add mapped point xs[10][6]/q xs_reg[10][6]/Q -type DFF DFF
add mapped point xs[10][7]/q xs_reg[10][7]/Q -type DFF DFF
add mapped point xs[2][7]/q xs_reg[2][7]/Q -type DFF DFF
add mapped point xs[9][6]/q xs_reg[9][6]/Q -type DFF DFF
add mapped point xs[9][3]/q xs_reg[9][3]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
