
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Sep 30 2026 23:15:31 -03 (Oct  1 2026 02:15:31 UTC)

// Verification Directory fv/practico_3 

module mux3(i_a, i_b, i_c, i_sel, o_ck);
  input i_a, i_b, i_c;
  input [1:0] i_sel;
  output o_ck;
  wire i_a, i_b, i_c;
  wire [1:0] i_sel;
  wire o_ck;
  wire n_0, n_2, n_4, n_15;
  NAND2X1LVT g31__5107(.A (i_sel[0]), .B (i_b), .Y (n_4));
  AO21XLLVT g82__6260(.A0 (i_sel[1]), .A1 (n_15), .B0 (n_2), .Y (o_ck));
  AOI21XLLVT g83__4319(.A0 (n_4), .A1 (n_0), .B0 (i_sel[1]), .Y (n_2));
  NAND2BXLLVT g85__5526(.AN (i_sel[0]), .B (i_a), .Y (n_0));
  MX2X1LVT g2(.A (i_c), .B (i_a), .S0 (i_sel[0]), .Y (n_15));
endmodule

module practico_3(i_ck, i_sel, i_data, o_data);
  input i_ck, i_data;
  input [1:0] i_sel;
  output o_data;
  wire i_ck, i_data;
  wire [1:0] i_sel;
  wire o_data;
  wire n_0, n_1, r_ff1, w_ck_div2, w_ck_div4, w_ck_mux;
  mux3 u_mux(.i_a (i_ck), .i_b (w_ck_div2), .i_c (w_ck_div4), .i_sel
       (i_sel), .o_ck (w_ck_mux));
  DFFHQX1LVT \u_div4_r_count_reg[1] (.CK (i_ck), .D (n_1), .Q
       (w_ck_div4));
  CLKXOR2X1LVT g24__6783(.A (w_ck_div4), .B (w_ck_div2), .Y (n_1));
  DFFHQX1LVT u_div2_r_div_reg(.CK (i_ck), .D (n_0), .Q (w_ck_div2));
  INVX1LVT g26(.A (w_ck_div2), .Y (n_0));
  DFFHQX1LVT r_ff2_reg(.CK (w_ck_mux), .D (r_ff1), .Q (o_data));
  DFFHQX1LVT r_ff1_reg(.CK (w_ck_mux), .D (i_data), .Q (r_ff1));
endmodule

