
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Sep 30 2026 22:28:08 -03 (Oct  1 2026 01:28:08 UTC)

// Verification Directory fv/practico_3 

module practico_3(i_ck, i_sel, i_data, o_data);
  input i_ck, i_data;
  input [1:0] i_sel;
  output o_data;
  wire i_ck, i_data;
  wire [1:0] i_sel;
  wire o_data;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_16, r_ff1;
  wire w_ck_div2, w_ck_div4;
  NAND2X1LVT g40__2398(.A (i_sel[0]), .B (w_ck_div2), .Y (n_7));
  DFFHQX1LVT r_ff2_reg(.CK (n_5), .D (r_ff1), .Q (o_data));
  DFFHQX1LVT r_ff1_reg(.CK (n_5), .D (i_data), .Q (r_ff1));
  AO21X1LVT g95__6260(.A0 (i_sel[1]), .A1 (n_16), .B0 (n_4), .Y (n_5));
  AOI21XLLVT g96__4319(.A0 (n_7), .A1 (n_2), .B0 (i_sel[1]), .Y (n_4));
  NAND2BXLLVT g98__5526(.AN (i_sel[0]), .B (i_ck), .Y (n_2));
  DFFHQX1LVT \u_div4_r_count_reg[1] (.CK (i_ck), .D (n_1), .Q
       (w_ck_div4));
  CLKXOR2X1LVT g51__6783(.A (w_ck_div4), .B (w_ck_div2), .Y (n_1));
  DFFHQX1LVT u_div2_r_div_reg(.CK (i_ck), .D (n_0), .Q (w_ck_div2));
  INVX1LVT g53(.A (w_ck_div2), .Y (n_0));
  MX2X1LVT g2(.A (w_ck_div4), .B (i_ck), .S0 (i_sel[0]), .Y (n_16));
endmodule

