
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Oct  8 2026 21:47:54 -03 (Oct  9 2026 00:47:54 UTC)

// Verification Directory fv/fir_serial_pipe 

module fir_serial_pipe(i_data, i_clock, o_data);
  input [7:0] i_data;
  input i_clock;
  output [18:0] o_data;
  wire [7:0] i_data;
  wire i_clock;
  wire [18:0] o_data;
  wire [7:0] data_in_reg;
  wire [7:0] \shift_reg[0] ;
  wire [15:0] \prod_reg[0] ;
  wire [7:0] \shift_reg[1] ;
  wire [15:0] \prod_reg[1] ;
  wire [7:0] \shift_reg[2] ;
  wire [15:0] \prod_reg[2] ;
  wire [7:0] \shift_reg[3] ;
  wire [15:0] \prod_reg[3] ;
  wire [7:0] \shift_reg[4] ;
  wire [15:0] \prod_reg[4] ;
  wire [7:0] \shift_reg[5] ;
  wire [15:0] \prod_reg[5] ;
  wire [7:0] \shift_reg[6] ;
  wire [15:0] \prod_reg[6] ;
  wire [15:0] \prod_reg[7] ;
  wire [15:0] \prod[2] ;
  wire [15:0] \prod[5] ;
  wire [15:0] \prod[3] ;
  wire [15:0] \prod[4] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5,
       csa_tree_ADD_TC_OP_12_groupi_n_5;
  wire csa_tree_ADD_TC_OP_12_groupi_n_10,
       csa_tree_ADD_TC_OP_12_groupi_n_17,
       csa_tree_ADD_TC_OP_12_groupi_n_28,
       csa_tree_ADD_TC_OP_12_groupi_n_32,
       csa_tree_ADD_TC_OP_12_groupi_n_41,
       csa_tree_ADD_TC_OP_12_groupi_n_47,
       csa_tree_ADD_TC_OP_12_groupi_n_52,
       csa_tree_ADD_TC_OP_12_groupi_n_55;
  wire csa_tree_ADD_TC_OP_12_groupi_n_72,
       csa_tree_ADD_TC_OP_12_groupi_n_73,
       csa_tree_ADD_TC_OP_12_groupi_n_78,
       csa_tree_ADD_TC_OP_12_groupi_n_87,
       csa_tree_ADD_TC_OP_12_groupi_n_89,
       csa_tree_ADD_TC_OP_12_groupi_n_102,
       csa_tree_ADD_TC_OP_12_groupi_n_103,
       csa_tree_ADD_TC_OP_12_groupi_n_104;
  wire csa_tree_ADD_TC_OP_12_groupi_n_113,
       csa_tree_ADD_TC_OP_12_groupi_n_119,
       csa_tree_ADD_TC_OP_12_groupi_n_134,
       csa_tree_ADD_TC_OP_12_groupi_n_156,
       csa_tree_ADD_TC_OP_12_groupi_n_166,
       csa_tree_ADD_TC_OP_12_groupi_n_167,
       csa_tree_ADD_TC_OP_12_groupi_n_168,
       csa_tree_ADD_TC_OP_12_groupi_n_179;
  wire csa_tree_ADD_TC_OP_12_groupi_n_200,
       csa_tree_ADD_TC_OP_12_groupi_n_201,
       csa_tree_ADD_TC_OP_12_groupi_n_204,
       csa_tree_ADD_TC_OP_12_groupi_n_205,
       csa_tree_ADD_TC_OP_12_groupi_n_212,
       csa_tree_ADD_TC_OP_12_groupi_n_213,
       csa_tree_ADD_TC_OP_12_groupi_n_230,
       csa_tree_ADD_TC_OP_12_groupi_n_231;
  wire csa_tree_ADD_TC_OP_12_groupi_n_240,
       csa_tree_ADD_TC_OP_12_groupi_n_253,
       csa_tree_ADD_TC_OP_12_groupi_n_254,
       csa_tree_ADD_TC_OP_12_groupi_n_256,
       csa_tree_ADD_TC_OP_12_groupi_n_269, n_0, n_1, n_2;
  wire n_3, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_61, n_63, n_64, n_65, n_66, n_67, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_95, n_96, n_97;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_110, n_111, n_112, n_113, n_114;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_132, n_133, n_134, n_137, n_138, n_139, n_141, n_142;
  wire n_143, n_144, n_145, n_146, n_147, n_148, n_149, n_151;
  wire n_152, n_153, n_154, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_163, n_164, n_165, n_166, n_167, n_168, n_169;
  wire n_170, n_171, n_172, n_173, n_174, n_175, n_176, n_177;
  wire n_178, n_179, n_180, n_181, n_182, n_183, n_184, n_185;
  wire n_186, n_187, n_188, n_189, n_190, n_191, n_192, n_193;
  wire n_194, n_195, n_196, n_197, n_198, n_199, n_200, n_201;
  wire n_202, n_203, n_204, n_205, n_206, n_207, n_209, n_210;
  wire n_211, n_219, n_220, n_223, n_224, n_227, n_382, n_383;
  wire n_391, n_482, n_484, n_496, n_510, n_511, n_534, n_540;
  wire n_544, n_546, n_547, n_548, n_561, n_567, n_568, n_569;
  wire n_585, n_586, n_587, n_588, n_595, n_597, n_598, n_599;
  wire n_610, n_617, n_618, n_619, n_620, n_621, n_622, n_627;
  wire n_628, n_629, n_631, n_633, n_634, n_635, n_638, n_639;
  wire n_640, n_641, n_644, n_645, n_646, n_647, n_648, n_649;
  wire n_663, n_667, n_668, n_673, n_679, n_691, n_692, n_693;
  wire n_698, n_700, n_721, n_722, n_724, n_725, n_728, n_729;
  wire n_732, n_738, n_744, n_752, n_754, n_755, n_756, n_757;
  wire n_761, n_766, n_767, n_768, n_769, n_770, n_771, n_772;
  wire n_774, n_799, n_800, n_802, n_814, n_815, n_835, n_836;
  wire n_837, n_840, n_852, n_853, n_863, n_868, n_870, n_873;
  wire n_879, n_880, n_881, n_883, n_888, n_890, n_893, n_894;
  wire n_911, n_912, n_913, n_914, n_915, n_918, n_919, n_920;
  wire n_922, n_923, n_925, n_929, n_931, n_935, n_937, n_938;
  wire n_939, n_948, n_981, n_984, n_986, n_988, n_989, n_990;
  wire n_991, n_993, n_1000, n_1003, n_1005, n_1007, n_1008, n_1009;
  wire n_1010, n_1011, n_1014, n_1016, n_1017, n_1018, n_1020, n_1021;
  wire n_1022, n_1027, n_1028, n_1030, n_1037, n_1038, n_1042, n_1046;
  wire n_1058, n_1059, n_1060, n_1061, n_1062, n_1064, n_1066, n_1067;
  wire n_1073, n_1074, n_1075, n_1076, n_1078, n_1079, n_1080, n_1083;
  wire n_1084, n_1092, n_1093, n_1094, n_1095, n_1096, n_1098, n_1099;
  wire n_1100, n_1101, n_1102, n_1104, n_1105, n_1106, n_1107, n_1108;
  wire n_1109, n_1111, n_1112, n_1113, n_1114, n_1115, n_1116, n_1117;
  wire n_1119, n_1120, n_1121, n_1122, n_1123, n_1124, n_1125, n_1126;
  wire n_1130, n_1132, n_1133, n_1134, n_1136, n_1137, n_1138, n_1139;
  wire n_1152, n_1153, n_1154, n_1155, n_1156, n_1158, n_1159, n_1163;
  wire n_1164, n_1165, n_1166, n_1167, n_1168, n_1178, n_1179, n_1208;
  wire n_1212, n_1213, n_1215, n_1217, n_1220, n_1222, n_1223, n_1224;
  wire n_1228, n_1230, n_1231, n_1232, n_1239, n_1243, n_1244, n_1248;
  wire n_1264, n_1265, n_1267, n_1268, n_1272, n_1278, n_1281, n_1282;
  wire n_1283, n_1284, n_1287, n_1288, n_1378, n_1380, n_1381, n_1382;
  wire n_1383, n_1386, n_1388, n_1389, n_1401, n_1417, n_1431, n_1432;
  wire n_1435, n_1438, n_1443, n_1444, n_1446, n_1447, n_1448, n_1449;
  wire n_1451, n_1452, n_1453, n_1455, n_1460, n_1461, n_1462, n_1463;
  wire n_1464, n_1468, n_1471, n_1473, n_1474, n_1475, n_1476, n_1477;
  wire n_1478, n_1481, n_1482, n_1483, n_1484, n_1485, n_1486, n_1491;
  wire n_1492, n_1494, n_1496, n_1499, n_1500, n_1521, n_1522, n_1524;
  wire n_1525, n_1552, n_1553, n_1554, n_1564, n_1565, n_1567, n_1569;
  wire n_1570, n_1573, n_1576, n_1577, n_1578, n_1579, n_1582, n_1583;
  wire n_1584, n_1586, n_1587, n_1591, n_1592, n_1593, n_1594, n_1596;
  wire n_1598, n_1599, n_1602, n_1603, n_1608, n_1610, n_1611, n_1612;
  wire n_1613, n_1614, n_1615, n_1616, n_1617, n_1618, n_1621, n_1622;
  wire n_1626, n_1627, n_1628, n_1630, n_1631, n_1632, n_1633, n_1637;
  wire n_1638, n_1639, n_1640, n_1641, n_1642, n_1643, n_1645, n_1648;
  wire n_1650, n_1652, n_1653, n_1654, n_1655, n_1656, n_1657, n_1659;
  wire n_1660, n_1661, n_1662, n_1666, n_1667, n_1668, n_1669, n_1670;
  wire n_1671, n_1674, n_1675, n_1676, n_1677, n_1678, n_1679, n_1680;
  wire n_1681, n_1686, n_1694, n_1696, n_1697, n_1704, n_1705, n_1706;
  wire n_1707, n_1708, n_1709, n_1711, n_1712, n_1713, n_1714, n_1716;
  wire n_1717, n_1720, n_1721, n_1722, n_1723, n_1724, n_1725, n_1728;
  wire n_1729, n_1730, n_1731, n_1732, n_1733, n_1734, n_1735, n_1736;
  wire n_1737, n_1738, n_1739, n_1740, n_1741, n_1742, n_1743, n_1745;
  wire n_1746, n_1747, n_1749, n_1751, n_1755, n_1795, n_1796, n_1797;
  wire n_1798, n_1801, n_1802, n_1803, n_1804, n_1805, n_1806, n_1807;
  wire n_1808, n_1809, n_1810, n_1811, n_1812, n_1814, n_1832, n_1833;
  wire n_1834, n_1841, n_1842, n_1843, n_1844, n_1857, n_1858, n_1859;
  wire n_1860, n_1861, n_1862, n_1863, n_1865, n_1866, n_1867, n_1868;
  wire n_1869, n_1881, n_1882, n_1883, n_1884, n_1885, n_1886, n_1887;
  wire n_1888, n_1889, n_1890, n_1891, n_1892, n_1894, n_1895, n_1896;
  wire n_1897, n_1898, n_1899, n_1900, n_1901, n_1902, n_1907, n_1908;
  wire n_1909, n_1910, n_1911, n_1912, n_1913, n_1914, n_1915, n_1957;
  wire n_1958, n_1959, n_1960, n_1965, n_1967, n_1968, n_1971, n_1972;
  wire n_1973, n_1974, n_1975, n_1977, n_2023, n_2032, n_2039, n_2040;
  wire n_2046, n_2047, n_2051, n_2052, n_2103;
  assign o_data[15] = o_data[18];
  assign o_data[16] = o_data[18];
  assign o_data[17] = o_data[18];
  DFFQX2LVT \data_in_reg_reg[0] (.CK (i_clock), .D (i_data[0]), .Q
       (data_in_reg[0]));
  DFFQX4LVT \data_in_reg_reg[1] (.CK (i_clock), .D (i_data[1]), .Q
       (data_in_reg[1]));
  DFFHQX1LVT \data_in_reg_reg[2] (.CK (i_clock), .D (i_data[2]), .Q
       (data_in_reg[2]));
  DFFHQX1LVT \data_in_reg_reg[6] (.CK (i_clock), .D (i_data[6]), .Q
       (data_in_reg[6]));
  DFFHQX1LVT \data_in_reg_reg[7] (.CK (i_clock), .D (i_data[7]), .Q
       (data_in_reg[7]));
  DFFHQX1LVT \data_out_reg_reg[0] (.CK (i_clock), .D (n_227), .Q
       (o_data[0]));
  DFFHQX1LVT \data_out_reg_reg[1] (.CK (i_clock), .D (n_649), .Q
       (o_data[1]));
  DFFHQX1LVT \data_out_reg_reg[2] (.CK (i_clock), .D (n_1569), .Q
       (o_data[2]));
  DFFHQX1LVT \data_out_reg_reg[3] (.CK (i_clock), .D (n_224), .Q
       (o_data[3]));
  DFFHQX1LVT \data_out_reg_reg[4] (.CK (i_clock), .D (n_223), .Q
       (o_data[4]));
  DFFHQX1LVT \data_out_reg_reg[5] (.CK (i_clock), .D (n_1910), .Q
       (o_data[5]));
  DFFHQX1LVT \data_out_reg_reg[6] (.CK (i_clock), .D (n_391), .Q
       (o_data[6]));
  DFFHQX1LVT \data_out_reg_reg[7] (.CK (i_clock), .D (n_220), .Q
       (o_data[7]));
  DFFHQX1LVT \data_out_reg_reg[8] (.CK (i_clock), .D (n_219), .Q
       (o_data[8]));
  DFFHQX1LVT \data_out_reg_reg[9] (.CK (i_clock), .D (n_888), .Q
       (o_data[9]));
  DFFHQX1LVT \data_out_reg_reg[10] (.CK (i_clock), .D (n_1272), .Q
       (o_data[10]));
  DFFHQX1LVT \data_out_reg_reg[11] (.CK (i_clock), .D (n_1500), .Q
       (o_data[11]));
  DFFHQX1LVT \data_out_reg_reg[12] (.CK (i_clock), .D (n_1803), .Q
       (o_data[12]));
  DFFHQX1LVT \data_out_reg_reg[13] (.CK (i_clock), .D (n_569), .Q
       (o_data[13]));
  DFFHQX1LVT \data_out_reg_reg[14] (.CK (i_clock), .D (n_1164), .Q
       (o_data[14]));
  DFFHQX1LVT \data_out_reg_reg[15] (.CK (i_clock), .D (n_700), .Q
       (o_data[18]));
  DFFQX4LVT \prod_reg_reg[0][0] (.CK (i_clock), .D (data_in_reg[0]), .Q
       (\shift_reg[0] [0]));
  DFFHQX4LVT \prod_reg_reg[0][4] (.CK (i_clock), .D (n_1), .Q
       (\prod_reg[0] [4]));
  DFFHQX4LVT \prod_reg_reg[0][5] (.CK (i_clock), .D (n_5), .Q
       (\prod_reg[0] [5]));
  DFFHQX4LVT \prod_reg_reg[0][7] (.CK (i_clock), .D (n_149), .Q
       (\prod_reg[0] [7]));
  DFFHQX4LVT \prod_reg_reg[0][8] (.CK (i_clock), .D (n_167), .Q
       (\prod_reg[0] [8]));
  DFFHQX4LVT \prod_reg_reg[0][9] (.CK (i_clock), .D (n_185), .Q
       (\prod_reg[0] [9]));
  DFFQX4LVT \prod_reg_reg[1][1] (.CK (i_clock), .D (\shift_reg[0] [0]),
       .Q (\shift_reg[1] [0]));
  DFFHQX4LVT \prod_reg_reg[1][2] (.CK (i_clock), .D (\shift_reg[0]
       [1]), .Q (\shift_reg[1] [1]));
  DFFHQX8LVT \prod_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [2]), .Q (\shift_reg[1] [2]));
  DFFHQX4LVT \prod_reg_reg[1][4] (.CK (i_clock), .D (n_59), .Q
       (\prod_reg[1] [4]));
  DFFHQX4LVT \prod_reg_reg[1][5] (.CK (i_clock), .D (n_104), .Q
       (\prod_reg[1] [5]));
  DFFHQX4LVT \prod_reg_reg[1][6] (.CK (i_clock), .D (n_130), .Q
       (\prod_reg[1] [6]));
  DFFQX2LVT \prod_reg_reg[1][7] (.CK (i_clock), .D (n_147), .Q
       (\prod_reg[1] [7]));
  DFFHQX4LVT \prod_reg_reg[1][8] (.CK (i_clock), .D (n_158), .Q
       (\prod_reg[1] [8]));
  DFFHQX4LVT \prod_reg_reg[1][9] (.CK (i_clock), .D (n_175), .Q
       (\prod_reg[1] [9]));
  DFFQX2LVT \prod_reg_reg[1][11] (.CK (i_clock), .D (n_180), .Q
       (\prod_reg[1] [11]));
  DFFHQX4LVT \prod_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1]
       [0]), .Q (\shift_reg[2] [0]));
  DFFHQX4LVT \prod_reg_reg[2][4] (.CK (i_clock), .D (n_39), .Q
       (\prod_reg[2] [4]));
  DFFHQX4LVT \prod_reg_reg[2][5] (.CK (i_clock), .D (n_90), .Q
       (\prod_reg[2] [5]));
  DFFHQX4LVT \prod_reg_reg[2][6] (.CK (i_clock), .D (n_128), .Q
       (\prod_reg[2] [6]));
  DFFHQX4LVT \prod_reg_reg[2][7] (.CK (i_clock), .D (n_143), .Q
       (\prod_reg[2] [7]));
  DFFHQX4LVT \prod_reg_reg[2][8] (.CK (i_clock), .D (n_154), .Q
       (\prod_reg[2] [8]));
  DFFHQX4LVT \prod_reg_reg[2][9] (.CK (i_clock), .D (n_174), .Q
       (\prod_reg[2] [9]));
  DFFHQX4LVT \prod_reg_reg[2][10] (.CK (i_clock), .D (n_187), .Q
       (\prod_reg[2] [10]));
  DFFQX2LVT \prod_reg_reg[2][11] (.CK (i_clock), .D (n_186), .Q
       (\prod_reg[2] [11]));
  DFFHQX8LVT \prod_reg_reg[3][3] (.CK (i_clock), .D (n_1627), .Q
       (\shift_reg[3] [0]));
  DFFQX2LVT \prod_reg_reg[3][5] (.CK (i_clock), .D (n_67), .Q
       (\prod_reg[3] [5]));
  DFFHQX4LVT \prod_reg_reg[3][7] (.CK (i_clock), .D (n_6), .Q
       (\prod_reg[3] [7]));
  DFFHQX4LVT \prod_reg_reg[3][8] (.CK (i_clock), .D (n_137), .Q
       (\prod_reg[3] [8]));
  DFFQX2LVT \prod_reg_reg[3][9] (.CK (i_clock), .D (n_1484), .Q
       (\prod_reg[3] [9]));
  DFFHQX4LVT \prod_reg_reg[3][10] (.CK (i_clock), .D (n_172), .Q
       (\prod_reg[3] [10]));
  DFFQX2LVT \prod_reg_reg[3][11] (.CK (i_clock), .D (n_191), .Q
       (\prod_reg[3] [11]));
  DFFQX1LVT \prod_reg_reg[3][12] (.CK (i_clock), .D (n_196), .Q
       (\prod_reg[3] [12]));
  DFFHQX8LVT \prod_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3]
       [0]), .Q (\shift_reg[4] [0]));
  DFFHQX4LVT \prod_reg_reg[4][5] (.CK (i_clock), .D (n_80), .Q
       (\prod_reg[4] [5]));
  DFFHQX4LVT \prod_reg_reg[4][7] (.CK (i_clock), .D (n_7), .Q
       (\prod_reg[4] [7]));
  DFFHQX4LVT \prod_reg_reg[4][8] (.CK (i_clock), .D (n_141), .Q
       (\prod_reg[4] [8]));
  DFFHQX4LVT \prod_reg_reg[4][9] (.CK (i_clock), .D (n_163), .Q
       (\prod_reg[4] [9]));
  DFFHQX4LVT \prod_reg_reg[4][10] (.CK (i_clock), .D (n_178), .Q
       (\prod_reg[4] [10]));
  DFFHQX4LVT \prod_reg_reg[4][11] (.CK (i_clock), .D (n_195), .Q
       (\prod_reg[4] [11]));
  DFFQX1LVT \prod_reg_reg[4][12] (.CK (i_clock), .D (n_200), .Q
       (\prod_reg[4] [12]));
  DFFQX2LVT \prod_reg_reg[5][2] (.CK (i_clock), .D (n_1867), .Q
       (\shift_reg[5] [0]));
  DFFHQX4LVT \prod_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4]
       [1]), .Q (\shift_reg[5] [1]));
  DFFHQX4LVT \prod_reg_reg[5][4] (.CK (i_clock), .D (n_1869), .Q
       (\prod_reg[5] [4]));
  DFFHQX1 \prod_reg_reg[5][6] (.CK (i_clock), .D (n_145), .Q
       (\prod_reg[5] [6]));
  DFFHQX4LVT \prod_reg_reg[5][10] (.CK (i_clock), .D (n_204), .Q
       (\prod_reg[5] [10]));
  DFFQX4LVT \prod_reg_reg[6][1] (.CK (i_clock), .D (n_1626), .Q
       (\shift_reg[6] [0]));
  DFFHQX4LVT \prod_reg_reg[6][2] (.CK (i_clock), .D (n_1452), .Q
       (\shift_reg[6] [1]));
  DFFHQX4LVT \prod_reg_reg[6][4] (.CK (i_clock), .D (n_111), .Q
       (\prod_reg[6] [4]));
  DFFHQX1LVT \prod_reg_reg[6][6] (.CK (i_clock), .D (n_9), .Q
       (\prod_reg[6] [6]));
  DFFQX1 \prod_reg_reg[7][0] (.CK (i_clock), .D (n_1153), .Q
       (\prod_reg[7] [0]));
  DFFQX2LVT \prod_reg_reg[7][1] (.CK (i_clock), .D (n_1628), .Q
       (\prod_reg[7] [1]));
  DFFHQX4LVT \prod_reg_reg[7][2] (.CK (i_clock), .D (n_1011), .Q
       (\prod_reg[7] [2]));
  DFFQX2LVT \prod_reg_reg[7][4] (.CK (i_clock), .D (n_138), .Q
       (\prod_reg[7] [4]));
  DFFHQX4LVT \prod_reg_reg[7][5] (.CK (i_clock), .D (n_10), .Q
       (\prod_reg[7] [5]));
  DFFHQX4LVT \prod_reg_reg[7][6] (.CK (i_clock), .D (n_165), .Q
       (\prod_reg[7] [6]));
  DFFHQX4LVT \prod_reg_reg[7][7] (.CK (i_clock), .D (n_189), .Q
       (\prod_reg[7] [7]));
  DFFHQX4LVT \prod_reg_reg[7][8] (.CK (i_clock), .D (n_202), .Q
       (\prod_reg[7] [8]));
  DFFHQX4LVT \prod_reg_reg[7][9] (.CK (i_clock), .D (n_211), .Q
       (\prod_reg[7] [9]));
  DFFHQX4LVT \prod_reg_reg[7][10] (.CK (i_clock), .D (n_209), .Q
       (\prod_reg[7] [10]));
  DFFHQX1LVT \shift_reg_reg[0][4] (.CK (i_clock), .D (data_in_reg[4]),
       .Q (\shift_reg[0] [4]));
  DFFHQX1LVT \shift_reg_reg[0][5] (.CK (i_clock), .D (data_in_reg[5]),
       .Q (\shift_reg[0] [5]));
  DFFHQX1LVT \shift_reg_reg[0][6] (.CK (i_clock), .D (data_in_reg[6]),
       .Q (\shift_reg[0] [6]));
  DFFHQX1LVT \shift_reg_reg[0][7] (.CK (i_clock), .D (data_in_reg[7]),
       .Q (\shift_reg[0] [7]));
  DFFHQX4LVT \shift_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [3]), .Q (\shift_reg[1] [3]));
  DFFHQX1LVT \shift_reg_reg[1][4] (.CK (i_clock), .D (\shift_reg[0]
       [4]), .Q (\shift_reg[1] [4]));
  DFFHQX1LVT \shift_reg_reg[1][5] (.CK (i_clock), .D (\shift_reg[0]
       [5]), .Q (\shift_reg[1] [5]));
  DFFHQX1LVT \shift_reg_reg[1][6] (.CK (i_clock), .D (\shift_reg[0]
       [6]), .Q (\shift_reg[1] [6]));
  DFFHQX1LVT \shift_reg_reg[1][7] (.CK (i_clock), .D (\shift_reg[0]
       [7]), .Q (\prod[2] [13]));
  DFFHQX1LVT \shift_reg_reg[2][5] (.CK (i_clock), .D (\shift_reg[1]
       [5]), .Q (\shift_reg[2] [5]));
  DFFHQX1LVT \shift_reg_reg[2][6] (.CK (i_clock), .D (\shift_reg[1]
       [6]), .Q (\shift_reg[2] [6]));
  DFFHQX1LVT \shift_reg_reg[3][5] (.CK (i_clock), .D (\shift_reg[2]
       [5]), .Q (\shift_reg[3] [5]));
  DFFHQX1LVT \shift_reg_reg[3][6] (.CK (i_clock), .D (\shift_reg[2]
       [6]), .Q (\shift_reg[3] [6]));
  DFFQX4LVT \shift_reg_reg[4][1] (.CK (i_clock), .D (\shift_reg[3]
       [1]), .Q (\shift_reg[4] [1]));
  DFFQX4LVT \shift_reg_reg[4][2] (.CK (i_clock), .D (\shift_reg[3]
       [2]), .Q (\shift_reg[4] [2]));
  DFFHQX4LVT \shift_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3]
       [3]), .Q (\shift_reg[4] [3]));
  DFFHQX1LVT \shift_reg_reg[4][4] (.CK (i_clock), .D (\shift_reg[3]
       [4]), .Q (\shift_reg[4] [4]));
  DFFHQX1LVT \shift_reg_reg[4][5] (.CK (i_clock), .D (\shift_reg[3]
       [5]), .Q (\shift_reg[4] [5]));
  DFFHQX1LVT \shift_reg_reg[4][6] (.CK (i_clock), .D (\shift_reg[3]
       [6]), .Q (\shift_reg[4] [6]));
  DFFHQX1LVT \shift_reg_reg[5][2] (.CK (i_clock), .D (\shift_reg[4]
       [2]), .Q (\shift_reg[5] [2]));
  DFFHQX1LVT \shift_reg_reg[5][6] (.CK (i_clock), .D (\shift_reg[4]
       [6]), .Q (\shift_reg[5] [6]));
  DFFX1LVT \shift_reg_reg[6][5] (.CK (i_clock), .D (\shift_reg[5] [5]),
       .Q (UNCONNECTED), .QN (\shift_reg[6] [5]));
  DFFHQX1LVT \shift_reg_reg[6][6] (.CK (i_clock), .D (\shift_reg[5]
       [6]), .Q (\shift_reg[6] [6]));
  DFFHQX1LVT \shift_reg_reg[6][7] (.CK (i_clock), .D (n_1165), .Q
       (\shift_reg[6] [7]));
  INVX3LVT g5266(.A (n_210), .Y (n_211));
  ADDFHX1LVT g5267__2398(.A (\shift_reg[6] [6]), .B (n_37), .CI
       (n_205), .CO (n_209), .S (n_210));
  ADDFHX1LVT g5271__5107(.A (\shift_reg[5] [6]), .B (n_15), .CI
       (n_199), .CO (n_206), .S (n_207));
  INVX2LVT g5276(.A (n_201), .Y (n_205));
  ADDFX1LVT g5277__6260(.A (\shift_reg[4] [6]), .B (\prod[5] [13]), .CI
       (n_192), .CO (n_203), .S (n_204));
  ADDFHX1LVT g5278__4319(.A (\shift_reg[6] [7]), .B (\shift_reg[6]
       [5]), .CI (n_188), .CO (n_201), .S (n_202));
  CLKXOR2X1LVT g5281__8428(.A (n_86), .B (n_194), .Y (n_200));
  INVX2LVT g5282(.A (n_197), .Y (n_199));
  ADDFX1LVT g5283__5526(.A (n_1165), .B (n_28), .CI (n_183), .CO
       (n_197), .S (n_198));
  CLKXOR2X1LVT g5285__6783(.A (n_77), .B (n_190), .Y (n_196));
  ADDFHX1LVT g5286__3680(.A (\shift_reg[3] [5]), .B (n_11), .CI
       (n_177), .CO (n_194), .S (n_195));
  ADDFX1LVT g5292__1617(.A (\shift_reg[4] [5]), .B (\prod[5] [13]), .CI
       (n_169), .CO (n_192), .S (n_193));
  ADDFHX2LVT g5293__2802(.A (\shift_reg[2] [5]), .B (n_14), .CI
       (n_171), .CO (n_190), .S (n_191));
  ADDFX2LVT g5294__1705(.A (\shift_reg[6] [7]), .B (n_29), .CI (n_164),
       .CO (n_188), .S (n_189));
  ADDFHX1LVT g5295__5122(.A (\prod[2] [13]), .B (\shift_reg[1] [6]),
       .CI (n_173), .CO (n_186), .S (n_187));
  INVX3LVT g5301(.A (n_182), .Y (n_185));
  ADDFHX1LVT g5302__8246(.A (n_1165), .B (n_993), .CI (n_160), .CO
       (n_183), .S (n_184));
  ADDFHX1LVT g5303__7098(.A (data_in_reg[6]), .B (n_33), .CI (n_168),
       .CO (n_181), .S (n_182));
  AOI21X2LVT g5305__6131(.A0 (n_48), .A1 (n_176), .B0 (\shift_reg[0]
       [7]), .Y (n_180));
  CLKXOR2X1LVT g5306__1881(.A (n_58), .B (n_176), .Y (n_179));
  ADDFHX1LVT g5307__5115(.A (\shift_reg[3] [4]), .B (n_11), .CI
       (n_162), .CO (n_177), .S (n_178));
  ADDFX2LVT g5313__7482(.A (\shift_reg[0] [7]), .B (n_50), .CI (n_157),
       .CO (n_176), .S (n_175));
  ADDFHX1LVT g5314__4733(.A (\prod[2] [13]), .B (\shift_reg[1] [5]),
       .CI (n_153), .CO (n_173), .S (n_174));
  ADDFHX2LVT g5315__6161(.A (\shift_reg[2] [4]), .B (n_14), .CI
       (n_1482), .CO (n_171), .S (n_172));
  ADDFX1LVT g5316__9315(.A (\shift_reg[4] [6]), .B (\shift_reg[4] [4]),
       .CI (n_151), .CO (n_169), .S (n_170));
  INVX2LVT g5319(.A (n_166), .Y (n_168));
  ADDFX1LVT g5320__9945(.A (data_in_reg[7]), .B (n_17), .CI (n_148),
       .CO (n_166), .S (n_167));
  XNOR2X1HVT g5322__2883(.A (n_32), .B (n_124), .Y (n_165));
  OAI21X4LVT g5323__2346(.A0 (n_114), .A1 (n_159), .B0 (n_119), .Y
       (n_164));
  ADDFHX2LVT g5324__1666(.A (\shift_reg[3] [3]), .B (n_73), .CI
       (n_1844), .CO (n_162), .S (n_163));
  XNOR2X1 g5330__7410(.A (n_2103), .B (n_110), .Y (n_161));
  OAI21X4LVT g5331__6417(.A0 (n_96), .A1 (n_1444), .B0 (n_97), .Y
       (n_160));
  CLKINVX4LVT g5333(.A (n_32), .Y (n_159));
  ADDFX1LVT g5334__5477(.A (\shift_reg[0] [7]), .B (n_49), .CI (n_146),
       .CO (n_157), .S (n_158));
  ADDFHX1LVT g5336__5107(.A (\shift_reg[1] [6]), .B (\shift_reg[1]
       [4]), .CI (n_142), .CO (n_153), .S (n_154));
  ADDFX1LVT g5337__6260(.A (\shift_reg[4] [5]), .B (\shift_reg[4] [3]),
       .CI (n_144), .CO (n_151), .S (n_152));
  ADDFHX1LVT g5342__4319(.A (data_in_reg[7]), .B (n_18), .CI (n_132),
       .CO (n_148), .S (n_149));
  OAI21X4LVT g5345__8428(.A0 (n_115), .A1 (n_139), .B0 (n_116), .Y
       (n_32));
  ADDFX1LVT g5354__6783(.A (\shift_reg[0] [6]), .B (n_22), .CI (n_129),
       .CO (n_146), .S (n_147));
  ADDFX1LVT g5355__3680(.A (\shift_reg[4] [2]), .B (\shift_reg[4] [4]),
       .CI (n_107), .CO (n_144), .S (n_145));
  ADDFHX1LVT g5356__1617(.A (\shift_reg[1] [5]), .B (\shift_reg[1]
       [3]), .CI (n_127), .CO (n_142), .S (n_143));
  XNOR2X1HVT g5359__2802(.A (n_126), .B (n_88), .Y (n_141));
  AOI21X4LVT g5363__5122(.A0 (n_112), .A1 (n_117), .B0 (n_118), .Y
       (n_139));
  XNOR2X1LVT g5364__8246(.A (n_112), .B (n_123), .Y (n_138));
  XNOR2X1HVT g5365__7098(.A (n_121), .B (n_76), .Y (n_137));
  XNOR2X1HVT g5374__1881(.A (n_30), .B (n_52), .Y (n_133));
  AOI21X4LVT g5375__5115(.A0 (n_106), .A1 (n_101), .B0 (n_1453), .Y
       (n_134));
  OAI21X4LVT g5376__7482(.A0 (n_45), .A1 (n_125), .B0 (n_46), .Y
       (n_132));
  ADDFHX2LVT g5378__4733(.A (\shift_reg[0] [5]), .B (n_13), .CI
       (n_103), .CO (n_129), .S (n_130));
  ADDFX1LVT g5379__6161(.A (\shift_reg[1] [2]), .B (\shift_reg[1] [4]),
       .CI (n_75), .CO (n_127), .S (n_128));
  OAI21X4LVT g5383__9315(.A0 (n_84), .A1 (n_113), .B0 (n_85), .Y
       (n_126));
  INVX3LVT g5386(.A (n_30), .Y (n_125));
  NAND2BX1LVT g5388__9945(.AN (n_114), .B (n_119), .Y (n_124));
  NAND2BX1LVT g5389__2883(.AN (n_118), .B (n_117), .Y (n_123));
  NAND2BX1LVT g5390__2346(.AN (n_115), .B (n_116), .Y (n_122));
  OAI21X1 g5393__1666(.A0 (n_1153), .A1 (n_105), .B0 (n_112), .Y
       (n_120));
  OAI21X4LVT g5394__7410(.A0 (n_70), .A1 (n_95), .B0 (n_72), .Y
       (n_121));
  NAND2X1LVT g5398__6417(.A (\shift_reg[6] [6]), .B (n_105), .Y
       (n_119));
  NOR2X2LVT g5399__5477(.A (n_1628), .B (n_29), .Y (n_118));
  NAND2X4LVT g5400__2398(.A (n_1628), .B (n_29), .Y (n_117));
  OR2X4LVT g5401__5107(.A (n_1011), .B (\shift_reg[6] [5]), .Y (n_116));
  CLKAND2X2LVT g5402__6260(.A (n_1011), .B (\shift_reg[6] [5]), .Y
       (n_115));
  NOR2X1LVT g5403__4319(.A (\shift_reg[6] [6]), .B (n_105), .Y (n_114));
  OAI21XLLVT g5407__8428(.A0 (n_1626), .A1 (n_93), .B0 (n_106), .Y
       (n_111));
  NAND2BX1LVT g5408__5526(.AN (n_96), .B (n_97), .Y (n_110));
  NAND2BX1LVT g5409__6783(.AN (n_99), .B (n_100), .Y (n_109));
  NOR2BX1LVT g5410__3680(.AN (n_101), .B (n_1453), .Y (n_108));
  OAI21X4LVT g5411__1617(.A0 (n_47), .A1 (n_81), .B0 (n_43), .Y (n_30));
  OAI21X4LVT g5412__2802(.A0 (\shift_reg[3] [0]), .A1 (n_69), .B0
       (n_26), .Y (n_113));
  AOI21X4LVT g5413__1705(.A0 (n_92), .A1 (n_1868), .B0 (n_91), .Y
       (n_107));
  NAND2X6LVT g5414__5122(.A (n_1153), .B (n_105), .Y (n_112));
  ADDFHX1LVT g5417__8246(.A (\shift_reg[0] [4]), .B (n_16), .CI (n_56),
       .CO (n_103), .S (n_104));
  NAND2BX1LVT g5420__7098(.AN (n_91), .B (n_92), .Y (n_102));
  NAND2X6LVT g5424__6131(.A (n_1626), .B (n_93), .Y (n_106));
  NAND2X4LVT g5428__1881(.A (n_1452), .B (n_993), .Y (n_101));
  OR2X2LVT g5429__5115(.A (\shift_reg[5] [2]), .B (n_28), .Y (n_100));
  AND2X2LVT g5430__7482(.A (\shift_reg[5] [2]), .B (n_28), .Y (n_99));
  NAND2X1LVT g5432__6161(.A (\shift_reg[5] [6]), .B (n_93), .Y (n_97));
  NOR2X1LVT g5433__9315(.A (\shift_reg[5] [6]), .B (n_93), .Y (n_96));
  OAI21X4LVT g5434__9945(.A0 (n_1627), .A1 (n_61), .B0 (n_24), .Y
       (n_95));
  XNOR2X1LVT g5446__2883(.A (n_23), .B (n_66), .Y (n_90));
  NAND2BX1LVT g5447__2346(.AN (n_84), .B (n_85), .Y (n_89));
  NAND2BX1LVT g5448__1666(.AN (n_1841), .B (n_1843), .Y (n_88));
  XNOR2X1HVT g5449__7410(.A (\shift_reg[3] [0]), .B (\shift_reg[3]
       [3]), .Y (n_87));
  XNOR2X1LVT g5450__6417(.A (n_73), .B (n_11), .Y (n_86));
  NAND2X4LVT g5451__5477(.A (\shift_reg[4] [3]), .B (\shift_reg[4]
       [1]), .Y (n_92));
  NOR2X4LVT g5452__2398(.A (\shift_reg[4] [1]), .B (\shift_reg[4] [3]),
       .Y (n_91));
  OR2X1LVT g5456__5107(.A (\shift_reg[3] [4]), .B (n_19), .Y (n_85));
  NOR2X2 g5457__6260(.A (n_27), .B (\shift_reg[3] [1]), .Y (n_84));
  AOI21X1LVT g5464__8428(.A0 (\shift_reg[3] [2]), .A1 (n_65), .B0
       (n_69), .Y (n_80));
  NAND2BX1LVT g5465__5526(.AN (n_70), .B (n_72), .Y (n_79));
  XNOR2X1LVT g5466__6783(.A (\shift_reg[2] [3]), .B (n_1627), .Y
       (n_78));
  XNOR2X1LVT g5467__3680(.A (n_14), .B (n_1477), .Y (n_77));
  NAND2BX1LVT g5468__1617(.AN (n_0), .B (n_71), .Y (n_76));
  AOI21X4LVT g5470__1705(.A0 (n_40), .A1 (n_44), .B0 (n_42), .Y (n_81));
  AOI21X4LVT g5471__5122(.A0 (n_63), .A1 (n_35), .B0 (n_64), .Y (n_75));
  INVX1 g5472(.A (\shift_reg[3] [5]), .Y (n_74));
  INVX1 g5473(.A (\shift_reg[3] [6]), .Y (n_73));
  AOI21XLLVT g5484__7098(.A0 (\shift_reg[2] [2]), .A1 (n_57), .B0
       (n_61), .Y (n_67));
  OR2X1LVT g5485__6131(.A (\shift_reg[2] [4]), .B (n_12), .Y (n_72));
  NAND2BX1LVT g5487__1881(.AN (n_64), .B (n_63), .Y (n_66));
  OR2X1LVT g5488__5115(.A (\shift_reg[2] [5]), .B (n_20), .Y (n_71));
  NOR2X1LVT g5489__7482(.A (n_25), .B (n_383), .Y (n_70));
  CLKAND2X6LVT g5490__4733(.A (n_21), .B (n_41), .Y (n_69));
  INVX1LVT g5491(.A (n_41), .Y (n_65));
  OAI21XLLVT g5504__6161(.A0 (n_22), .A1 (\shift_reg[0] [0]), .B0
       (n_56), .Y (n_59));
  NOR2X2LVT g5505__9315(.A (\shift_reg[1] [3]), .B (\shift_reg[1] [1]),
       .Y (n_64));
  XNOR2X1LVT g5506__9945(.A (\shift_reg[0] [6]), .B (\shift_reg[0]
       [7]), .Y (n_58));
  NAND2X2LVT g5507__2883(.A (\shift_reg[1] [3]), .B (\shift_reg[1]
       [1]), .Y (n_63));
  CLKAND2X6LVT g5509__1666(.A (n_20), .B (n_36), .Y (n_61));
  INVXLLVT g5512(.A (n_36), .Y (n_57));
  OAI21X1LVT g5519__7410(.A0 (data_in_reg[0]), .A1 (n_34), .B0 (n_40),
       .Y (n_55));
  AOI21XLLVT g5520__6417(.A0 (\shift_reg[3] [1]), .A1 (\shift_reg[3]
       [0]), .B0 (n_41), .Y (n_54));
  NOR2BX1LVT g5521__5477(.AN (n_44), .B (n_42), .Y (n_53));
  NAND2BX1LVT g5522__2398(.AN (n_45), .B (n_46), .Y (n_52));
  NAND2BX1LVT g5523__5107(.AN (n_47), .B (n_43), .Y (n_51));
  NAND2X8LVT g5524__6260(.A (\shift_reg[0] [0]), .B (n_22), .Y (n_56));
  INVX1LVT g5526(.A (\shift_reg[0] [5]), .Y (n_50));
  INVX1LVT g5529(.A (\shift_reg[0] [4]), .Y (n_49));
  INVX1LVT g5530(.A (\shift_reg[0] [6]), .Y (n_48));
  AOI2BB1X1LVT g5541__4319(.A0N (\shift_reg[1] [2]), .A1N
       (\shift_reg[1] [0]), .B0 (n_23), .Y (n_39));
  AOI21XLLVT g5542__8428(.A0 (n_1627), .A1 (n_383), .B0 (n_36), .Y
       (n_38));
  CLKAND2X2LVT g5543__5526(.A (data_in_reg[2]), .B (n_17), .Y (n_47));
  NAND2X1LVT g5544__6783(.A (data_in_reg[6]), .B (n_34), .Y (n_46));
  NOR2X2LVT g5545__3680(.A (data_in_reg[6]), .B (n_34), .Y (n_45));
  NAND2X4LVT g5546__1617(.A (data_in_reg[1]), .B (n_18), .Y (n_44));
  OR2X2LVT g5547__2802(.A (data_in_reg[2]), .B (n_17), .Y (n_43));
  NOR2X2LVT g5548__1705(.A (data_in_reg[1]), .B (n_18), .Y (n_42));
  NOR2X6LVT g5549__5122(.A (\shift_reg[3] [0]), .B (\shift_reg[3] [1]),
       .Y (n_41));
  NAND2X6LVT g5550__8246(.A (data_in_reg[0]), .B (n_34), .Y (n_40));
  INVX1LVT g5554(.A (\shift_reg[6] [7]), .Y (n_37));
  INVX1HVT g5577(.A (n_35), .Y (n_23));
  INVX1LVT g5580(.A (data_in_reg[7]), .Y (n_33));
  NOR2X6LVT g5588__7098(.A (n_1627), .B (n_383), .Y (n_36));
  NAND2X4LVT g5590__6131(.A (\shift_reg[1] [2]), .B (\shift_reg[1]
       [0]), .Y (n_35));
  DFFX4LVT \data_in_reg_reg[4] (.CK (i_clock), .D (i_data[4]), .Q
       (data_in_reg[4]), .QN (n_18));
  DFFX1LVT \data_in_reg_reg[5] (.CK (i_clock), .D (i_data[5]), .Q
       (data_in_reg[5]), .QN (n_17));
  DFFX4LVT \prod_reg_reg[0][1] (.CK (i_clock), .D (data_in_reg[1]), .Q
       (\shift_reg[0] [1]), .QN (n_16));
  DFFX4LVT \prod_reg_reg[0][2] (.CK (i_clock), .D (data_in_reg[2]), .Q
       (\shift_reg[0] [2]), .QN (n_13));
  DFFX4LVT \prod_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1] [1]),
       .Q (\shift_reg[2] [1]), .QN (n_12));
  DFFX4LVT \prod_reg_reg[2][12] (.CK (i_clock), .D (\prod[2] [13]), .Q
       (\prod[3] [14]), .QN (n_14));
  DFFX1LVT \prod_reg_reg[3][13] (.CK (i_clock), .D (\prod[3] [14]), .Q
       (\prod[4] [14]), .QN (n_11));
  DFFX4LVT \prod_reg_reg[5][12] (.CK (i_clock), .D (\prod[5] [13]), .Q
       (\prod_reg[5] [12]), .QN (n_15));
  DFFX4LVT \shift_reg_reg[0][3] (.CK (i_clock), .D (data_in_reg[3]), .Q
       (\shift_reg[0] [3]), .QN (n_22));
  DFFX1LVT \shift_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1] [2]),
       .Q (\shift_reg[2] [2]), .QN (n_20));
  DFFX1LVT \shift_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1] [3]),
       .Q (\shift_reg[2] [3]), .QN (n_24));
  DFFX1LVT \shift_reg_reg[2][4] (.CK (i_clock), .D (\shift_reg[1] [4]),
       .Q (\shift_reg[2] [4]), .QN (n_25));
  DFFX2LVT \shift_reg_reg[3][1] (.CK (i_clock), .D (n_383), .Q
       (\shift_reg[3] [1]), .QN (n_19));
  DFFX1LVT \shift_reg_reg[3][2] (.CK (i_clock), .D (\shift_reg[2] [2]),
       .Q (\shift_reg[3] [2]), .QN (n_21));
  DFFX1LVT \shift_reg_reg[3][3] (.CK (i_clock), .D (\shift_reg[2] [3]),
       .Q (\shift_reg[3] [3]), .QN (n_26));
  DFFX1LVT \shift_reg_reg[3][4] (.CK (i_clock), .D (\shift_reg[2] [4]),
       .Q (\shift_reg[3] [4]), .QN (n_27));
  DFFX1LVT \shift_reg_reg[5][5] (.CK (i_clock), .D (\shift_reg[4] [5]),
       .Q (\shift_reg[5] [5]), .QN (n_28));
  DFFX4LVT \shift_reg_reg[6][4] (.CK (i_clock), .D (\shift_reg[5] [4]),
       .Q (\shift_reg[6] [4]), .QN (n_29));
  CLKXOR2X1 g2__1881(.A (n_139), .B (n_122), .Y (n_10));
  CLKXOR2X1 g5646__5115(.A (n_134), .B (n_109), .Y (n_9));
  CLKXOR2X1LVT g5647__7482(.A (n_106), .B (n_108), .Y (n_8));
  CLKXOR2X1 g5649__6161(.A (n_95), .B (n_79), .Y (n_6));
  CLKXOR2X1LVT g5651__9945(.A (n_87), .B (n_69), .Y (n_4));
  CLKXOR2X1 g5652__2883(.A (n_61), .B (n_78), .Y (n_3));
  CLKXOR2X1LVT g5653__2346(.A (n_1868), .B (n_102), .Y (n_2));
  CLKXOR2X1LVT g5654__1666(.A (n_40), .B (n_53), .Y (n_1));
  NOR2BX1LVT g5655__7410(.AN (\shift_reg[2] [5]), .B (\shift_reg[2]
       [2]), .Y (n_0));
  ADDFHXLLVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_1__6783(.A
       (\prod_reg[2] [4]), .B (\prod_reg[5] [4]), .CI (\prod_reg[6]
       [4]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_231), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_230));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_1__5107(.A
       (\prod_reg[7] [8]), .B (\prod_reg[1] [8]), .CI (\prod_reg[2]
       [8]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_213), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_212));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_3__4319(.A
       (n_1461), .B (csa_tree_ADD_TC_OP_12_groupi_n_212), .CI (n_1152),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_256), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_179));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_4__1705(.A
       (n_1578), .B (n_771), .CI (csa_tree_ADD_TC_OP_12_groupi_n_256),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_240), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_156));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_1__7098(.A
       (\prod_reg[3] [10]), .B (\prod_reg[5] [10]), .CI (n_382), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_205), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_204));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_1__6161(.A
       (\prod_reg[3] [11]), .B (\prod_reg[2] [11]), .CI
       (\prod_reg[6] [11]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_201),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_200));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_2__7410(.A
       (n_1168), .B (csa_tree_ADD_TC_OP_12_groupi_n_201), .CI (n_1009),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_168), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_167));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_0__5477(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_32), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_28), .CI (n_1167), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_269), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_166));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_1__2398(.A
       (n_1587), .B (csa_tree_ADD_TC_OP_12_groupi_n_166), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_168), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_254), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_253));
  OAI2BB2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6875__1705(.A0N (n_1977),
       .A1N (n_693), .B0 (n_1977), .B1 (n_693), .Y (n_219));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6876__5122(.A (n_984), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_134), .Y (n_220));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6888__4733(.A0 (n_588), .A1
       (n_1697), .B0 (n_587), .Y (csa_tree_ADD_TC_OP_12_groupi_n_134));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6912__6783(.A (n_1960), .B
       (n_1975), .Y (csa_tree_ADD_TC_OP_12_groupi_n_113));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6914__1617(.A (n_2051), .B
       (n_1975), .Y (csa_tree_ADD_TC_OP_12_groupi_n_119));
  INVX2 csa_tree_ADD_TC_OP_12_groupi_g6927(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_102), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_103));
  NOR2X8LVT csa_tree_ADD_TC_OP_12_groupi_g6930__4733(.A (n_1496), .B
       (n_598), .Y (csa_tree_ADD_TC_OP_12_groupi_n_104));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6931__6161(.A (n_1521), .B
       (n_2051), .Y (csa_tree_ADD_TC_OP_12_groupi_n_102));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6942__5477(.A (n_597), .B
       (n_1598), .Y (csa_tree_ADD_TC_OP_12_groupi_n_89));
  CLKAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6961__8428(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_253), .B (n_991), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_87));
  OR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6967__1705(.A (n_911), .B
       (n_922), .Y (csa_tree_ADD_TC_OP_12_groupi_n_78));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6981__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_269), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_254), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_73));
  NOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6982__6131(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_269), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_254), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_72));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6992__2346(.A (n_1724), .B
       (n_870), .Y (n_223));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6998__5477(.A (n_1288), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_52), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_55));
  CLKAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7002__6260(.A (n_629), .B
       (n_1662), .Y (csa_tree_ADD_TC_OP_12_groupi_n_52));
  OR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7008__3680(.A (n_638), .B
       (n_639), .Y (csa_tree_ADD_TC_OP_12_groupi_n_47));
  ADDHX1LVT csa_tree_ADD_TC_OP_12_groupi_g7012__5122(.A
       (\shift_reg[0] [0]), .B (\prod_reg[7] [0]), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_41), .S (n_227));
  INVX1LVT csa_tree_ADD_TC_OP_12_groupi_g7025(.A (\prod[4] [14]), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_28));
  OR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3__9945(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_87), .B (n_868), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_17));
  OAI2BB1X4LVT csa_tree_ADD_TC_OP_12_groupi_g7039__6417(.A0N (n_1496),
       .A1N (n_915), .B0 (csa_tree_ADD_TC_OP_12_groupi_n_78), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_10));
  NOR2BX2LVT csa_tree_ADD_TC_OP_12_groupi_g7045__6260(.AN (n_587), .B
       (n_1804), .Y (csa_tree_ADD_TC_OP_12_groupi_n_5));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7047__8428(.A (n_640), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .Y (n_224));
  CLKINVX6LVT fopt7055(.A (\prod_reg[7] [10]), .Y (n_382));
  CLKBUFX6LVT fopt7057(.A (\shift_reg[2] [1]), .Y (n_383));
  XNOR2X1LVT g2(.A (csa_tree_ADD_TC_OP_12_groupi_n_5), .B (n_1805), .Y
       (n_391));
  OAI21X4LVT g164(.A0 (n_1389), .A1 (n_482), .B0 (n_1583), .Y (n_484));
  AOI21X4LVT g167(.A0 (n_1230), .A1 (n_1567), .B0 (n_1577), .Y (n_482));
  CLKINVX6LVT fopt114(.A (n_1731), .Y (n_496));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6893__2883_dup7102(.A
       (n_540), .B (n_667), .Y (n_534));
  CLKINVX12LVT csa_tree_ADD_TC_OP_12_groupi_g7107(.A (n_1697), .Y
       (n_540));
  XNOR3X1LVT g3(.A (\prod_reg[4] [10]), .B (\prod_reg[2] [10]), .C
       (\prod_reg[0] [10]), .Y (n_544));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_0__7112(.A
       (\prod_reg[4] [10]), .B (\prod_reg[2] [10]), .CI (n_546), .CO
       (n_547), .S (n_548));
  OAI22X4LVT g289(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_17), .A1
       (n_1814), .B0 (n_567), .B1 (n_568), .Y (n_569));
  NOR2X8LVT g296(.A (n_881), .B (n_2052), .Y (n_561));
  CLKINVX1LVT g299(.A (csa_tree_ADD_TC_OP_12_groupi_n_17), .Y (n_567));
  CLKINVX6LVT g290(.A (n_1814), .Y (n_568));
  CLKINVX12LVT g89(.A (n_586), .Y (n_587));
  NOR2X6LVT g90(.A (n_1618), .B (n_585), .Y (n_586));
  NOR2X8LVT g92(.A (n_837), .B (n_836), .Y (n_585));
  CLKAND2X6LVT g88(.A (n_1618), .B (n_585), .Y (n_588));
  NAND2X6LVT g7116(.A (n_1431), .B (n_1046), .Y (n_597));
  NOR2X8LVT g7122(.A (n_1431), .B (n_1046), .Y (n_598));
  INVX3LVT g7124(.A (n_1972), .Y (n_599));
  NOR2X2LVT g78(.A (\prod_reg[5] [5]), .B (\prod_reg[6] [5]), .Y
       (n_610));
  CLKINVX4LVT g75(.A (n_621), .Y (n_622));
  NOR2X6LVT g76(.A (n_618), .B (n_620), .Y (n_621));
  NOR2X6LVT g79(.A (\prod_reg[6] [5]), .B (n_617), .Y (n_618));
  NOR2X4LVT g77(.A (\prod_reg[5] [5]), .B (n_619), .Y (n_620));
  NOR2X8LVT g198(.A (n_631), .B (n_640), .Y (n_641));
  NOR2X8LVT g205(.A (n_629), .B (n_1662), .Y (n_631));
  OAI21X4LVT g7139(.A0 (n_1892), .A1 (n_627), .B0 (n_628), .Y (n_629));
  NOR2X1LVT g7140(.A (\shift_reg[1] [1]), .B (n_1674), .Y (n_627));
  NAND2X1LVT g7142(.A (\shift_reg[1] [1]), .B (n_1674), .Y (n_628));
  AOI2BB1X4LVT g199(.A0N (n_635), .A1N (n_638), .B0 (n_639), .Y
       (n_640));
  OAI21X1LVT g204(.A0 (\shift_reg[0] [1]), .A1 (n_1155), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_41), .Y (n_633));
  NAND2X2LVT g7145(.A (\shift_reg[0] [1]), .B (n_1155), .Y (n_634));
  NOR2X2LVT g7146(.A (n_1154), .B (n_1891), .Y (n_638));
  OAI221X1LVT g200(.A0 (n_644), .A1 (n_634), .B0 (n_645), .B1 (n_646),
       .C0 (n_648), .Y (n_649));
  INVX1 g216(.A (csa_tree_ADD_TC_OP_12_groupi_n_41), .Y (n_644));
  OR2X1LVT g7149(.A (\shift_reg[0] [1]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_41), .Y (n_645));
  INVX1 g7150(.A (n_1156), .Y (n_646));
  AOI31X1LVT g203(.A0 (\shift_reg[0] [1]), .A1 (n_644), .A2 (n_646),
       .B0 (n_647), .Y (n_648));
  NOR3X1LVT g7151(.A (\shift_reg[0] [1]), .B (n_644), .C (n_1156), .Y
       (n_647));
  NOR2X6LVT g107(.A (n_981), .B (n_588), .Y (n_667));
  INVX3LVT g122(.A (n_1464), .Y (n_663));
  NOR2X6LVT g108(.A (n_587), .B (n_981), .Y (n_668));
  NAND2BX4LVT g7157(.AN (n_1435), .B (n_915), .Y (n_679));
  NAND2X8LVT g7165(.A (n_691), .B (n_692), .Y (n_693));
  NOR2X4LVT g7166(.A (n_1960), .B (n_668), .Y (n_691));
  NAND2X6LVT g7167(.A (n_667), .B (n_540), .Y (n_692));
  NOR2X8LVT g52(.A (n_1383), .B (n_853), .Y (n_700));
  NOR2X6LVT g56(.A (n_1834), .B (n_1798), .Y (n_698));
  OAI2BB1X4LVT g7170(.A0N (n_721), .A1N (n_722), .B0 (n_728), .Y
       (n_729));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_3__7173(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_213), .B (n_1485), .CI (n_1622),
       .CO (n_722), .S (n_595));
  OAI21X4LVT g7174(.A0 (n_721), .A1 (n_722), .B0 (n_1570), .Y (n_728));
  OAI22X2LVT g127(.A0 (\prod_reg[6] [10]), .A1 (n_873), .B0
       (\prod_reg[1] [10]), .B1 (n_724), .Y (n_725));
  NOR2X1LVT g128(.A (\prod_reg[1] [10]), .B (\prod_reg[6] [10]), .Y
       (n_732));
  BUFX2LVT g7176(.A (n_1158), .Y (n_738));
  CLKINVX6LVT g14(.A (n_1525), .Y (n_744));
  OAI22X4LVT g7182(.A0 (n_752), .A1 (n_757), .B0 (n_756), .B1 (n_1599),
       .Y (n_761));
  AOI21X2LVT g7183(.A0 (n_544), .A1 (n_1567), .B0 (n_1577), .Y (n_752));
  INVX3LVT g7184(.A (n_756), .Y (n_757));
  NOR2X6LVT g7185(.A (n_754), .B (n_755), .Y (n_756));
  NOR2X4LVT g7186(.A (csa_tree_ADD_TC_OP_12_groupi_n_200), .B (n_1386),
       .Y (n_754));
  CLKAND2X6LVT g131(.A (csa_tree_ADD_TC_OP_12_groupi_n_200), .B
       (n_1386), .Y (n_755));
  OAI21X4LVT g7195(.A0 (n_766), .A1 (n_769), .B0 (n_770), .Y (n_771));
  NOR2X1LVT g144(.A (\prod_reg[5] [8]), .B (\prod_reg[6] [8]), .Y
       (n_766));
  CLKAND2X6LVT g138(.A (n_767), .B (n_768), .Y (n_769));
  NAND2X2LVT g142(.A (\prod_reg[4] [7]), .B (\prod_reg[3] [7]), .Y
       (n_767));
  OAI21X4LVT g139(.A0 (\prod_reg[4] [7]), .A1 (\prod_reg[3] [7]), .B0
       (\prod_reg[0] [7]), .Y (n_768));
  NAND2X1LVT g145(.A (\prod_reg[6] [8]), .B (\prod_reg[5] [8]), .Y
       (n_770));
  NOR2X4LVT g7203(.A (n_800), .B (n_1797), .Y (n_802));
  NOR2X6LVT g7204(.A (n_1401), .B (n_799), .Y (n_800));
  NOR2X4LVT g102(.A (n_1474), .B (n_1475), .Y (n_799));
  CLKINVX6LVT g106(.A (n_663), .Y (n_673));
  OAI22X4LVT g7211(.A0 (n_814), .A1 (n_622), .B0 (n_1074), .B1 (n_621),
       .Y (n_815));
  NAND2X4LVT g7212(.A (\prod_reg[4] [4]), .B (\prod_reg[3] [4]), .Y
       (n_814));
  CLKAND2X3LVT g166(.A (n_835), .B (n_1900), .Y (n_836));
  CLKINVX4LVT g7223(.A (n_1468), .Y (n_835));
  NOR2X4LVT g7224(.A (n_835), .B (n_1900), .Y (n_837));
  NOR2X4LVT g192(.A (n_1739), .B (n_769), .Y (n_840));
  NOR2X6LVT g7226(.A (n_852), .B (n_698), .Y (n_853));
  NAND2BX2LVT g7227(.AN (n_1378), .B (n_1731), .Y (n_852));
  BUFX3LVT fopt7237(.A (n_989), .Y (n_868));
  BUFX3LVT fopt7238(.A (n_1014), .Y (n_870));
  CLKINVX8LVT fopt7240(.A (n_880), .Y (n_881));
  CLKINVX8LVT fopt87(.A (n_879), .Y (n_880));
  AND2X6LVT g7241(.A (n_599), .B (n_1810), .Y (n_879));
  OAI21X4LVT g7242(.A0 (n_883), .A1 (n_1808), .B0 (n_1265), .Y (n_888));
  INVX2LVT g51(.A (n_1565), .Y (n_883));
  NOR2X4LVT g7246(.A (n_599), .B (n_1432), .Y (n_890));
  NOR2BX4LVT g7252(.AN (n_915), .B (csa_tree_ADD_TC_OP_12_groupi_n_89),
       .Y (n_893));
  NAND2X8LVT g7253(.A (n_1552), .B (n_561), .Y (n_894));
  NAND2X6LVT g66(.A (n_914), .B (n_911), .Y (n_915));
  XNOR3X1LVT g71(.A (n_912), .B (n_484), .C (n_913), .Y (n_914));
  INVX2LVT g7257(.A (n_918), .Y (n_912));
  BUFX6LVT g74(.A (csa_tree_ADD_TC_OP_12_groupi_n_167), .Y (n_913));
  NOR2X4LVT g72(.A (n_918), .B (n_913), .Y (n_919));
  NAND2X2LVT g73(.A (n_918), .B (n_913), .Y (n_920));
  XOR3X1LVT g70(.A (csa_tree_ADD_TC_OP_12_groupi_n_167), .B (n_912), .C
       (n_990), .Y (n_922));
  NAND2X2LVT g32(.A (n_673), .B (n_1476), .Y (n_923));
  OAI21X4LVT g29(.A0 (n_673), .A1 (n_1476), .B0 (n_1795), .Y (n_925));
  OAI21X4LVT g349(.A0 (n_931), .A1 (n_935), .B0 (n_937), .Y (n_938));
  CLKAND2X6LVT g352(.A (n_929), .B (n_1455), .Y (n_931));
  NAND2X2LVT g360(.A (\prod_reg[0] [3]), .B (\shift_reg[1] [2]), .Y
       (n_929));
  NOR2X6LVT g355(.A (n_2023), .B (n_1554), .Y (n_935));
  NAND2X4LVT g356(.A (n_1554), .B (n_2023), .Y (n_937));
  XNOR3X1LVT g350(.A (n_2023), .B (n_1554), .C (n_931), .Y (n_939));
  NOR2X8LVT g7288(.A (n_1573), .B (n_802), .Y (n_981));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6933__7291(.A (n_1447), .B
       (n_1751), .Y (n_984));
  INVX3LVT csa_tree_ADD_TC_OP_12_groupi_g7292(.A (n_1447), .Y (n_986));
  NOR3BX4LVT g7294(.AN (n_920), .B (n_988), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_253), .Y (n_989));
  NOR2BX2LVT g7295(.AN (n_484), .B (n_919), .Y (n_988));
  OAI21X2LVT g7296(.A0 (n_990), .A1 (n_919), .B0 (n_920), .Y (n_991));
  INVX1LVT g7297(.A (n_484), .Y (n_990));
  CLKINVX6LVT csa_tree_ADD_TC_OP_12_groupi_g7301(.A (\prod[3] [14]), .Y
       (n_510));
  OAI22X4LVT g286(.A0 (n_1592), .A1 (n_1007), .B0 (n_1008), .B1
       (n_1611), .Y (n_1009));
  NOR2X4LVT g292(.A (\prod[3] [14]), .B (n_511), .Y (n_1000));
  CLKINVX4LVT g287(.A (n_1611), .Y (n_1007));
  AOI21X4LVT g7305(.A0 (n_1612), .A1 (n_1003), .B0 (\prod_reg[1] [11]),
       .Y (n_1005));
  INVX2LVT g7306(.A (n_1592), .Y (n_1008));
  NOR2X4LVT g9(.A (\prod_reg[4] [4]), .B (\prod_reg[3] [4]), .Y
       (n_1010));
  BUFX2LVT g7307(.A (\shift_reg[6] [2]), .Y (n_1011));
  NOR2X8LVT g40(.A (csa_tree_ADD_TC_OP_12_groupi_n_52), .B (n_641), .Y
       (n_1014));
  NOR3X4LVT g104(.A (n_1016), .B (n_1075), .C (n_1020), .Y (n_1021));
  INVX2LVT g7310(.A (n_761), .Y (n_1016));
  BUFX6LVT fopt124(.A (n_1136), .Y (n_1017));
  CLKINVX6LVT fopt142(.A (n_729), .Y (n_1018));
  CLKAND2X3LVT g7312(.A (n_1017), .B (n_1018), .Y (n_1020));
  INVX2LVT g110(.A (n_1016), .Y (n_1022));
  OAI21X4LVT g101(.A0 (n_1016), .A1 (n_1028), .B0 (n_1030), .Y (n_911));
  CLKAND2X3LVT g7313(.A (n_1027), .B (n_1018), .Y (n_1028));
  INVX3LVT fopt123(.A (n_1017), .Y (n_1027));
  OR2X1LVT g109(.A (n_1027), .B (n_1018), .Y (n_1030));
  BUFX2LVT g229(.A (n_1231), .Y (n_1037));
  INVX3LVT g234(.A (csa_tree_ADD_TC_OP_12_groupi_n_240), .Y (n_1038));
  NAND2X4LVT g228(.A (n_1037), .B (n_1038), .Y (n_1042));
  CLKINVX4LVT g7318(.A (n_1232), .Y (n_1046));
  OAI21X4LVT g133(.A0 (n_1058), .A1 (n_1061), .B0 (n_1062), .Y (n_721));
  NOR2X2LVT g7322(.A (\prod_reg[5] [9]), .B (\prod_reg[6] [9]), .Y
       (n_1058));
  CLKAND2X6LVT g7323(.A (n_1059), .B (n_1060), .Y (n_1061));
  NAND2X2LVT g7324(.A (\prod_reg[3] [8]), .B (\prod_reg[4] [8]), .Y
       (n_1059));
  OAI21X2LVT g7325(.A0 (\prod_reg[3] [8]), .A1 (\prod_reg[4] [8]), .B0
       (\prod_reg[0] [8]), .Y (n_1060));
  NAND2X1LVT g7326(.A (\prod_reg[6] [9]), .B (\prod_reg[5] [9]), .Y
       (n_1062));
  NOR2X4LVT g7330(.A (\prod_reg[5] [9]), .B (n_1066), .Y (n_1067));
  NOR2X8LVT g7334(.A (n_863), .B (n_1073), .Y (n_1074));
  NOR2X4LVT g23(.A (n_1020), .B (n_1075), .Y (n_1076));
  NOR2X4 g24(.A (n_1017), .B (n_1018), .Y (n_1075));
  NOR2X2LVT g7336(.A (\prod_reg[6] [7]), .B (\prod_reg[5] [7]), .Y
       (n_1078));
  NOR2X8LVT g429(.A (n_1079), .B (n_1730), .Y (n_1083));
  AND2X6LVT g445(.A (\prod_reg[3] [6]), .B (\prod_reg[4] [6]), .Y
       (n_1079));
  NAND2X1LVT g447(.A (\prod_reg[6] [7]), .B (\prod_reg[5] [7]), .Y
       (n_1084));
  OAI21X4LVT g405(.A0 (n_1120), .A1 (n_1105), .B0 (n_1121), .Y
       (n_1122));
  NOR2X2LVT g414(.A (n_1104), .B (n_1491), .Y (n_1105));
  INVX3LVT fopt466(.A (n_1594), .Y (n_1104));
  NAND2X6LVT g439(.A (n_1093), .B (n_1095), .Y (n_1096));
  NAND2X6LVT g443(.A (n_1092), .B (\prod_reg[5] [7]), .Y (n_1093));
  NAND2X6LVT g7338(.A (n_1094), .B (\prod_reg[6] [7]), .Y (n_1095));
  NOR2X4LVT g426(.A (n_1098), .B (n_1101), .Y (n_1102));
  INVX2LVT g433(.A (n_1096), .Y (n_1098));
  NAND2X4LVT g430(.A (n_1099), .B (n_1100), .Y (n_1101));
  NAND2X4LVT g7339(.A (\prod_reg[3] [6]), .B (\prod_reg[4] [6]), .Y
       (n_1099));
  OAI21X4LVT g438(.A0 (\prod_reg[4] [6]), .A1 (\prod_reg[3] [6]), .B0
       (\prod_reg[0] [6]), .Y (n_1100));
  NOR2X8LVT g420(.A (n_1109), .B (n_1119), .Y (n_1120));
  NOR2X4LVT g446(.A (n_1107), .B (n_1108), .Y (n_1109));
  INVX3 g455(.A (n_1106), .Y (n_1107));
  INVX3LVT g453(.A (n_1896), .Y (n_1108));
  AOI21X4LVT g422(.A0 (n_1107), .A1 (n_1108), .B0 (n_1897), .Y
       (n_1119));
  NAND2X4LVT g431(.A (n_1112), .B (n_1114), .Y (n_1115));
  NAND3X4LVT g436(.A (\prod_reg[4] [6]), .B (n_1111), .C (n_1080), .Y
       (n_1112));
  NAND3X4LVT g435(.A (n_1113), .B (n_1111), .C (\prod_reg[0] [6]), .Y
       (n_1114));
  OAI21X4LVT g432(.A0 (n_1080), .A1 (n_1099), .B0 (n_1116), .Y
       (n_1117));
  NAND3X4LVT g434(.A (\prod_reg[3] [6]), .B (n_1113), .C (n_1080), .Y
       (n_1116));
  NAND2X2LVT g415(.A (n_1104), .B (n_1491), .Y (n_1121));
  NAND2X4LVT g407(.A (n_1120), .B (n_1123), .Y (n_1124));
  MXI2X4LVT g411(.A (n_1594), .B (n_1104), .S0 (n_1491), .Y (n_1123));
  INVX2LVT g416(.A (n_1120), .Y (n_1125));
  CLKINVX4LVT g410(.A (n_1123), .Y (n_1126));
  OAI21X4LVT g117(.A0 (n_1130), .A1 (n_1133), .B0 (n_1134), .Y (n_918));
  NOR2X4LVT g7340(.A (csa_tree_ADD_TC_OP_12_groupi_n_205), .B (n_1132),
       .Y (n_1133));
  BUFX6LVT g7342(.A (n_547), .Y (n_1132));
  NAND2X2LVT g7343(.A (csa_tree_ADD_TC_OP_12_groupi_n_205), .B
       (n_1132), .Y (n_1134));
  XNOR3X1LVT g118(.A (csa_tree_ADD_TC_OP_12_groupi_n_205), .B (n_1132),
       .C (n_1130), .Y (n_1136));
  CLKINVX8LVT g80(.A (n_1137), .Y (n_1138));
  NOR2X8LVT g81(.A (n_1960), .B (n_668), .Y (n_1137));
  CLKAND2X6LVT g7346(.A (n_667), .B (n_540), .Y (n_1139));
  ADDFHX1LVT g7351(.A (\prod_reg[4] [8]), .B (\prod_reg[0] [8]), .CI
       (\prod_reg[3] [8]), .CO (UNCONNECTED0), .S (n_1152));
  BUFX12LVT g7352(.A (\shift_reg[6] [0]), .Y (n_1153));
  ADDFHX2LVT g7353(.A (\prod_reg[7] [1]), .B (\shift_reg[6] [0]), .CI
       (\shift_reg[1] [0]), .CO (n_1154), .S (n_1155));
  BUFX2LVT g7354(.A (n_1155), .Y (n_1156));
  OAI21X4LVT g7356(.A0 (n_1159), .A1 (n_1736), .B0 (n_1163), .Y
       (n_1164));
  INVX2LVT g7357(.A (n_1158), .Y (n_1159));
  NAND2BX2LVT g7358(.AN (n_1378), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_73), .Y (n_1158));
  NAND2X8LVT g7360(.A (n_1239), .B (n_1735), .Y (n_1163));
  BUFX2LVT g7363(.A (\prod_reg[5] [12]), .Y (n_1165));
  ADDFHX1LVT g7364(.A (\prod_reg[3] [12]), .B (\prod_reg[4] [12]), .CI
       (n_1166), .CO (n_1167), .S (n_1168));
  CLKINVX6LVT g97(.A (\prod_reg[5] [12]), .Y (n_1166));
  NOR2X8LVT g15(.A (n_1755), .B (n_1178), .Y (n_1179));
  NOR2X6LVT g7368(.A (n_597), .B (n_1496), .Y (n_1178));
  NAND2X8LVT g7389(.A (n_1576), .B (n_1680), .Y (n_1208));
  ADDFHX1LVT g7393(.A (\prod_reg[3] [7]), .B (\prod_reg[0] [7]), .CI
       (\prod_reg[4] [7]), .CO (UNCONNECTED1), .S (n_1212));
  NAND2X8LVT g7395(.A (n_1125), .B (n_1126), .Y (n_1213));
  ADDFHX1LVT g7398(.A (n_1894), .B (n_815), .CI (n_938), .CO (n_1224),
       .S (n_1215));
  BUFX2LVT g7400(.A (n_1883), .Y (n_1217));
  NAND2X2LVT g7402(.A (n_1217), .B (n_1749), .Y (n_1220));
  CLKINVX6LVT g7403(.A (n_1222), .Y (n_1223));
  XNOR3X1LVT g136(.A (n_1883), .B (n_1888), .C (n_1215), .Y (n_1222));
  NOR2X6LVT g7407(.A (n_1022), .B (n_1076), .Y (n_1228));
  BUFX2LVT g7408(.A (n_548), .Y (n_1230));
  XOR3X1LVT g7409(.A (n_1231), .B (csa_tree_ADD_TC_OP_12_groupi_n_240),
       .C (n_1678), .Y (n_1232));
  XNOR3X1LVT g113(.A (n_1621), .B (n_548), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_204), .Y (n_1231));
  NOR2X8LVT g46(.A (n_1564), .B (n_1743), .Y (n_1239));
  INVX3LVT g94(.A (n_1243), .Y (n_1244));
  OAI21X4LVT g7414(.A0 (n_1078), .A1 (n_1083), .B0 (n_1084), .Y
       (n_1243));
  XNOR3X1LVT g7416(.A (n_1243), .B (n_1591), .C (n_1463), .Y (n_1248));
  NAND2X8LVT g43(.A (n_1264), .B (n_1809), .Y (n_1265));
  NOR2X6LVT g45(.A (n_1968), .B (n_1284), .Y (n_1264));
  OAI22X4LVT g7427(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_103), .A1
       (n_1268), .B0 (n_1451), .B1 (n_1582), .Y (n_1272));
  NOR2X4LVT g86(.A (n_1586), .B (n_1267), .Y (n_1268));
  CLKAND2X6LVT g7428(.A (csa_tree_ADD_TC_OP_12_groupi_n_134), .B
       (n_1449), .Y (n_1267));
  BUFX2LVT g7438(.A (n_1745), .Y (n_1278));
  OAI21X4LVT g7440(.A0 (n_1967), .A1 (n_1959), .B0 (n_1283), .Y
       (n_1284));
  CLKINVX4LVT fopt56(.A (n_1282), .Y (n_1283));
  BUFX6LVT fopt57(.A (n_1281), .Y (n_1282));
  CLKAND2X6LVT g7441(.A (n_1971), .B (n_1973), .Y (n_1281));
  NOR2X8LVT g50(.A (n_890), .B (n_1281), .Y (n_1287));
  BUFX2LVT fopt7443(.A (n_631), .Y (n_1288));
  BUFX3LVT g7534(.A (csa_tree_ADD_TC_OP_12_groupi_n_72), .Y (n_1378));
  NAND2X8LVT g7535(.A (csa_tree_ADD_TC_OP_12_groupi_n_73), .B (n_1382),
       .Y (n_1383));
  OAI21X4LVT g7537(.A0 (n_1380), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_87), .B0 (n_1381), .Y (n_1382));
  NOR2X4LVT g7538(.A (n_989), .B (n_915), .Y (n_1380));
  INVX1LVT g35(.A (n_1378), .Y (n_1381));
  CLKINVX8LVT fopt1(.A (n_1603), .Y (n_1386));
  CLKAND2X3LVT g7540(.A (n_1386), .B (n_1388), .Y (n_1389));
  INVX2LVT g12(.A (csa_tree_ADD_TC_OP_12_groupi_n_200), .Y (n_1388));
  CLKINVX8LVT g7552(.A (n_1796), .Y (n_1401));
  AOI21X4LVT g7564(.A0 (n_1137), .A1 (n_534), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_119), .Y (n_1417));
  AO22X4LVT g7573(.A0 (n_1584), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_156), .B0 (n_595), .B1 (n_1614),
       .Y (n_1431));
  XOR3X1LVT g7578(.A (n_1811), .B (n_1614), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_156), .Y (n_1432));
  NOR3X8LVT g7582(.A (n_1435), .B (n_1746), .C (n_1745), .Y (n_1438));
  CLKINVX8LVT fopt29(.A (csa_tree_ADD_TC_OP_12_groupi_n_78), .Y
       (n_1435));
  AOI2BB1X4LVT g7587(.A0N (n_99), .A1N (n_134), .B0 (n_1443), .Y
       (n_1444));
  INVX2LVT g54(.A (n_100), .Y (n_1443));
  OAI21X1 g7588(.A0 (n_99), .A1 (n_134), .B0 (n_100), .Y (n_1446));
  BUFX12LVT fopt7589(.A (n_981), .Y (n_1447));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6911__7590(.A (n_1745), .B
       (n_1448), .Y (n_1449));
  BUFX6LVT csa_tree_ADD_TC_OP_12_groupi_g7591(.A (n_1447), .Y (n_1448));
  NOR3BX4LVT csa_tree_ADD_TC_OP_12_groupi_g7042__7592(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_134), .B (n_1448), .C (n_1278),
       .Y (n_1451));
  NOR2BX4LVT g7594(.AN (\shift_reg[5] [4]), .B (n_1452), .Y (n_1453));
  OAI21X4LVT g7597(.A0 (\prod_reg[0] [3]), .A1 (\shift_reg[1] [2]), .B0
       (\shift_reg[5] [1]), .Y (n_1455));
  BUFX6LVT fopt7598(.A (\shift_reg[5] [1]), .Y (n_1452));
  INVX2LVT fopt7601(.A (n_207), .Y (n_1460));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_1__7602(.A
       (\prod_reg[7] [7]), .B (\prod_reg[2] [7]), .CI (\prod_reg[1]
       [7]), .CO (n_1461), .S (n_1462));
  ADDFHX2LVT g7603(.A (n_1895), .B (n_1462), .CI (n_1212), .CO
       (n_1463), .S (n_1464));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_4__7604(.A
       (n_2039), .B (n_1887), .CI (n_1492), .CO (n_1471), .S (n_1468));
  CLKAND2X3LVT g7609(.A (n_673), .B (n_1471), .Y (n_1473));
  NOR2X4LVT g7610(.A (n_1471), .B (n_673), .Y (n_1474));
  CLKAND2X6LVT g7611(.A (n_1471), .B (n_673), .Y (n_1475));
  BUFX6LVT g7612(.A (n_1471), .Y (n_1476));
  OAI21X4LVT g161(.A0 (n_1478), .A1 (n_1616), .B0 (n_1481), .Y
       (n_1482));
  NOR2X1LVT g7613(.A (\shift_reg[2] [3]), .B (n_1477), .Y (n_1478));
  INVX2LVT g168(.A (\shift_reg[2] [6]), .Y (n_1477));
  NAND2X1LVT g7615(.A (\shift_reg[2] [3]), .B (n_1477), .Y (n_1481));
  XNOR2X1LVT g162(.A (n_1483), .B (n_1616), .Y (n_1484));
  NOR2BX1LVT g163(.AN (n_1481), .B (n_1478), .Y (n_1483));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_0__7616(.A
       (\prod_reg[4] [9]), .B (\prod_reg[0] [9]), .CI (\prod_reg[3]
       [9]), .CO (n_1486), .S (n_1485));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_2__7620(.A
       (\prod_reg[5] [6]), .B (\prod_reg[6] [6]), .CI (n_1885), .CO
       (n_1491), .S (n_1492));
  XOR3X1LVT g7623(.A (n_1017), .B (n_761), .C (n_729), .Y (n_1494));
  NOR3X8LVT g7624(.A (n_1208), .B (n_1021), .C (n_1228), .Y (n_1496));
  OAI22X4LVT g7626(.A0 (n_1499), .A1 (n_1525), .B0 (n_2032), .B1
       (n_744), .Y (n_1500));
  INVX1LVT g7627(.A (n_2032), .Y (n_1499));
  BUFX6LVT fopt7648(.A (n_597), .Y (n_1521));
  NOR2X8LVT g7649(.A (n_1417), .B (n_1524), .Y (n_1525));
  OAI21X4LVT g7650(.A0 (n_1522), .A1 (n_1553), .B0 (n_1521), .Y
       (n_1524));
  OR2X2LVT g7651(.A (n_879), .B (n_598), .Y (n_1522));
  CLKINVX12LVT fopt7669(.A (n_1287), .Y (n_1552));
  NOR2X6LVT g7670(.A (n_1074), .B (n_1010), .Y (n_1554));
  DFFX4LVT \shift_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4] [3]),
       .Q (\shift_reg[5] [3]), .QN (n_93));
  DFFX1 \prod_reg_reg[4][13] (.CK (i_clock), .D (\prod[4] [14]), .Q
       (\prod[5] [13]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_32));
  DFFX2LVT \prod_reg_reg[0][10] (.CK (i_clock), .D (n_181), .Q
       (\prod_reg[0] [10]), .QN (n_546));
  DFFX4LVT \prod_reg_reg[5][5] (.CK (i_clock), .D (n_2), .Q
       (\prod_reg[5] [5]), .QN (n_617));
  DFFX4LVT \prod_reg_reg[6][5] (.CK (i_clock), .D (n_8), .Q
       (\prod_reg[6] [5]), .QN (n_619));
  DFFX4LVT \prod_reg_reg[6][10] (.CK (i_clock), .D (n_1460), .Q
       (\prod_reg[6] [10]), .QN (n_724));
  DFFX4LVT \prod_reg_reg[6][8] (.CK (i_clock), .D (n_184), .Q
       (\prod_reg[6] [8]), .QN (n_772));
  DFFX4LVT \prod_reg_reg[5][8] (.CK (i_clock), .D (n_170), .Q
       (\prod_reg[5] [8]), .QN (n_774));
  DFFX4LVT \prod_reg_reg[3][4] (.CK (i_clock), .D (n_38), .Q
       (\prod_reg[3] [4]), .QN (n_863));
  DFFX4LVT \prod_reg_reg[1][10] (.CK (i_clock), .D (n_179), .Q
       (\prod_reg[1] [10]), .QN (n_873));
  DFFX4LVT \prod_reg_reg[0][3] (.CK (i_clock), .D (n_55), .Q
       (\prod_reg[0] [3]), .QN (n_948));
  DFFX4LVT \shift_reg_reg[5][4] (.CK (i_clock), .D (\shift_reg[4] [4]),
       .Q (\shift_reg[5] [4]), .QN (n_993));
  DFFX4LVT \prod_reg_reg[6][11] (.CK (i_clock), .D (n_206), .Q
       (\prod_reg[6] [11]), .QN (n_511));
  DFFX4LVT \prod_reg_reg[5][11] (.CK (i_clock), .D (n_203), .Q
       (\prod_reg[5] [11]), .QN (n_1003));
  DFFX4LVT \prod_reg_reg[5][9] (.CK (i_clock), .D (n_193), .Q
       (\prod_reg[5] [9]), .QN (n_1064));
  DFFX4LVT \prod_reg_reg[6][9] (.CK (i_clock), .D (n_198), .Q
       (\prod_reg[6] [9]), .QN (n_1066));
  DFFX4LVT \prod_reg_reg[4][4] (.CK (i_clock), .D (n_54), .Q
       (\prod_reg[4] [4]), .QN (n_1073));
  DFFX4LVT \prod_reg_reg[0][6] (.CK (i_clock), .D (n_133), .Q
       (\prod_reg[0] [6]), .QN (n_1080));
  DFFX4LVT \prod_reg_reg[6][7] (.CK (i_clock), .D (n_161), .Q
       (\prod_reg[6] [7]), .QN (n_1092));
  DFFX4LVT \prod_reg_reg[5][7] (.CK (i_clock), .D (n_152), .Q
       (\prod_reg[5] [7]), .QN (n_1094));
  DFFX4LVT \prod_reg_reg[3][6] (.CK (i_clock), .D (n_3), .Q
       (\prod_reg[3] [6]), .QN (n_1111));
  DFFX4LVT \prod_reg_reg[4][6] (.CK (i_clock), .D (n_4), .Q
       (\prod_reg[4] [6]), .QN (n_1113));
  OR2X6LVT g7722(.A (n_1380), .B (csa_tree_ADD_TC_OP_12_groupi_n_87),
       .Y (n_1564));
  OR2X2LVT g7723(.A (n_890), .B (n_879), .Y (n_1565));
  OR2X6LVT g7725(.A (n_1621), .B (csa_tree_ADD_TC_OP_12_groupi_n_204),
       .Y (n_1567));
  CLKXOR2X1LVT g7727(.A (n_635), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_47), .Y (n_1569));
  XOR2X2LVT g7728(.A (n_725), .B (n_1486), .Y (n_1570));
  AO21X4LVT g7731(.A0 (n_1902), .A1 (n_1468), .B0 (n_1899), .Y
       (n_1573));
  OR2X4LVT g7734(.A (n_1037), .B (n_1038), .Y (n_1576));
  AND2X4LVT g7735(.A (n_1621), .B (csa_tree_ADD_TC_OP_12_groupi_n_204),
       .Y (n_1577));
  CLKXOR2X1LVT g7736(.A (n_1593), .B (n_1061), .Y (n_1578));
  OR2X4LVT g7737(.A (n_1244), .B (n_1591), .Y (n_1579));
  OR2X6LVT g7740(.A (csa_tree_ADD_TC_OP_12_groupi_n_102), .B (n_1586),
       .Y (n_1582));
  NAND2BX2LVT g7741(.AN (n_1386), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_200), .Y (n_1583));
  NAND2BX4LVT g7742(.AN (n_1614), .B (n_1811), .Y (n_1584));
  OAI2BB1X4LVT g7744(.A0N (n_880), .A1N (n_1552), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_113), .Y (n_1586));
  ADDFX1LVT g7745(.A (n_510), .B (n_511), .CI (n_1007), .CO (n_1587),
       .S (UNCONNECTED2));
  AOI21X4LVT g7749(.A0 (n_769), .A1 (n_1739), .B0 (n_840), .Y (n_1591));
  AOI2BB1X4LVT g7750(.A0N (\prod_reg[6] [11]), .A1N (n_510), .B0
       (n_1000), .Y (n_1592));
  AOI2BB1X2LVT g7751(.A0N (\prod_reg[6] [9]), .A1N (n_1064), .B0
       (n_1067), .Y (n_1593));
  AOI2BB1X4LVT g7752(.A0N (n_1096), .A1N (n_1083), .B0 (n_1102), .Y
       (n_1594));
  AOI2BB1X4LVT g7754(.A0N (n_1471), .A1N (n_673), .B0 (n_1473), .Y
       (n_1596));
  OAI2BB1X4LVT g7756(.A0N (n_1680), .A1N (n_1576), .B0 (n_1494), .Y
       (n_1598));
  AO21X4LVT g7757(.A0 (n_544), .A1 (n_1567), .B0 (n_1577), .Y (n_1599));
  OAI2BB1X4LVT g7760(.A0N (\prod_reg[6] [10]), .A1N (\prod_reg[1]
       [10]), .B0 (n_1602), .Y (n_1603));
  NAND2BX4LVT g7761(.AN (n_732), .B (n_1486), .Y (n_1602));
  MXI2X2LVT g7767(.A (\prod_reg[0] [3]), .B (n_948), .S0
       (\shift_reg[1] [2]), .Y (n_1608));
  NOR2X6LVT g7768(.A (n_1610), .B (n_1005), .Y (n_1611));
  NOR2BX4LVT g7769(.AN (\prod_reg[4] [11]), .B (n_1003), .Y (n_1610));
  INVX3LVT g7770(.A (\prod_reg[4] [11]), .Y (n_1612));
  NAND2X8LVT g7771(.A (n_1613), .B (n_1579), .Y (n_1614));
  OAI2BB1X2LVT g7772(.A0N (n_1591), .A1N (n_1244), .B0 (n_1463), .Y
       (n_1613));
  CLKAND2X3LVT g7773(.A (n_1615), .B (n_71), .Y (n_1616));
  NAND2BX4LVT g7774(.AN (n_0), .B (n_121), .Y (n_1615));
  AND2X4LVT g7775(.A (n_1617), .B (n_1220), .Y (n_1618));
  OAI21X2LVT g7776(.A0 (n_1217), .A1 (n_1749), .B0 (n_1215), .Y
       (n_1617));
  ADDFHX1LVT g7778(.A (\prod_reg[7] [9]), .B (\prod_reg[1] [9]), .CI
       (\prod_reg[2] [9]), .CO (n_1621), .S (n_1622));
  ADDFX1LVT g7782(.A (\prod_reg[5] [11]), .B (\prod_reg[4] [11]), .CI
       (\prod_reg[1] [11]), .CO (UNCONNECTED3), .S (n_1130));
  CLKXOR2X1 g5650__7784(.A (n_81), .B (n_51), .Y (n_5));
  CLKXOR2X1 g5648__7786(.A (n_113), .B (n_89), .Y (n_7));
  CLKBUFX3LVT g7793(.A (\shift_reg[5] [0]), .Y (n_1626));
  BUFX6LVT fopt7794(.A (\shift_reg[2] [0]), .Y (n_1627));
  BUFX6LVT g1(.A (\shift_reg[6] [1]), .Y (n_1628));
  INVX1LVT g2123(.A (n_1889), .Y (n_1630));
  AO21X4LVT g2133(.A0 (\shift_reg[5] [1]), .A1 (n_1608), .B0 (n_1632),
       .Y (n_1633));
  AOI211X2LVT g2134(.A0 (\shift_reg[1] [2]), .A1 (\prod_reg[0] [3]),
       .B0 (\shift_reg[5] [1]), .C0 (n_1631), .Y (n_1632));
  NOR2X2LVT g2142(.A (\shift_reg[1] [2]), .B (\prod_reg[0] [3]), .Y
       (n_1631));
  AOI21X4LVT g2112(.A0 (n_1642), .A1 (n_1654), .B0 (n_1655), .Y
       (n_1656));
  CLKMX2X3LVT g2120(.A (n_12), .B (\shift_reg[2] [1]), .S0 (n_1641), .Y
       (n_1642));
  NOR2X8LVT g2140(.A (n_1638), .B (n_1640), .Y (n_1641));
  NOR2X4LVT g2144(.A (\prod_reg[7] [3]), .B (n_1637), .Y (n_1638));
  NOR2X4LVT g2145(.A (n_1639), .B (\shift_reg[6] [2]), .Y (n_1640));
  NOR2X6LVT g2125(.A (n_1650), .B (n_1653), .Y (n_1654));
  NOR2X6LVT g2128(.A (n_1645), .B (n_1866), .Y (n_1650));
  NOR2X8LVT g2149(.A (n_1643), .B (n_13), .Y (n_1645));
  CLKINVX6LVT g2155(.A (\prod_reg[7] [2]), .Y (n_1643));
  INVX3LVT g2151(.A (\shift_reg[3] [0]), .Y (n_1648));
  NOR2BX4LVT g2127(.AN (n_1645), .B (n_1652), .Y (n_1653));
  AOI2BB1X4LVT g2137(.A0N (n_1648), .A1N (n_1865), .B0 (n_1863), .Y
       (n_1652));
  NOR2X4LVT g2114(.A (n_1642), .B (n_1654), .Y (n_1655));
  NAND2X1LVT g2117(.A (n_1889), .B (n_1633), .Y (n_1657));
  CLKMX2X3LVT g2110(.A (n_1656), .B (n_1660), .S0 (n_1661), .Y
       (n_1662));
  XNOR2X1LVT g2113(.A (n_1659), .B (n_1654), .Y (n_1660));
  CLKXOR2X1LVT g2121(.A (n_12), .B (n_1641), .Y (n_1659));
  AOI2BB2X4LVT g2115(.A0N (n_1630), .A1N (n_1633), .B0 (n_1633), .B1
       (n_1630), .Y (n_1661));
  NOR2X4LVT g2118(.A (n_1667), .B (n_1668), .Y (n_1669));
  NOR2X4LVT g2122(.A (n_2023), .B (n_1666), .Y (n_1667));
  NAND2BX4LVT g2131(.AN (n_1863), .B (n_1645), .Y (n_1666));
  CLKAND2X2LVT g2126(.A (\shift_reg[2] [1]), .B (n_1641), .Y (n_1668));
  NAND2X2LVT g2129(.A (n_12), .B (n_1670), .Y (n_1671));
  INVX2LVT g2135(.A (n_1641), .Y (n_1670));
  OAI22X4LVT g2139(.A0 (n_1643), .A1 (\shift_reg[0] [2]), .B0
       (\prod_reg[7] [2]), .B1 (n_13), .Y (n_1674));
  OAI21X2LVT g2119(.A0 (n_12), .A1 (n_1675), .B0 (n_1676), .Y (n_1677));
  NOR2X4LVT g2141(.A (\prod_reg[7] [3]), .B (\shift_reg[6] [2]), .Y
       (n_1675));
  NAND2X2LVT g2148(.A (\prod_reg[7] [3]), .B (\shift_reg[6] [2]), .Y
       (n_1676));
  NAND2X8LVT g49(.A (n_1042), .B (n_1679), .Y (n_1680));
  BUFX6LVT g7795(.A (n_1678), .Y (n_1679));
  XOR3X1LVT g7796(.A (n_721), .B (n_1570), .C (n_722), .Y (n_1678));
  NAND2X6LVT g38(.A (n_880), .B (csa_tree_ADD_TC_OP_12_groupi_n_104),
       .Y (n_1681));
  CLKINVX6LVT g7798(.A (n_1552), .Y (n_1553));
  NOR2X6LVT g7802(.A (n_1138), .B (n_1139), .Y (n_1686));
  NOR2X8LVT g169(.A (n_1694), .B (n_1696), .Y (n_1697));
  NOR3X6LVT g173(.A (n_1723), .B (n_1014), .C (n_1728), .Y (n_1694));
  NOR2X6LVT g170(.A (n_1728), .B (n_1722), .Y (n_1696));
  AOI21X4LVT g160(.A0 (n_1709), .A1 (n_1223), .B0 (n_1721), .Y
       (n_1722));
  AO22X4LVT g7811(.A0 (n_1704), .A1 (n_1707), .B0 (n_2040), .B1
       (n_1708), .Y (n_1709));
  BUFX6LVT g7812(.A (n_1884), .Y (n_1704));
  NAND2X4LVT g177(.A (n_1705), .B (n_1706), .Y (n_1707));
  CLKINVX6LVT g182(.A (n_939), .Y (n_1705));
  CLKINVX6LVT g178(.A (n_2040), .Y (n_1706));
  CLKINVX8LVT g181(.A (n_1705), .Y (n_1708));
  NOR2X8LVT g7813(.A (n_1711), .B (n_1720), .Y (n_1721));
  INVX2LVT g7814(.A (n_2047), .Y (n_1711));
  CLKINVX6LVT g7816(.A (n_1859), .Y (n_1720));
  NOR2X6LVT g7819(.A (n_2040), .B (n_1705), .Y (n_1712));
  NOR2X8LVT g176(.A (n_1706), .B (n_1708), .Y (n_1713));
  INVX2LVT g179(.A (n_1704), .Y (n_1714));
  CLKINVX6LVT g7821(.A (n_1712), .Y (n_1716));
  CLKINVX6LVT g175(.A (n_1713), .Y (n_1717));
  NOR2X1LVT g159(.A (n_1721), .B (n_1723), .Y (n_1724));
  NOR2X6LVT g7822(.A (n_2047), .B (n_1859), .Y (n_1723));
  BUFX2LVT fopt7823(.A (n_1721), .Y (n_1725));
  NOR2X6LVT g165(.A (n_1709), .B (n_1223), .Y (n_1728));
  NOR2X8LVT g7825(.A (n_1080), .B (n_1729), .Y (n_1730));
  NOR2X8LVT g25(.A (\prod_reg[4] [6]), .B (\prod_reg[3] [6]), .Y
       (n_1729));
  NAND2X8LVT g7826(.A (n_1731), .B (n_1732), .Y (n_1733));
  NOR2X8LVT g7827(.A (n_868), .B (n_1435), .Y (n_1731));
  NOR2X8LVT g7828(.A (n_1746), .B (n_1745), .Y (n_1732));
  NOR2X8LVT g7829(.A (n_738), .B (n_1734), .Y (n_1735));
  NOR2X8LVT g7830(.A (n_1686), .B (n_1733), .Y (n_1734));
  NOR3X6LVT g47(.A (n_1564), .B (n_1743), .C (n_1734), .Y (n_1736));
  NAND2X6LVT g21(.A (n_1737), .B (n_1738), .Y (n_1739));
  NAND2X4LVT g7831(.A (\prod_reg[5] [8]), .B (n_772), .Y (n_1737));
  NAND2X6LVT g22(.A (\prod_reg[6] [8]), .B (n_774), .Y (n_1738));
  NOR2X8LVT g7832(.A (n_496), .B (n_1742), .Y (n_1743));
  NOR2X8LVT g7833(.A (n_1740), .B (n_1741), .Y (n_1742));
  CLKINVX8LVT g7834(.A (n_1179), .Y (n_1740));
  NOR2X8LVT g7835(.A (n_1681), .B (n_1553), .Y (n_1741));
  CLKINVX16LVT g7837(.A (n_1975), .Y (n_1745));
  CLKINVX8LVT fopt7838(.A (csa_tree_ADD_TC_OP_12_groupi_n_104), .Y
       (n_1746));
  NOR2X8LVT csa_tree_ADD_TC_OP_12_groupi_g6916__7840(.A (n_1746), .B
       (n_1745), .Y (n_1747));
  BUFX3LVT fopt7841(.A (n_1888), .Y (n_1749));
  CLKINVX4LVT fopt7842(.A (n_1959), .Y (n_1751));
  CLKINVX6LVT fopt7845(.A (n_1598), .Y (n_1755));
  NOR3X4LVT g7883(.A (n_1474), .B (n_1475), .C (n_1796), .Y (n_1797));
  CLKINVX8LVT g41(.A (n_1795), .Y (n_1796));
  NAND2X8LVT g42(.A (n_1124), .B (n_1213), .Y (n_1795));
  CLKINVX6LVT fopt7884(.A (n_1742), .Y (n_1798));
  OAI32X4LVT g7886(.A0 (n_679), .A1 (n_1834), .A2 (n_1798), .B0
       (n_1801), .B1 (n_1802), .Y (n_1803));
  INVX1LVT g7888(.A (n_679), .Y (n_1801));
  NOR2X6LVT g7889(.A (n_1798), .B (n_1834), .Y (n_1802));
  BUFX6LVT csa_tree_ADD_TC_OP_12_groupi_g7890(.A (n_588), .Y (n_1804));
  CLKINVX4LVT csa_tree_ADD_TC_OP_12_groupi_g7891(.A (n_540), .Y
       (n_1805));
  NOR3X4LVT g7892(.A (n_1968), .B (n_1284), .C (n_1807), .Y (n_1808));
  NOR3X8LVT g7893(.A (n_1804), .B (n_1805), .C (n_1806), .Y (n_1807));
  NAND2X8LVT csa_tree_ADD_TC_OP_12_groupi_g6934__7894(.A (n_986), .B
       (n_1965), .Y (n_1806));
  NOR2X4LVT g7895(.A (n_1565), .B (n_1807), .Y (n_1809));
  XNOR3X1LVT g7896(.A (n_595), .B (n_1614), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_156), .Y (n_1810));
  CLKINVX6LVT g7897(.A (n_595), .Y (n_1811));
  NAND2X8LVT g7898(.A (n_1812), .B (n_1862), .Y (n_1814));
  NAND2X8LVT g7899(.A (n_693), .B (n_1438), .Y (n_1812));
  ADDHX2LVT g7917(.A (n_1891), .B (n_1154), .CO (n_639), .S
       (UNCONNECTED4));
  ADDHX2LVT g7919(.A (n_633), .B (n_634), .CO (n_635), .S
       (UNCONNECTED5));
  NOR2X8LVT g7920(.A (n_1832), .B (n_1833), .Y (n_1834));
  CLKINVX6LVT g28(.A (n_1747), .Y (n_1832));
  NOR2X6LVT g7921(.A (n_1138), .B (n_1139), .Y (n_1833));
  OAI21X4LVT g7928(.A0 (n_1841), .A1 (n_1842), .B0 (n_1843), .Y
       (n_1844));
  NOR2X2LVT g31(.A (\shift_reg[3] [2]), .B (n_74), .Y (n_1841));
  CLKINVX4LVT g7929(.A (n_126), .Y (n_1842));
  NAND2X2LVT g30(.A (\shift_reg[3] [2]), .B (n_74), .Y (n_1843));
  NAND2X8LVT g59(.A (n_1857), .B (n_1858), .Y (n_1859));
  NAND3X8LVT g60(.A (n_1704), .B (n_1716), .C (n_1717), .Y (n_1857));
  OAI21X4LVT g61(.A0 (n_1712), .A1 (n_1713), .B0 (n_1714), .Y (n_1858));
  NAND2X8LVT g16(.A (n_1860), .B (n_1861), .Y (n_1862));
  CLKINVX4LVT g18(.A (csa_tree_ADD_TC_OP_12_groupi_n_10), .Y (n_1860));
  NAND2X8LVT g17(.A (n_893), .B (n_894), .Y (n_1861));
  NOR2X4LVT g7941(.A (\shift_reg[3] [0]), .B (\shift_reg[4] [0]), .Y
       (n_1863));
  INVX2LVT g7943(.A (\shift_reg[4] [0]), .Y (n_1865));
  CLKMX2X3LVT g7944(.A (\shift_reg[4] [0]), .B (n_1865), .S0 (n_1648),
       .Y (n_1866));
  OA21X1LVT g5483__7945(.A0 (\shift_reg[4] [2]), .A1 (n_1867), .B0
       (n_1868), .Y (n_1869));
  BUFX2 g7946(.A (\shift_reg[4] [0]), .Y (n_1867));
  NAND2X6LVT g5508__7947(.A (\shift_reg[4] [2]), .B (\shift_reg[4]
       [0]), .Y (n_1868));
  ADDFHX1LVT g7955(.A (\prod_reg[0] [4]), .B (\prod_reg[1] [4]), .CI
       (\prod_reg[7] [4]), .CO (n_1881), .S (n_1882));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_3__7956(.A
       (n_1677), .B (n_1882), .CI (csa_tree_ADD_TC_OP_12_groupi_n_230),
       .CO (n_1883), .S (n_1884));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_0__7957(.A
       (\prod_reg[0] [5]), .B (\prod_reg[4] [5]), .CI (\prod_reg[3]
       [5]), .CO (n_1885), .S (n_1886));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_3__7958(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_231), .B (n_1881), .CI (n_1886),
       .CO (n_1887), .S (n_1888));
  ADDFHX2LVT g7959(.A (\shift_reg[6] [1]), .B (\shift_reg[2] [0]), .CI
       (\shift_reg[5] [0]), .CO (n_1889), .S (n_1890));
  XOR3X1LVT g7960(.A (\shift_reg[1] [1]), .B (n_1674), .C (n_1890), .Y
       (n_1891));
  INVXLLVT g7961(.A (n_1890), .Y (n_1892));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_1__7962(.A
       (\prod_reg[7] [5]), .B (\prod_reg[1] [5]), .CI (\prod_reg[2]
       [5]), .CO (n_1106), .S (n_1894));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_1__7963(.A
       (\prod_reg[7] [6]), .B (\prod_reg[1] [6]), .CI (\prod_reg[2]
       [6]), .CO (n_1895), .S (n_1896));
  NOR2X4LVT g7964(.A (n_1115), .B (n_1117), .Y (n_1897));
  ADDHX2LVT g7965(.A (n_1898), .B (n_1224), .CO (n_1899), .S (n_1900));
  XNOR3X1LVT g7966(.A (n_1106), .B (n_1896), .C (n_1897), .Y (n_1898));
  OR2X1LVT g7967(.A (n_1901), .B (n_1224), .Y (n_1902));
  XNOR3X1LVT g421_dup(.A (n_1106), .B (n_1896), .C (n_1897), .Y
       (n_1901));
  CLKXOR2X1LVT g7969(.A (n_1907), .B (n_1909), .Y (n_1910));
  XNOR2X1LVT g7970(.A (n_1709), .B (n_1223), .Y (n_1907));
  NOR2X4LVT g39(.A (n_1725), .B (n_1908), .Y (n_1909));
  NOR2X4LVT g7971(.A (n_1723), .B (n_870), .Y (n_1908));
  NOR2X4LVT g36(.A (n_1401), .B (n_1596), .Y (n_1911));
  CLKINVX6LVT g7972(.A (n_1573), .Y (n_1912));
  NOR2X6LVT g7973(.A (n_1913), .B (n_1914), .Y (n_1915));
  INVX3LVT g37(.A (n_1401), .Y (n_1913));
  CLKINVX4LVT g7974(.A (n_1596), .Y (n_1914));
  NAND2X8LVT g8009(.A (n_1957), .B (n_1958), .Y (n_1959));
  INVX3LVT g8010(.A (n_1912), .Y (n_1957));
  NOR2X6LVT g8011(.A (n_1911), .B (n_1915), .Y (n_1958));
  NOR3X8LVT g8012(.A (n_1912), .B (n_1911), .C (n_1915), .Y (n_1960));
  INVX8LVT fopt8013(.A (n_1967), .Y (n_1965));
  NOR3X6LVT g8018(.A (n_587), .B (n_1447), .C (n_1967), .Y (n_1968));
  NAND2X8LVT g8022(.A (n_923), .B (n_925), .Y (n_1971));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_5__8023(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_179), .B (n_1122), .CI (n_1248),
       .CO (n_1972), .S (n_1973));
  NOR2X8LVT csa_tree_ADD_TC_OP_12_groupi_g6949__8024(.A (n_1974), .B
       (n_879), .Y (n_1975));
  NOR2X6LVT g8025(.A (n_1971), .B (n_1973), .Y (n_1974));
  OR2X6LVT g8026(.A (n_1967), .B (n_1282), .Y (n_1977));
  BUFX12LVT fopt8028(.A (n_1974), .Y (n_1967));
  DFFX4LVT \shift_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5] [3]),
       .Q (\shift_reg[6] [3]), .QN (n_105));
  DFFX4LVT \data_in_reg_reg[3] (.CK (i_clock), .D (i_data[3]), .Q
       (data_in_reg[3]), .QN (n_34));
  DFFX4LVT \prod_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5] [2]),
       .Q (\shift_reg[6] [2]), .QN (n_1637));
  DFFX4LVT \prod_reg_reg[7][3] (.CK (i_clock), .D (n_120), .Q
       (\prod_reg[7] [3]), .QN (n_1639));
  CLKAND2X6LVT g8074(.A (\shift_reg[4] [0]), .B (\shift_reg[3] [0]), .Y
       (n_2023));
  OR2X2LVT g8083(.A (n_1496), .B (n_1755), .Y (n_2032));
  OAI2BB2X4LVT g8090(.A0N (\prod_reg[6] [5]), .A1N (\prod_reg[5] [5]),
       .B0 (n_814), .B1 (n_610), .Y (n_2039));
  AOI2BB2X4LVT g8091(.A0N (n_1645), .A1N (n_1652), .B0 (n_1669), .B1
       (n_1671), .Y (n_2040));
  OAI21X4LVT g8097(.A0 (n_2046), .A1 (n_1656), .B0 (n_1657), .Y
       (n_2047));
  NOR2BX2LVT g8098(.AN (n_1630), .B (n_1633), .Y (n_2046));
  CLKINVX6LVT fopt(.A (n_2052), .Y (n_2051));
  BUFX6LVT fopt8101(.A (n_598), .Y (n_2052));
  CLKBUFX2LVT drc(.A (n_1446), .Y (n_2103));
endmodule

