
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Oct  8 2026 21:41:23 -03 (Oct  9 2026 00:41:23 UTC)

// Verification Directory fv/fir_serial_pipe 

module fir_serial_pipe(i_data, i_clock, o_data);
  input [7:0] i_data;
  input i_clock;
  output [18:0] o_data;
  wire [7:0] i_data;
  wire i_clock;
  wire [18:0] o_data;
  wire [7:0] data_in_reg;
  wire [7:0] \shift_reg[0] ;
  wire [15:0] \prod_reg[0] ;
  wire [7:0] \shift_reg[1] ;
  wire [15:0] \prod_reg[1] ;
  wire [7:0] \shift_reg[2] ;
  wire [15:0] \prod_reg[2] ;
  wire [7:0] \shift_reg[3] ;
  wire [15:0] \prod_reg[3] ;
  wire [7:0] \shift_reg[4] ;
  wire [15:0] \prod_reg[4] ;
  wire [7:0] \shift_reg[5] ;
  wire [15:0] \prod_reg[5] ;
  wire [7:0] \shift_reg[6] ;
  wire [15:0] \prod_reg[6] ;
  wire [15:0] \prod_reg[7] ;
  wire [15:0] \prod[2] ;
  wire [15:0] \prod[5] ;
  wire [15:0] \prod[3] ;
  wire [15:0] \prod[4] ;
  wire UNCONNECTED, csa_tree_ADD_TC_OP_12_groupi_n_1,
       csa_tree_ADD_TC_OP_12_groupi_n_2,
       csa_tree_ADD_TC_OP_12_groupi_n_3,
       csa_tree_ADD_TC_OP_12_groupi_n_4,
       csa_tree_ADD_TC_OP_12_groupi_n_5,
       csa_tree_ADD_TC_OP_12_groupi_n_7,
       csa_tree_ADD_TC_OP_12_groupi_n_8;
  wire csa_tree_ADD_TC_OP_12_groupi_n_9,
       csa_tree_ADD_TC_OP_12_groupi_n_10,
       csa_tree_ADD_TC_OP_12_groupi_n_11,
       csa_tree_ADD_TC_OP_12_groupi_n_12,
       csa_tree_ADD_TC_OP_12_groupi_n_13,
       csa_tree_ADD_TC_OP_12_groupi_n_14,
       csa_tree_ADD_TC_OP_12_groupi_n_15,
       csa_tree_ADD_TC_OP_12_groupi_n_22;
  wire csa_tree_ADD_TC_OP_12_groupi_n_24,
       csa_tree_ADD_TC_OP_12_groupi_n_26,
       csa_tree_ADD_TC_OP_12_groupi_n_28,
       csa_tree_ADD_TC_OP_12_groupi_n_29,
       csa_tree_ADD_TC_OP_12_groupi_n_30,
       csa_tree_ADD_TC_OP_12_groupi_n_32,
       csa_tree_ADD_TC_OP_12_groupi_n_33,
       csa_tree_ADD_TC_OP_12_groupi_n_34;
  wire csa_tree_ADD_TC_OP_12_groupi_n_36,
       csa_tree_ADD_TC_OP_12_groupi_n_37,
       csa_tree_ADD_TC_OP_12_groupi_n_38,
       csa_tree_ADD_TC_OP_12_groupi_n_41,
       csa_tree_ADD_TC_OP_12_groupi_n_42,
       csa_tree_ADD_TC_OP_12_groupi_n_43,
       csa_tree_ADD_TC_OP_12_groupi_n_44,
       csa_tree_ADD_TC_OP_12_groupi_n_45;
  wire csa_tree_ADD_TC_OP_12_groupi_n_46,
       csa_tree_ADD_TC_OP_12_groupi_n_47,
       csa_tree_ADD_TC_OP_12_groupi_n_48,
       csa_tree_ADD_TC_OP_12_groupi_n_49,
       csa_tree_ADD_TC_OP_12_groupi_n_50,
       csa_tree_ADD_TC_OP_12_groupi_n_51,
       csa_tree_ADD_TC_OP_12_groupi_n_52,
       csa_tree_ADD_TC_OP_12_groupi_n_53;
  wire csa_tree_ADD_TC_OP_12_groupi_n_54,
       csa_tree_ADD_TC_OP_12_groupi_n_55,
       csa_tree_ADD_TC_OP_12_groupi_n_56,
       csa_tree_ADD_TC_OP_12_groupi_n_57,
       csa_tree_ADD_TC_OP_12_groupi_n_58,
       csa_tree_ADD_TC_OP_12_groupi_n_59,
       csa_tree_ADD_TC_OP_12_groupi_n_60,
       csa_tree_ADD_TC_OP_12_groupi_n_61;
  wire csa_tree_ADD_TC_OP_12_groupi_n_62,
       csa_tree_ADD_TC_OP_12_groupi_n_63,
       csa_tree_ADD_TC_OP_12_groupi_n_64,
       csa_tree_ADD_TC_OP_12_groupi_n_65,
       csa_tree_ADD_TC_OP_12_groupi_n_66,
       csa_tree_ADD_TC_OP_12_groupi_n_67,
       csa_tree_ADD_TC_OP_12_groupi_n_68,
       csa_tree_ADD_TC_OP_12_groupi_n_69;
  wire csa_tree_ADD_TC_OP_12_groupi_n_70,
       csa_tree_ADD_TC_OP_12_groupi_n_71,
       csa_tree_ADD_TC_OP_12_groupi_n_72,
       csa_tree_ADD_TC_OP_12_groupi_n_75,
       csa_tree_ADD_TC_OP_12_groupi_n_76,
       csa_tree_ADD_TC_OP_12_groupi_n_77,
       csa_tree_ADD_TC_OP_12_groupi_n_78,
       csa_tree_ADD_TC_OP_12_groupi_n_79;
  wire csa_tree_ADD_TC_OP_12_groupi_n_80,
       csa_tree_ADD_TC_OP_12_groupi_n_81,
       csa_tree_ADD_TC_OP_12_groupi_n_82,
       csa_tree_ADD_TC_OP_12_groupi_n_83,
       csa_tree_ADD_TC_OP_12_groupi_n_84,
       csa_tree_ADD_TC_OP_12_groupi_n_85,
       csa_tree_ADD_TC_OP_12_groupi_n_86,
       csa_tree_ADD_TC_OP_12_groupi_n_87;
  wire csa_tree_ADD_TC_OP_12_groupi_n_88,
       csa_tree_ADD_TC_OP_12_groupi_n_89,
       csa_tree_ADD_TC_OP_12_groupi_n_90,
       csa_tree_ADD_TC_OP_12_groupi_n_91,
       csa_tree_ADD_TC_OP_12_groupi_n_92,
       csa_tree_ADD_TC_OP_12_groupi_n_93,
       csa_tree_ADD_TC_OP_12_groupi_n_95,
       csa_tree_ADD_TC_OP_12_groupi_n_96;
  wire csa_tree_ADD_TC_OP_12_groupi_n_98,
       csa_tree_ADD_TC_OP_12_groupi_n_100,
       csa_tree_ADD_TC_OP_12_groupi_n_101,
       csa_tree_ADD_TC_OP_12_groupi_n_103,
       csa_tree_ADD_TC_OP_12_groupi_n_104,
       csa_tree_ADD_TC_OP_12_groupi_n_106,
       csa_tree_ADD_TC_OP_12_groupi_n_107,
       csa_tree_ADD_TC_OP_12_groupi_n_108;
  wire csa_tree_ADD_TC_OP_12_groupi_n_109,
       csa_tree_ADD_TC_OP_12_groupi_n_111,
       csa_tree_ADD_TC_OP_12_groupi_n_112,
       csa_tree_ADD_TC_OP_12_groupi_n_113,
       csa_tree_ADD_TC_OP_12_groupi_n_114,
       csa_tree_ADD_TC_OP_12_groupi_n_115,
       csa_tree_ADD_TC_OP_12_groupi_n_116,
       csa_tree_ADD_TC_OP_12_groupi_n_119;
  wire csa_tree_ADD_TC_OP_12_groupi_n_120,
       csa_tree_ADD_TC_OP_12_groupi_n_121,
       csa_tree_ADD_TC_OP_12_groupi_n_122,
       csa_tree_ADD_TC_OP_12_groupi_n_123,
       csa_tree_ADD_TC_OP_12_groupi_n_124,
       csa_tree_ADD_TC_OP_12_groupi_n_132,
       csa_tree_ADD_TC_OP_12_groupi_n_133,
       csa_tree_ADD_TC_OP_12_groupi_n_134;
  wire csa_tree_ADD_TC_OP_12_groupi_n_135,
       csa_tree_ADD_TC_OP_12_groupi_n_136,
       csa_tree_ADD_TC_OP_12_groupi_n_137,
       csa_tree_ADD_TC_OP_12_groupi_n_138,
       csa_tree_ADD_TC_OP_12_groupi_n_139,
       csa_tree_ADD_TC_OP_12_groupi_n_140,
       csa_tree_ADD_TC_OP_12_groupi_n_141,
       csa_tree_ADD_TC_OP_12_groupi_n_142;
  wire csa_tree_ADD_TC_OP_12_groupi_n_143,
       csa_tree_ADD_TC_OP_12_groupi_n_144,
       csa_tree_ADD_TC_OP_12_groupi_n_145,
       csa_tree_ADD_TC_OP_12_groupi_n_146,
       csa_tree_ADD_TC_OP_12_groupi_n_147,
       csa_tree_ADD_TC_OP_12_groupi_n_148,
       csa_tree_ADD_TC_OP_12_groupi_n_149,
       csa_tree_ADD_TC_OP_12_groupi_n_150;
  wire csa_tree_ADD_TC_OP_12_groupi_n_151,
       csa_tree_ADD_TC_OP_12_groupi_n_152,
       csa_tree_ADD_TC_OP_12_groupi_n_153,
       csa_tree_ADD_TC_OP_12_groupi_n_154,
       csa_tree_ADD_TC_OP_12_groupi_n_155,
       csa_tree_ADD_TC_OP_12_groupi_n_156,
       csa_tree_ADD_TC_OP_12_groupi_n_157,
       csa_tree_ADD_TC_OP_12_groupi_n_158;
  wire csa_tree_ADD_TC_OP_12_groupi_n_159,
       csa_tree_ADD_TC_OP_12_groupi_n_160,
       csa_tree_ADD_TC_OP_12_groupi_n_161,
       csa_tree_ADD_TC_OP_12_groupi_n_162,
       csa_tree_ADD_TC_OP_12_groupi_n_163,
       csa_tree_ADD_TC_OP_12_groupi_n_164,
       csa_tree_ADD_TC_OP_12_groupi_n_165,
       csa_tree_ADD_TC_OP_12_groupi_n_166;
  wire csa_tree_ADD_TC_OP_12_groupi_n_167,
       csa_tree_ADD_TC_OP_12_groupi_n_168,
       csa_tree_ADD_TC_OP_12_groupi_n_169,
       csa_tree_ADD_TC_OP_12_groupi_n_170,
       csa_tree_ADD_TC_OP_12_groupi_n_171,
       csa_tree_ADD_TC_OP_12_groupi_n_172,
       csa_tree_ADD_TC_OP_12_groupi_n_173,
       csa_tree_ADD_TC_OP_12_groupi_n_174;
  wire csa_tree_ADD_TC_OP_12_groupi_n_175,
       csa_tree_ADD_TC_OP_12_groupi_n_176,
       csa_tree_ADD_TC_OP_12_groupi_n_177,
       csa_tree_ADD_TC_OP_12_groupi_n_178,
       csa_tree_ADD_TC_OP_12_groupi_n_179,
       csa_tree_ADD_TC_OP_12_groupi_n_180,
       csa_tree_ADD_TC_OP_12_groupi_n_181,
       csa_tree_ADD_TC_OP_12_groupi_n_182;
  wire csa_tree_ADD_TC_OP_12_groupi_n_183,
       csa_tree_ADD_TC_OP_12_groupi_n_184,
       csa_tree_ADD_TC_OP_12_groupi_n_185,
       csa_tree_ADD_TC_OP_12_groupi_n_186,
       csa_tree_ADD_TC_OP_12_groupi_n_187,
       csa_tree_ADD_TC_OP_12_groupi_n_188,
       csa_tree_ADD_TC_OP_12_groupi_n_189,
       csa_tree_ADD_TC_OP_12_groupi_n_190;
  wire csa_tree_ADD_TC_OP_12_groupi_n_191,
       csa_tree_ADD_TC_OP_12_groupi_n_192,
       csa_tree_ADD_TC_OP_12_groupi_n_193,
       csa_tree_ADD_TC_OP_12_groupi_n_194,
       csa_tree_ADD_TC_OP_12_groupi_n_195,
       csa_tree_ADD_TC_OP_12_groupi_n_196,
       csa_tree_ADD_TC_OP_12_groupi_n_197,
       csa_tree_ADD_TC_OP_12_groupi_n_198;
  wire csa_tree_ADD_TC_OP_12_groupi_n_199,
       csa_tree_ADD_TC_OP_12_groupi_n_200,
       csa_tree_ADD_TC_OP_12_groupi_n_201,
       csa_tree_ADD_TC_OP_12_groupi_n_202,
       csa_tree_ADD_TC_OP_12_groupi_n_203,
       csa_tree_ADD_TC_OP_12_groupi_n_204,
       csa_tree_ADD_TC_OP_12_groupi_n_205,
       csa_tree_ADD_TC_OP_12_groupi_n_206;
  wire csa_tree_ADD_TC_OP_12_groupi_n_207,
       csa_tree_ADD_TC_OP_12_groupi_n_208,
       csa_tree_ADD_TC_OP_12_groupi_n_209,
       csa_tree_ADD_TC_OP_12_groupi_n_210,
       csa_tree_ADD_TC_OP_12_groupi_n_211,
       csa_tree_ADD_TC_OP_12_groupi_n_212,
       csa_tree_ADD_TC_OP_12_groupi_n_213,
       csa_tree_ADD_TC_OP_12_groupi_n_214;
  wire csa_tree_ADD_TC_OP_12_groupi_n_215,
       csa_tree_ADD_TC_OP_12_groupi_n_216,
       csa_tree_ADD_TC_OP_12_groupi_n_217,
       csa_tree_ADD_TC_OP_12_groupi_n_218,
       csa_tree_ADD_TC_OP_12_groupi_n_219,
       csa_tree_ADD_TC_OP_12_groupi_n_220,
       csa_tree_ADD_TC_OP_12_groupi_n_221,
       csa_tree_ADD_TC_OP_12_groupi_n_222;
  wire csa_tree_ADD_TC_OP_12_groupi_n_223,
       csa_tree_ADD_TC_OP_12_groupi_n_224,
       csa_tree_ADD_TC_OP_12_groupi_n_225,
       csa_tree_ADD_TC_OP_12_groupi_n_226,
       csa_tree_ADD_TC_OP_12_groupi_n_227,
       csa_tree_ADD_TC_OP_12_groupi_n_228,
       csa_tree_ADD_TC_OP_12_groupi_n_229,
       csa_tree_ADD_TC_OP_12_groupi_n_230;
  wire csa_tree_ADD_TC_OP_12_groupi_n_231,
       csa_tree_ADD_TC_OP_12_groupi_n_232,
       csa_tree_ADD_TC_OP_12_groupi_n_233,
       csa_tree_ADD_TC_OP_12_groupi_n_234,
       csa_tree_ADD_TC_OP_12_groupi_n_235,
       csa_tree_ADD_TC_OP_12_groupi_n_236,
       csa_tree_ADD_TC_OP_12_groupi_n_237,
       csa_tree_ADD_TC_OP_12_groupi_n_238;
  wire csa_tree_ADD_TC_OP_12_groupi_n_239,
       csa_tree_ADD_TC_OP_12_groupi_n_240,
       csa_tree_ADD_TC_OP_12_groupi_n_241,
       csa_tree_ADD_TC_OP_12_groupi_n_242,
       csa_tree_ADD_TC_OP_12_groupi_n_243,
       csa_tree_ADD_TC_OP_12_groupi_n_244,
       csa_tree_ADD_TC_OP_12_groupi_n_245,
       csa_tree_ADD_TC_OP_12_groupi_n_246;
  wire csa_tree_ADD_TC_OP_12_groupi_n_247,
       csa_tree_ADD_TC_OP_12_groupi_n_248,
       csa_tree_ADD_TC_OP_12_groupi_n_249, n_0, n_1, n_3, n_4, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_163, n_164, n_165, n_166, n_167, n_168;
  wire n_169, n_170, n_171, n_172, n_173, n_174, n_175, n_176;
  wire n_177, n_350, n_351, n_352, n_353, n_355, n_356, n_357;
  wire n_358, n_359, n_360;
  assign o_data[15] = o_data[18];
  assign o_data[16] = o_data[18];
  assign o_data[17] = o_data[18];
  DFFHQX1LVT \data_in_reg_reg[0] (.CK (i_clock), .D (i_data[0]), .Q
       (data_in_reg[0]));
  DFFHQX1LVT \data_in_reg_reg[1] (.CK (i_clock), .D (i_data[1]), .Q
       (data_in_reg[1]));
  DFFHQX1LVT \data_in_reg_reg[2] (.CK (i_clock), .D (i_data[2]), .Q
       (data_in_reg[2]));
  DFFHQX1LVT \data_in_reg_reg[3] (.CK (i_clock), .D (i_data[3]), .Q
       (data_in_reg[3]));
  DFFHQX1LVT \data_in_reg_reg[4] (.CK (i_clock), .D (i_data[4]), .Q
       (data_in_reg[4]));
  DFFHQX1LVT \data_in_reg_reg[5] (.CK (i_clock), .D (i_data[5]), .Q
       (data_in_reg[5]));
  DFFHQX1LVT \data_in_reg_reg[6] (.CK (i_clock), .D (i_data[6]), .Q
       (data_in_reg[6]));
  DFFHQX1LVT \data_in_reg_reg[7] (.CK (i_clock), .D (i_data[7]), .Q
       (data_in_reg[7]));
  DFFHQX1LVT \data_out_reg_reg[0] (.CK (i_clock), .D (n_177), .Q
       (o_data[0]));
  DFFHQX1LVT \data_out_reg_reg[1] (.CK (i_clock), .D (n_176), .Q
       (o_data[1]));
  DFFHQX1LVT \data_out_reg_reg[2] (.CK (i_clock), .D (n_175), .Q
       (o_data[2]));
  DFFHQX1LVT \data_out_reg_reg[3] (.CK (i_clock), .D (n_174), .Q
       (o_data[3]));
  DFFHQX1LVT \data_out_reg_reg[4] (.CK (i_clock), .D (n_173), .Q
       (o_data[4]));
  DFFHQX1LVT \data_out_reg_reg[5] (.CK (i_clock), .D (n_172), .Q
       (o_data[5]));
  DFFHQX1LVT \data_out_reg_reg[6] (.CK (i_clock), .D (n_171), .Q
       (o_data[6]));
  DFFQXLLVT \data_out_reg_reg[7] (.CK (i_clock), .D (n_170), .Q
       (o_data[7]));
  DFFHQX1LVT \data_out_reg_reg[8] (.CK (i_clock), .D (n_169), .Q
       (o_data[8]));
  DFFHQX1LVT \data_out_reg_reg[9] (.CK (i_clock), .D (n_168), .Q
       (o_data[9]));
  DFFHQX1LVT \data_out_reg_reg[10] (.CK (i_clock), .D (n_167), .Q
       (o_data[10]));
  DFFHQX1LVT \data_out_reg_reg[11] (.CK (i_clock), .D (n_166), .Q
       (o_data[11]));
  DFFHQX1LVT \data_out_reg_reg[12] (.CK (i_clock), .D (n_165), .Q
       (o_data[12]));
  DFFHQX1LVT \data_out_reg_reg[13] (.CK (i_clock), .D (n_164), .Q
       (o_data[13]));
  DFFHQX1LVT \data_out_reg_reg[14] (.CK (i_clock), .D (n_163), .Q
       (o_data[14]));
  DFFHQX1LVT \data_out_reg_reg[15] (.CK (i_clock), .D (n_352), .Q
       (o_data[18]));
  DFFHQX1LVT \prod_reg_reg[0][0] (.CK (i_clock), .D (data_in_reg[0]),
       .Q (\shift_reg[0] [0]));
  DFFHQX1LVT \prod_reg_reg[0][3] (.CK (i_clock), .D (n_28), .Q
       (\prod_reg[0] [3]));
  DFFHQX1LVT \prod_reg_reg[0][4] (.CK (i_clock), .D (n_51), .Q
       (\prod_reg[0] [4]));
  DFFHQX1LVT \prod_reg_reg[0][5] (.CK (i_clock), .D (n_69), .Q
       (\prod_reg[0] [5]));
  DFFHQX1LVT \prod_reg_reg[0][6] (.CK (i_clock), .D (n_81), .Q
       (\prod_reg[0] [6]));
  DFFHQX1LVT \prod_reg_reg[0][7] (.CK (i_clock), .D (n_97), .Q
       (\prod_reg[0] [7]));
  DFFHQX1LVT \prod_reg_reg[0][8] (.CK (i_clock), .D (n_113), .Q
       (\prod_reg[0] [8]));
  DFFHQX1LVT \prod_reg_reg[0][9] (.CK (i_clock), .D (n_135), .Q
       (\prod_reg[0] [9]));
  DFFHQX1LVT \prod_reg_reg[1][1] (.CK (i_clock), .D (\shift_reg[0]
       [0]), .Q (\shift_reg[1] [0]));
  DFFHQX1LVT \prod_reg_reg[1][2] (.CK (i_clock), .D (\shift_reg[0]
       [1]), .Q (\shift_reg[1] [1]));
  DFFQX2LVT \prod_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0] [2]),
       .Q (\shift_reg[1] [2]));
  DFFHQX1LVT \prod_reg_reg[1][4] (.CK (i_clock), .D (n_33), .Q
       (\prod_reg[1] [4]));
  DFFHQX1LVT \prod_reg_reg[1][5] (.CK (i_clock), .D (n_62), .Q
       (\prod_reg[1] [5]));
  DFFHQX1LVT \prod_reg_reg[1][6] (.CK (i_clock), .D (n_77), .Q
       (\prod_reg[1] [6]));
  DFFHQX1LVT \prod_reg_reg[1][7] (.CK (i_clock), .D (n_93), .Q
       (\prod_reg[1] [7]));
  DFFHQX1LVT \prod_reg_reg[1][8] (.CK (i_clock), .D (n_109), .Q
       (\prod_reg[1] [8]));
  DFFHQX1LVT \prod_reg_reg[1][9] (.CK (i_clock), .D (n_125), .Q
       (\prod_reg[1] [9]));
  DFFHQX1LVT \prod_reg_reg[1][10] (.CK (i_clock), .D (n_129), .Q
       (\prod_reg[1] [10]));
  DFFQX4LVT \prod_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1] [0]),
       .Q (\shift_reg[2] [0]));
  DFFQX2LVT \prod_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1] [1]),
       .Q (\shift_reg[2] [1]));
  DFFHQX1LVT \prod_reg_reg[2][4] (.CK (i_clock), .D (n_31), .Q
       (\prod_reg[2] [4]));
  DFFHQX1LVT \prod_reg_reg[2][5] (.CK (i_clock), .D (n_60), .Q
       (\prod_reg[2] [5]));
  DFFHQX1LVT \prod_reg_reg[2][6] (.CK (i_clock), .D (n_73), .Q
       (\prod_reg[2] [6]));
  DFFHQX1LVT \prod_reg_reg[2][7] (.CK (i_clock), .D (n_85), .Q
       (\prod_reg[2] [7]));
  DFFHQX1LVT \prod_reg_reg[2][8] (.CK (i_clock), .D (n_103), .Q
       (\prod_reg[2] [8]));
  DFFHQX1LVT \prod_reg_reg[2][9] (.CK (i_clock), .D (n_124), .Q
       (\prod_reg[2] [9]));
  DFFHQX1LVT \prod_reg_reg[2][10] (.CK (i_clock), .D (n_137), .Q
       (\prod_reg[2] [10]));
  DFFHQX1LVT \prod_reg_reg[2][11] (.CK (i_clock), .D (n_136), .Q
       (\prod_reg[2] [11]));
  DFFQX2LVT \prod_reg_reg[3][3] (.CK (i_clock), .D (\shift_reg[2] [0]),
       .Q (\shift_reg[3] [0]));
  DFFHQX1LVT \prod_reg_reg[3][4] (.CK (i_clock), .D (n_19), .Q
       (\prod_reg[3] [4]));
  DFFHQX1LVT \prod_reg_reg[3][5] (.CK (i_clock), .D (n_45), .Q
       (\prod_reg[3] [5]));
  DFFHQX1LVT \prod_reg_reg[3][6] (.CK (i_clock), .D (n_0), .Q
       (\prod_reg[3] [6]));
  DFFHQX1LVT \prod_reg_reg[3][7] (.CK (i_clock), .D (n_75), .Q
       (\prod_reg[3] [7]));
  DFFHQX1LVT \prod_reg_reg[3][8] (.CK (i_clock), .D (n_91), .Q
       (\prod_reg[3] [8]));
  DFFHQX1LVT \prod_reg_reg[3][9] (.CK (i_clock), .D (n_105), .Q
       (\prod_reg[3] [9]));
  DFFHQX1LVT \prod_reg_reg[3][10] (.CK (i_clock), .D (n_120), .Q
       (\prod_reg[3] [10]));
  DFFHQX1LVT \prod_reg_reg[3][11] (.CK (i_clock), .D (n_141), .Q
       (\prod_reg[3] [11]));
  DFFHQX1LVT \prod_reg_reg[3][12] (.CK (i_clock), .D (n_146), .Q
       (\prod_reg[3] [12]));
  DFFHQX1LVT \prod_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3]
       [0]), .Q (\shift_reg[4] [0]));
  DFFHQX1LVT \prod_reg_reg[4][4] (.CK (i_clock), .D (n_27), .Q
       (\prod_reg[4] [4]));
  DFFHQX1LVT \prod_reg_reg[4][5] (.CK (i_clock), .D (n_49), .Q
       (\prod_reg[4] [5]));
  DFFHQX1LVT \prod_reg_reg[4][6] (.CK (i_clock), .D (n_1), .Q
       (\prod_reg[4] [6]));
  DFFHQX1LVT \prod_reg_reg[4][7] (.CK (i_clock), .D (n_79), .Q
       (\prod_reg[4] [7]));
  DFFHQX1LVT \prod_reg_reg[4][8] (.CK (i_clock), .D (n_95), .Q
       (\prod_reg[4] [8]));
  DFFHQX1LVT \prod_reg_reg[4][9] (.CK (i_clock), .D (n_111), .Q
       (\prod_reg[4] [9]));
  DFFHQX1LVT \prod_reg_reg[4][10] (.CK (i_clock), .D (n_128), .Q
       (\prod_reg[4] [10]));
  DFFHQX1LVT \prod_reg_reg[4][12] (.CK (i_clock), .D (n_150), .Q
       (\prod_reg[4] [12]));
  DFFQX2LVT \prod_reg_reg[5][2] (.CK (i_clock), .D (\shift_reg[4] [0]),
       .Q (\shift_reg[5] [0]));
  DFFHQX1LVT \prod_reg_reg[5][4] (.CK (i_clock), .D (n_44), .Q
       (\prod_reg[5] [4]));
  DFFHQX1LVT \prod_reg_reg[5][5] (.CK (i_clock), .D (n_71), .Q
       (\prod_reg[5] [5]));
  DFFHQX1LVT \prod_reg_reg[5][6] (.CK (i_clock), .D (n_87), .Q
       (\prod_reg[5] [6]));
  DFFHQX1LVT \prod_reg_reg[5][7] (.CK (i_clock), .D (n_101), .Q
       (\prod_reg[5] [7]));
  DFFHQX1LVT \prod_reg_reg[5][8] (.CK (i_clock), .D (n_118), .Q
       (\prod_reg[5] [8]));
  DFFHQX1LVT \prod_reg_reg[5][9] (.CK (i_clock), .D (n_143), .Q
       (\prod_reg[5] [9]));
  DFFHQX1LVT \prod_reg_reg[5][10] (.CK (i_clock), .D (n_154), .Q
       (\prod_reg[5] [10]));
  DFFHQX1LVT \prod_reg_reg[5][11] (.CK (i_clock), .D (n_153), .Q
       (\prod_reg[5] [11]));
  DFFQX2LVT \prod_reg_reg[6][1] (.CK (i_clock), .D (\shift_reg[5] [0]),
       .Q (\shift_reg[6] [0]));
  DFFHQX1LVT \prod_reg_reg[6][4] (.CK (i_clock), .D (n_65), .Q
       (\prod_reg[6] [4]));
  DFFHQX1LVT \prod_reg_reg[6][5] (.CK (i_clock), .D (n_83), .Q
       (\prod_reg[6] [5]));
  DFFHQX1LVT \prod_reg_reg[6][6] (.CK (i_clock), .D (n_99), .Q
       (\prod_reg[6] [6]));
  DFFHQX1LVT \prod_reg_reg[6][7] (.CK (i_clock), .D (n_115), .Q
       (\prod_reg[6] [7]));
  DFFHQX1LVT \prod_reg_reg[6][8] (.CK (i_clock), .D (n_134), .Q
       (\prod_reg[6] [8]));
  DFFHQX1LVT \prod_reg_reg[6][9] (.CK (i_clock), .D (n_148), .Q
       (\prod_reg[6] [9]));
  DFFHQX1LVT \prod_reg_reg[6][10] (.CK (i_clock), .D (n_158), .Q
       (\prod_reg[6] [10]));
  DFFHQX1LVT \prod_reg_reg[7][0] (.CK (i_clock), .D (\shift_reg[6]
       [0]), .Q (\prod_reg[7] [0]));
  DFFHQX1LVT \prod_reg_reg[7][1] (.CK (i_clock), .D (\shift_reg[6]
       [1]), .Q (\prod_reg[7] [1]));
  DFFHQX1LVT \prod_reg_reg[7][2] (.CK (i_clock), .D (\shift_reg[6]
       [2]), .Q (\prod_reg[7] [2]));
  DFFHQX1LVT \prod_reg_reg[7][3] (.CK (i_clock), .D (n_67), .Q
       (\prod_reg[7] [3]));
  DFFHQX1LVT \prod_reg_reg[7][4] (.CK (i_clock), .D (n_89), .Q
       (\prod_reg[7] [4]));
  DFFHQX1LVT \prod_reg_reg[7][5] (.CK (i_clock), .D (n_107), .Q
       (\prod_reg[7] [5]));
  DFFHQX1LVT \prod_reg_reg[7][6] (.CK (i_clock), .D (n_122), .Q
       (\prod_reg[7] [6]));
  DFFHQX1LVT \prod_reg_reg[7][7] (.CK (i_clock), .D (n_139), .Q
       (\prod_reg[7] [7]));
  DFFHQX1LVT \prod_reg_reg[7][8] (.CK (i_clock), .D (n_152), .Q
       (\prod_reg[7] [8]));
  DFFHQX1LVT \prod_reg_reg[7][9] (.CK (i_clock), .D (n_161), .Q
       (\prod_reg[7] [9]));
  DFFHQX1LVT \shift_reg_reg[0][3] (.CK (i_clock), .D (data_in_reg[3]),
       .Q (\shift_reg[0] [3]));
  DFFHQX1LVT \shift_reg_reg[0][4] (.CK (i_clock), .D (data_in_reg[4]),
       .Q (\shift_reg[0] [4]));
  DFFHQX1LVT \shift_reg_reg[0][5] (.CK (i_clock), .D (data_in_reg[5]),
       .Q (\shift_reg[0] [5]));
  DFFHQX1LVT \shift_reg_reg[0][6] (.CK (i_clock), .D (data_in_reg[6]),
       .Q (\shift_reg[0] [6]));
  DFFHQX1LVT \shift_reg_reg[0][7] (.CK (i_clock), .D (data_in_reg[7]),
       .Q (\shift_reg[0] [7]));
  DFFHQX1LVT \shift_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [3]), .Q (\shift_reg[1] [3]));
  DFFHQX1LVT \shift_reg_reg[1][4] (.CK (i_clock), .D (\shift_reg[0]
       [4]), .Q (\shift_reg[1] [4]));
  DFFHQX1LVT \shift_reg_reg[1][5] (.CK (i_clock), .D (\shift_reg[0]
       [5]), .Q (\shift_reg[1] [5]));
  DFFHQX1LVT \shift_reg_reg[1][6] (.CK (i_clock), .D (\shift_reg[0]
       [6]), .Q (\shift_reg[1] [6]));
  DFFHQX1LVT \shift_reg_reg[1][7] (.CK (i_clock), .D (\shift_reg[0]
       [7]), .Q (\prod[2] [13]));
  DFFHQX1LVT \shift_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1]
       [2]), .Q (\shift_reg[2] [2]));
  DFFHQX1LVT \shift_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1]
       [3]), .Q (\shift_reg[2] [3]));
  DFFHQX1LVT \shift_reg_reg[2][4] (.CK (i_clock), .D (\shift_reg[1]
       [4]), .Q (\shift_reg[2] [4]));
  DFFHQX1LVT \shift_reg_reg[2][5] (.CK (i_clock), .D (\shift_reg[1]
       [5]), .Q (\shift_reg[2] [5]));
  DFFHQX1LVT \shift_reg_reg[2][6] (.CK (i_clock), .D (\shift_reg[1]
       [6]), .Q (\shift_reg[2] [6]));
  DFFQX2LVT \shift_reg_reg[3][1] (.CK (i_clock), .D (\shift_reg[2]
       [1]), .Q (\shift_reg[3] [1]));
  DFFHQX1LVT \shift_reg_reg[3][2] (.CK (i_clock), .D (\shift_reg[2]
       [2]), .Q (\shift_reg[3] [2]));
  DFFHQX1LVT \shift_reg_reg[3][3] (.CK (i_clock), .D (\shift_reg[2]
       [3]), .Q (\shift_reg[3] [3]));
  DFFHQX1LVT \shift_reg_reg[3][4] (.CK (i_clock), .D (\shift_reg[2]
       [4]), .Q (\shift_reg[3] [4]));
  DFFHQX1LVT \shift_reg_reg[3][5] (.CK (i_clock), .D (\shift_reg[2]
       [5]), .Q (\shift_reg[3] [5]));
  DFFHQX1LVT \shift_reg_reg[3][6] (.CK (i_clock), .D (\shift_reg[2]
       [6]), .Q (\shift_reg[3] [6]));
  DFFHQX1LVT \shift_reg_reg[4][1] (.CK (i_clock), .D (\shift_reg[3]
       [1]), .Q (\shift_reg[4] [1]));
  DFFHQX1LVT \shift_reg_reg[4][2] (.CK (i_clock), .D (\shift_reg[3]
       [2]), .Q (\shift_reg[4] [2]));
  DFFHQX1LVT \shift_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3]
       [3]), .Q (\shift_reg[4] [3]));
  DFFHQX1LVT \shift_reg_reg[4][4] (.CK (i_clock), .D (\shift_reg[3]
       [4]), .Q (\shift_reg[4] [4]));
  DFFHQX1LVT \shift_reg_reg[4][5] (.CK (i_clock), .D (\shift_reg[3]
       [5]), .Q (\shift_reg[4] [5]));
  DFFHQX1LVT \shift_reg_reg[4][6] (.CK (i_clock), .D (\shift_reg[3]
       [6]), .Q (\shift_reg[4] [6]));
  DFFHQX1LVT \shift_reg_reg[5][2] (.CK (i_clock), .D (\shift_reg[4]
       [2]), .Q (\shift_reg[5] [2]));
  DFFHQX1LVT \shift_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4]
       [3]), .Q (\shift_reg[5] [3]));
  DFFHQX1LVT \shift_reg_reg[5][4] (.CK (i_clock), .D (\shift_reg[4]
       [4]), .Q (\shift_reg[5] [4]));
  DFFHQX1LVT \shift_reg_reg[5][5] (.CK (i_clock), .D (\shift_reg[4]
       [5]), .Q (\shift_reg[5] [5]));
  DFFHQX1LVT \shift_reg_reg[5][6] (.CK (i_clock), .D (\shift_reg[4]
       [6]), .Q (\shift_reg[5] [6]));
  DFFRX1LVT \shift_reg_reg[6][3] (.RN (1'b1), .CK (i_clock), .D
       (\shift_reg[5] [3]), .Q (UNCONNECTED), .QN (\shift_reg[6] [3]));
  DFFHQX1LVT \shift_reg_reg[6][4] (.CK (i_clock), .D (\shift_reg[5]
       [4]), .Q (\shift_reg[6] [4]));
  DFFHQX1LVT \shift_reg_reg[6][5] (.CK (i_clock), .D (\shift_reg[5]
       [5]), .Q (\shift_reg[6] [5]));
  DFFHQX1LVT \shift_reg_reg[6][6] (.CK (i_clock), .D (\shift_reg[5]
       [6]), .Q (\shift_reg[6] [6]));
  DFFHQX1LVT \shift_reg_reg[6][7] (.CK (i_clock), .D (\prod_reg[5]
       [12]), .Q (\shift_reg[6] [7]));
  INVX1LVT g5250(.A (n_160), .Y (n_161));
  ADDFX1LVT g5251__2398(.A (\shift_reg[6] [6]), .B (n_14), .CI (n_155),
       .CO (n_159), .S (n_160));
  INVX1LVT g5254(.A (n_157), .Y (n_158));
  ADDFX1LVT g5255__5107(.A (\shift_reg[5] [6]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_13), .CI (n_149), .CO (n_156),
       .S (n_157));
  INVX1LVT g5260(.A (n_151), .Y (n_155));
  ADDFX1LVT g5261__6260(.A (\shift_reg[4] [6]), .B (\prod[5] [13]), .CI
       (n_142), .CO (n_153), .S (n_154));
  ADDFX1LVT g5262__4319(.A (\shift_reg[6] [7]), .B (n_63), .CI (n_138),
       .CO (n_151), .S (n_152));
  CLKXOR2X1LVT g5265__8428(.A (n_47), .B (n_144), .Y (n_150));
  INVX1LVT g5266(.A (n_147), .Y (n_149));
  ADDFX1LVT g5267__5526(.A (n_52), .B (\prod_reg[5] [12]), .CI (n_133),
       .CO (n_147), .S (n_148));
  CLKXOR2X1LVT g5269__6783(.A (n_41), .B (n_140), .Y (n_146));
  ADDFX1LVT g5270__3680(.A (\shift_reg[3] [5]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_15), .CI (n_127), .CO (n_144),
       .S (n_145));
  ADDFX1LVT g5276__1617(.A (\shift_reg[4] [5]), .B (\prod[5] [13]), .CI
       (n_117), .CO (n_142), .S (n_143));
  ADDFX1LVT g5277__2802(.A (\shift_reg[2] [5]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_9), .CI (n_119), .CO (n_140), .S
       (n_141));
  ADDFX1LVT g5278__1705(.A (\shift_reg[6] [7]), .B (n_58), .CI (n_121),
       .CO (n_138), .S (n_139));
  ADDFX1LVT g5279__5122(.A (\prod[2] [13]), .B (\shift_reg[1] [6]), .CI
       (n_123), .CO (n_136), .S (n_137));
  INVX1LVT g5285(.A (n_132), .Y (n_135));
  ADDFX1LVT g5286__8246(.A (n_53), .B (\prod_reg[5] [12]), .CI (n_114),
       .CO (n_133), .S (n_134));
  ADDFX1LVT g5287__7098(.A (data_in_reg[6]), .B (n_10), .CI (n_116),
       .CO (n_131), .S (n_132));
  AOI21X1LVT g5289__6131(.A0 (n_25), .A1 (n_126), .B0 (\shift_reg[0]
       [7]), .Y (n_130));
  CLKXOR2X1LVT g5290__1881(.A (n_32), .B (n_126), .Y (n_129));
  ADDFX1LVT g5291__5115(.A (\shift_reg[3] [4]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_15), .CI (n_110), .CO (n_127),
       .S (n_128));
  ADDFX1LVT g5297__7482(.A (\shift_reg[0] [7]), .B (n_21), .CI (n_108),
       .CO (n_126), .S (n_125));
  ADDFX1LVT g5298__4733(.A (\prod[2] [13]), .B (\shift_reg[1] [5]), .CI
       (n_102), .CO (n_123), .S (n_124));
  ADDFX1LVT g5299__6161(.A (\shift_reg[6] [6]), .B (\shift_reg[6] [3]),
       .CI (n_106), .CO (n_121), .S (n_122));
  ADDFX1LVT g5300__9315(.A (\shift_reg[2] [4]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_9), .CI (n_104), .CO (n_119), .S
       (n_120));
  ADDFX1LVT g5301__9945(.A (\shift_reg[4] [6]), .B (\shift_reg[4] [4]),
       .CI (n_100), .CO (n_117), .S (n_118));
  INVX1LVT g5304(.A (n_112), .Y (n_116));
  ADDFX1LVT g5305__2883(.A (\shift_reg[5] [6]), .B (n_54), .CI (n_98),
       .CO (n_114), .S (n_115));
  ADDFX1LVT g5306__2346(.A (data_in_reg[7]), .B (n_11), .CI (n_96), .CO
       (n_112), .S (n_113));
  ADDFX1LVT g5308__1666(.A (\shift_reg[3] [3]), .B (n_40), .CI (n_94),
       .CO (n_110), .S (n_111));
  ADDFX1LVT g5314__7410(.A (\shift_reg[0] [7]), .B (n_22), .CI (n_92),
       .CO (n_108), .S (n_109));
  ADDFX1LVT g5315__6417(.A (\shift_reg[6] [5]), .B (n_3), .CI (n_88),
       .CO (n_106), .S (n_107));
  ADDFX1LVT g5316__5477(.A (\shift_reg[2] [3]), .B (n_34), .CI (n_90),
       .CO (n_104), .S (n_105));
  ADDFX1LVT g5317__2398(.A (\shift_reg[1] [6]), .B (\shift_reg[1] [4]),
       .CI (n_84), .CO (n_102), .S (n_103));
  ADDFX1LVT g5318__5107(.A (\shift_reg[4] [5]), .B (\shift_reg[4] [3]),
       .CI (n_86), .CO (n_100), .S (n_101));
  ADDFX1LVT g5321__6260(.A (\shift_reg[5] [5]), .B (n_37), .CI (n_82),
       .CO (n_98), .S (n_99));
  ADDFX1LVT g5322__4319(.A (data_in_reg[7]), .B (n_15), .CI (n_80), .CO
       (n_96), .S (n_97));
  ADDFX1LVT g5324__8428(.A (\shift_reg[3] [2]), .B (n_39), .CI (n_78),
       .CO (n_94), .S (n_95));
  ADDFX1LVT g5330__5526(.A (\shift_reg[0] [6]), .B (n_20), .CI (n_76),
       .CO (n_92), .S (n_93));
  ADDFX1LVT g5331__6783(.A (\shift_reg[2] [2]), .B (n_36), .CI (n_74),
       .CO (n_90), .S (n_91));
  ADDFX1LVT g5332__3680(.A (\shift_reg[6] [4]), .B (n_8), .CI (n_66),
       .CO (n_88), .S (n_89));
  ADDFX1LVT g5333__1617(.A (\shift_reg[4] [2]), .B (\shift_reg[4] [4]),
       .CI (n_70), .CO (n_86), .S (n_87));
  ADDFX1LVT g5334__2802(.A (\shift_reg[1] [5]), .B (\shift_reg[1] [3]),
       .CI (n_72), .CO (n_84), .S (n_85));
  ADDFX1LVT g5337__1705(.A (\shift_reg[5] [4]), .B (n_4), .CI (n_57),
       .CO (n_82), .S (n_83));
  ADDFX1LVT g5338__5122(.A (data_in_reg[6]), .B (n_12), .CI (n_68), .CO
       (n_80), .S (n_81));
  ADDFX1LVT g5340__8246(.A (\shift_reg[3] [1]), .B (n_38), .CI (n_64),
       .CO (n_78), .S (n_79));
  ADDFX1LVT g5346__7098(.A (\shift_reg[0] [5]), .B (n_9), .CI (n_61),
       .CO (n_76), .S (n_77));
  ADDFX1LVT g5347__6131(.A (n_35), .B (\shift_reg[2] [1]), .CI (n_56),
       .CO (n_74), .S (n_75));
  ADDFX1LVT g5348__1881(.A (\shift_reg[1] [4]), .B (\shift_reg[1] [2]),
       .CI (n_59), .CO (n_72), .S (n_73));
  ADDFX1LVT g5349__5115(.A (\shift_reg[4] [1]), .B (\shift_reg[4] [3]),
       .CI (n_43), .CO (n_70), .S (n_71));
  ADDFX1LVT g5352__7482(.A (data_in_reg[5]), .B (n_18), .CI (n_50), .CO
       (n_68), .S (n_69));
  OAI21X1LVT g5354__4733(.A0 (\shift_reg[6] [3]), .A1 (\shift_reg[6]
       [0]), .B0 (n_66), .Y (n_67));
  OAI21X1LVT g5358__6161(.A0 (n_54), .A1 (\shift_reg[5] [0]), .B0
       (n_57), .Y (n_65));
  AOI2BB1X1LVT g5360__9315(.A0N (\shift_reg[3] [0]), .A1N (n_55), .B0
       (\shift_reg[3] [3]), .Y (n_64));
  NAND2X1LVT g5361__9945(.A (\shift_reg[6] [3]), .B (\shift_reg[6]
       [0]), .Y (n_66));
  INVX1LVT g5362(.A (\shift_reg[6] [5]), .Y (n_63));
  ADDFX1LVT g5363__2883(.A (\shift_reg[0] [4]), .B (n_7), .CI (n_29),
       .CO (n_61), .S (n_62));
  ADDFX1LVT g5364__2346(.A (\shift_reg[1] [3]), .B (\shift_reg[1] [1]),
       .CI (n_30), .CO (n_59), .S (n_60));
  INVX1LVT g5369(.A (\shift_reg[6] [4]), .Y (n_58));
  AOI2BB1X1LVT g5372__1666(.A0N (\shift_reg[2] [0]), .A1N (n_46), .B0
       (\shift_reg[2] [3]), .Y (n_56));
  NAND2X2LVT g5374__7410(.A (n_54), .B (\shift_reg[5] [0]), .Y (n_57));
  INVX1LVT g5376(.A (\shift_reg[5] [3]), .Y (n_54));
  INVX1LVT g5377(.A (\shift_reg[5] [4]), .Y (n_53));
  INVX1LVT g5378(.A (\shift_reg[5] [5]), .Y (n_52));
  ADDFX1LVT g5379__6417(.A (data_in_reg[4]), .B (n_17), .CI (n_23), .CO
       (n_50), .S (n_51));
  ADDHX1LVT g5380__5477(.A (n_26), .B (n_24), .CO (n_55), .S (n_49));
  XNOR2X1LVT g5386__2398(.A (\shift_reg[3] [3]), .B (\shift_reg[3]
       [0]), .Y (n_48));
  XNOR2X1LVT g5387__5107(.A (n_40), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_15), .Y (n_47));
  ADDHX1LVT g5390__6260(.A (n_16), .B (n_13), .CO (n_46), .S (n_45));
  ADDHX1LVT g5391__4319(.A (\shift_reg[4] [2]), .B (\shift_reg[4] [0]),
       .CO (n_43), .S (n_44));
  XNOR2X1LVT g5395__8428(.A (\shift_reg[2] [3]), .B (\shift_reg[2]
       [0]), .Y (n_42));
  XNOR2X1LVT g5396__5526(.A (n_34), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_9), .Y (n_41));
  INVX1 g5399(.A (\shift_reg[3] [6]), .Y (n_40));
  INVX1LVT g5403(.A (\shift_reg[3] [5]), .Y (n_39));
  INVX1LVT g5404(.A (\shift_reg[3] [4]), .Y (n_38));
  INVX1LVT g5409(.A (\shift_reg[5] [2]), .Y (n_37));
  INVX1LVT g5410(.A (\shift_reg[2] [5]), .Y (n_36));
  INVX1LVT g5411(.A (\shift_reg[2] [4]), .Y (n_35));
  INVX1 g5417(.A (\shift_reg[2] [6]), .Y (n_34));
  OAI21X1LVT g5418__6783(.A0 (n_20), .A1 (\shift_reg[0] [0]), .B0
       (n_29), .Y (n_33));
  XNOR2X1LVT g5419__3680(.A (\shift_reg[0] [6]), .B (\shift_reg[0]
       [7]), .Y (n_32));
  ADDHX1LVT g5423__1617(.A (\shift_reg[1] [0]), .B (\shift_reg[1] [2]),
       .CO (n_30), .S (n_31));
  OAI21X1LVT g5429__2802(.A0 (data_in_reg[0]), .A1 (n_12), .B0 (n_23),
       .Y (n_28));
  AOI21X1LVT g5430__1705(.A0 (\shift_reg[3] [1]), .A1 (\shift_reg[3]
       [0]), .B0 (n_24), .Y (n_27));
  NAND2X1LVT g5431__5122(.A (n_20), .B (\shift_reg[0] [0]), .Y (n_29));
  INVX1LVT g5434(.A (\shift_reg[3] [2]), .Y (n_26));
  INVX1LVT g5435(.A (\shift_reg[0] [6]), .Y (n_25));
  INVX1LVT g5442(.A (\shift_reg[0] [4]), .Y (n_22));
  INVX1LVT g5443(.A (\shift_reg[0] [5]), .Y (n_21));
  INVX1 g5444(.A (\shift_reg[0] [3]), .Y (n_20));
  AOI21X1LVT g5445__8246(.A0 (\shift_reg[2] [1]), .A1 (\shift_reg[2]
       [0]), .B0 (n_13), .Y (n_19));
  NOR2X2LVT g5446__7098(.A (\shift_reg[3] [1]), .B (\shift_reg[3] [0]),
       .Y (n_24));
  NAND2X2LVT g5448__6131(.A (data_in_reg[0]), .B (n_12), .Y (n_23));
  INVX1LVT g5452(.A (data_in_reg[2]), .Y (n_18));
  INVX1LVT g5453(.A (data_in_reg[1]), .Y (n_17));
  INVX1LVT g5454(.A (\shift_reg[2] [2]), .Y (n_16));
  INVX1LVT g5455(.A (data_in_reg[4]), .Y (n_15));
  INVX1LVT g5456(.A (\shift_reg[6] [7]), .Y (n_14));
  INVX1LVT g5479(.A (data_in_reg[3]), .Y (n_12));
  INVX1LVT g5480(.A (data_in_reg[5]), .Y (n_11));
  INVX1LVT g5481(.A (data_in_reg[7]), .Y (n_10));
  NOR2X2LVT g5489__1881(.A (\shift_reg[2] [1]), .B (\shift_reg[2] [0]),
       .Y (n_13));
  DFFX1LVT \prod_reg_reg[0][1] (.CK (i_clock), .D (data_in_reg[1]), .Q
       (\shift_reg[0] [1]), .QN (n_7));
  DFFX1LVT \prod_reg_reg[2][12] (.CK (i_clock), .D (\prod[2] [13]), .Q
       (\prod[3] [14]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_9));
  DFFX1 \prod_reg_reg[3][13] (.CK (i_clock), .D (\prod[3] [14]), .Q
       (\prod[4] [14]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_15));
  DFFX2LVT \prod_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4] [1]),
       .Q (\shift_reg[5] [1]), .QN (n_4));
  DFFX1LVT \prod_reg_reg[5][12] (.CK (i_clock), .D (\prod[5] [13]), .Q
       (\prod_reg[5] [12]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_13));
  DFFX1LVT \prod_reg_reg[6][2] (.CK (i_clock), .D (\shift_reg[5] [1]),
       .Q (\shift_reg[6] [1]), .QN (n_8));
  DFFX1LVT \prod_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5] [2]),
       .Q (\shift_reg[6] [2]), .QN (n_3));
  CLKXOR2X1LVT g2__5115(.A (n_48), .B (n_55), .Y (n_1));
  CLKXOR2X1LVT g5532__7482(.A (n_42), .B (n_46), .Y (n_0));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_001_0__4733(.A
       (\shift_reg[1] [0]), .B (\prod_reg[7] [1]), .CI
       (\shift_reg[6] [0]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_219),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_221));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_002_0__6161(.A
       (\shift_reg[5] [0]), .B (\shift_reg[1] [1]), .CI
       (\shift_reg[2] [0]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_218),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_237));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_002_1__9315(.A
       (\shift_reg[6] [1]), .B (n_355), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_219), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_238), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_222));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_0__9945(.A
       (\prod_reg[0] [3]), .B (\shift_reg[5] [1]), .CI
       (\shift_reg[1] [2]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_217),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_216));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_1__2883(.A
       (\shift_reg[2] [1]), .B (\prod_reg[7] [3]), .CI
       (\shift_reg[6] [2]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_215),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_214));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_2__2346(.A
       (n_356), .B (n_357), .CI (csa_tree_ADD_TC_OP_12_groupi_n_218),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_177), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_176));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_3__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_214), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_216), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_176), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_239), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_223));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_0__7410(.A
       (\prod_reg[0] [4]), .B (\prod_reg[7] [4]), .CI (\prod_reg[1]
       [4]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_213), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_212));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_1__6417(.A
       (\prod_reg[2] [4]), .B (\prod_reg[5] [4]), .CI (\prod_reg[6]
       [4]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_211), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_210));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_2__5477(.A
       (n_358), .B (n_360), .CI (csa_tree_ADD_TC_OP_12_groupi_n_217),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_175), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_174));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_3__2398(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_215), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_212), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_210), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_173), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_172));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_4__5107(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_174), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_177), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_172), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_240), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_224));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_0__6260(.A
       (\prod_reg[4] [5]), .B (\prod_reg[3] [5]), .CI (\prod_reg[0]
       [5]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_209), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_208));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_1__4319(.A
       (\prod_reg[7] [5]), .B (\prod_reg[1] [5]), .CI (\prod_reg[2]
       [5]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_207), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_206));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_2__8428(.A
       (\prod_reg[5] [5]), .B (\prod_reg[6] [5]), .CI (n_359), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_205), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_204));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_3__5526(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_211), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_213), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_208), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_171), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_170));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_4__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_206), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_204), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_175), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_144), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_143));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_5__3680(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_173), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_170), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_143), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_241), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_225));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_0__1617(.A
       (\prod_reg[4] [6]), .B (\prod_reg[3] [6]), .CI (\prod_reg[0]
       [6]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_203), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_202));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_1__2802(.A
       (\prod_reg[2] [6]), .B (\prod_reg[5] [6]), .CI (\prod_reg[7]
       [6]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_201), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_200));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_2__1705(.A
       (\prod_reg[1] [6]), .B (\prod_reg[6] [6]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_209), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_169), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_168));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_3__5122(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_207), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_202), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_200), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_167), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_166));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_4__8246(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_205), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_168), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_166), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_142), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_141));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_5__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_171), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_144), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_141), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_242), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_226));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_0__6131(.A
       (\prod_reg[4] [7]), .B (\prod_reg[3] [7]), .CI (\prod_reg[0]
       [7]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_199), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_198));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_1__1881(.A
       (\prod_reg[2] [7]), .B (\prod_reg[5] [7]), .CI (\prod_reg[7]
       [7]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_197), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_196));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_2__5115(.A
       (\prod_reg[1] [7]), .B (\prod_reg[6] [7]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_203), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_165), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_164));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_3__7482(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_201), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_198), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_196), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_163), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_162));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_4__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_164), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_169), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_162), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_140), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_139));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_5__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_167), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_139), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_142), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_243), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_227));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_0__9315(.A
       (\prod_reg[4] [8]), .B (\prod_reg[3] [8]), .CI (\prod_reg[0]
       [8]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_195), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_194));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_1__9945(.A
       (\prod_reg[7] [8]), .B (\prod_reg[1] [8]), .CI (\prod_reg[2]
       [8]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_193), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_192));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_2__2883(.A
       (\prod_reg[5] [8]), .B (\prod_reg[6] [8]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_199), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_161), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_160));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_3__2346(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_197), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_194), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_192), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_236), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_159));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_4__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_160), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_165), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_163), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_138), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_137));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_5__7410(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_159), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_137), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_140), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_244), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_228));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_0__6417(.A
       (\prod_reg[4] [9]), .B (\prod_reg[3] [9]), .CI (\prod_reg[0]
       [9]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_191), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_190));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_1__5477(.A
       (\prod_reg[7] [9]), .B (\prod_reg[1] [9]), .CI (\prod_reg[2]
       [9]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_189), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_188));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_2__2398(.A
       (\prod_reg[5] [9]), .B (\prod_reg[6] [9]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_195), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_158), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_157));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_3__5107(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_193), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_190), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_188), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_156), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_235));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_4__6260(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_161), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_157), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_236), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_220), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_136));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_5__4319(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_235), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_136), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_138), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_245), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_229));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_0__8428(.A
       (\prod_reg[4] [10]), .B (\prod_reg[3] [10]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_12), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_187), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_186));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_1__5526(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_8), .B (\prod_reg[1] [10]), .CI
       (\prod_reg[2] [10]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_185),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_184));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_2__6783(.A
       (\prod_reg[5] [10]), .B (\prod_reg[6] [10]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_191), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_155), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_154));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_3__3680(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_189), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_186), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_184), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_153), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_152));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_4__1617(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_154), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_158), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_156), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_135), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_134));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_010_5__2802(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_152), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_134), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_220), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_230));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_0__1705(.A
       (\prod_reg[2] [11]), .B (\prod_reg[5] [11]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_11), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_183), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_182));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_1__5122(.A
       (\prod_reg[3] [11]), .B (csa_tree_ADD_TC_OP_12_groupi_n_14), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_7), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_181), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_180));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_2__8246(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_185), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_187), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_182), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_151), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_150));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_3__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_180), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_155), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_153), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_132), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_133));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_4__6131(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_150), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_133), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_135), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_247), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_231));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_0__1881(.A
       (\prod_reg[4] [12]), .B (\prod_reg[3] [12]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_13), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_179), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_178));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_1__5115(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_9), .B (\prod_reg[4] [11]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_183), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_149), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_145));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_2__7482(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_178), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_181), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_145), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_148), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_147));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_3__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_151), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_147), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_132), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_233), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_232));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_0__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_10), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_15), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_179), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_249), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_146));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_1__9315(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_149), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_146), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_148), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_234), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_248));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6944__2883(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_67), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_119), .Y (n_163));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6945__2346(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_84), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_124), .Y (n_165));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6946__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_1), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_120), .Y (n_166));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6947__7410(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_83), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_123), .Y (n_167));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6948__6417(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_82), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_122), .Y (n_168));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6949__5477(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_68), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_121), .Y (n_164));
  NAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6950__2398(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_106), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_116), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_124));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6951__5107(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_77), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_5), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_123));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6952__6260(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_48), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_61), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_122));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6953__4319(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_104), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_112), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_121));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6954__8428(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_96), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .B0 (n_350), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_120));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6955__5526(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_103), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_113), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_119));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6956__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_80), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_111), .Y (n_169));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6957__3680(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_79), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_115), .Y (n_170));
  NAND3X6LVT csa_tree_ADD_TC_OP_12_groupi_g6958__1617(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_57), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_114), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_98), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_116));
  NAND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6959__2802(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_46), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_109), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_115));
  NAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6960__1705(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_109), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_70), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_114));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6961__5122(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_89), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_101), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_90), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_113));
  AOI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6962__8246(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_72), .A1 (n_353), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_41), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_112));
  CLKAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6963__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_108), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_95), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_111));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6964__6131(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_100), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_78), .Y (n_171));
  NAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g6965__1881(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_45), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_100), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_109));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6966__5115(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_100), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_71), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_108));
  AO21X1LVT csa_tree_ADD_TC_OP_12_groupi_g6967__7482(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_49), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_92), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_66), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_107));
  AOI2BB1X4LVT csa_tree_ADD_TC_OP_12_groupi_g6968__4733(.A0N
       (csa_tree_ADD_TC_OP_12_groupi_n_87), .A1N
       (csa_tree_ADD_TC_OP_12_groupi_n_5), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_91), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_106));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6970__9315(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_54), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_98), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_104));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g6971__9945(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_85), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_98), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_103));
  AOI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6973__2346(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_76), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_81), .B0 (n_351), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_101));
  NAND2X8LVT csa_tree_ADD_TC_OP_12_groupi_g6974__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_2), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_88), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_100));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6975__7410(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_36), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_69), .Y (n_172));
  NAND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6978__5477(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_52), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_4), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_96));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6979__2398(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_47), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_51), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_57), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_95));
  AOI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6980__5107(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_59), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_63), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_5));
  CLKAND2X3LVT csa_tree_ADD_TC_OP_12_groupi_g6981__6260(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_4), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_86), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_98));
  OAI21X1LVT csa_tree_ADD_TC_OP_12_groupi_g6983__4319(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_42), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_64), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_92));
  OAI21X2LVT csa_tree_ADD_TC_OP_12_groupi_g6984__8428(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_38), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_3), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_43), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_91));
  OAI21X2LVT csa_tree_ADD_TC_OP_12_groupi_g6985__5526(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_64), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_90));
  NAND3X2LVT csa_tree_ADD_TC_OP_12_groupi_g6986__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_64), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_42), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_43), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_89));
  AOI2BB1X4LVT csa_tree_ADD_TC_OP_12_groupi_g6987__3680(.A0N
       (csa_tree_ADD_TC_OP_12_groupi_n_29), .A1N
       (csa_tree_ADD_TC_OP_12_groupi_n_65), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_50), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_88));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g6988__1617(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_63), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_75), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_93));
  INVX1LVT csa_tree_ADD_TC_OP_12_groupi_g6989(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_86), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_87));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6991__2802(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_53), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_3), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_86));
  NAND2X1 csa_tree_ADD_TC_OP_12_groupi_g6992__1705(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_42), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_54), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_84));
  AND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6994__5122(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_52), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_38), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_83));
  NOR2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g6995__8246(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_59), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_63), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_82));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6996__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_85));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g6997__6131(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_59), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_81));
  NOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g6998__1881(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_48), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_80));
  NOR2X1 csa_tree_ADD_TC_OP_12_groupi_g6999__5115(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_58), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_51), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_79));
  NAND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7000__7482(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_46), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_45), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_78));
  INVX1 csa_tree_ADD_TC_OP_12_groupi_g7001(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_4), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_77));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7003__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_37), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_63), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_76));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7004__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_53), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_60), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_75));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7007__2883(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_3), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_72));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7008__2346(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_44), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_58), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_71));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7009__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_47), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_51), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_70));
  OR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7010__7410(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_65), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_50), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_69));
  NOR2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g7011__6417(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_64), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_68));
  NOR2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g7012__5477(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_49), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_66), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_67));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7013__2398(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_48), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_60), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_4));
  INVX1 csa_tree_ADD_TC_OP_12_groupi_g7015(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_61));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g7016(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_60), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_59));
  INVX3LVT csa_tree_ADD_TC_OP_12_groupi_g7017(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_58), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_57));
  INVX1LVT csa_tree_ADD_TC_OP_12_groupi_g7018(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_54));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g7019(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_53), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_52));
  AND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7020__5107(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_234), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_249), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_66));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7021__6260(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_240), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_225), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_65));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7022__4319(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_248), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_233), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_64));
  AND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7023__8428(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_244), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_229), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_63));
  AND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7024__5526(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_243), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_228), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_62));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7025__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_244), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_229), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_60));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7026__3680(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_242), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_227), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_58));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7027__1617(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_248), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_233), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_56));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7028__2802(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_247), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_232), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_55));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7029__1705(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_245), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_230), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_53));
  INVX1LVT csa_tree_ADD_TC_OP_12_groupi_g7030(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_47), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_46));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g7031(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_44), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_45));
  INVX1LVT csa_tree_ADD_TC_OP_12_groupi_g7033(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_42), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_41));
  CLKINVX4LVT csa_tree_ADD_TC_OP_12_groupi_g7037(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_38), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_37));
  AND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7038__5122(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_242), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_227), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_51));
  AND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7039__8246(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_240), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_225), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_50));
  OR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7040__7098(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_249), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_234), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_49));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7041__6131(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_243), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_228), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_48));
  AND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7042__1881(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_241), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_226), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_47));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7043__5115(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_241), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_226), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_44));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7044__7482(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_231), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_43));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7045__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_247), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_232), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_42));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g7046__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_231), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_3));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7047__9315(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_245), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_230), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_38));
  NAND2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g7049__9945(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_34), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_29), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_36));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g7050__2883(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_32), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_30), .Y (n_173));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g7051__2346(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_28), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_33), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_34));
  INVX3LVT csa_tree_ADD_TC_OP_12_groupi_g7052(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_32), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_33));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_g7053__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_238), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_26), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_223), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_32), .S (n_174));
  NAND2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g7054__7410(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_28), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_29), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_30));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7055__6417(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_239), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_224), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_29));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g7056__5477(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_239), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_224), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_28));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_g7057__2398(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_237), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_222), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_26), .S (n_175));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_g7058__5107(.A
       (\shift_reg[0] [1]), .B (csa_tree_ADD_TC_OP_12_groupi_n_22), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_221), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .S (n_176));
  ADDHX1LVT csa_tree_ADD_TC_OP_12_groupi_g7059__6260(.A
       (\shift_reg[0] [0]), .B (\prod_reg[7] [0]), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_22), .S (n_177));
  NAND2BX4LVT csa_tree_ADD_TC_OP_12_groupi_g2__2802(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_65), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_34), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_2));
  NOR2BX1 csa_tree_ADD_TC_OP_12_groupi_g7078__1705(.AN
       (csa_tree_ADD_TC_OP_12_groupi_n_43), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_3), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_1));
  DFFX1LVT \prod_reg_reg[0][2] (.CK (i_clock), .D (data_in_reg[2]), .Q
       (\shift_reg[0] [2]), .QN (n_9));
  DFFX1LVT \prod_reg_reg[1][11] (.CK (i_clock), .D (n_130), .Q
       (\prod_reg[1] [11]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_14));
  DFFX1LVT \prod_reg_reg[0][10] (.CK (i_clock), .D (n_131), .Q
       (\prod_reg[0] [10]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_12));
  DFFX1LVT \prod_reg_reg[6][11] (.CK (i_clock), .D (n_156), .Q
       (\prod_reg[6] [11]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_11));
  DFFX1LVT \prod_reg_reg[4][13] (.CK (i_clock), .D (\prod[4] [14]), .Q
       (\prod[5] [13]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_10));
  DFFX1LVT \prod_reg_reg[7][10] (.CK (i_clock), .D (n_159), .Q
       (\prod_reg[7] [10]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_8));
  DFFX1 \prod_reg_reg[4][11] (.CK (i_clock), .D (n_145), .Q
       (\prod_reg[4] [11]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_7));
  NOR2BX2LVT g2(.AN (csa_tree_ADD_TC_OP_12_groupi_n_93), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_37), .Y (n_350));
  NAND2BX2LVT g7094(.AN (csa_tree_ADD_TC_OP_12_groupi_n_3), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_52), .Y (n_351));
  AOI31X2LVT g7095(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_85), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_49), .A2
       (csa_tree_ADD_TC_OP_12_groupi_n_124), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_107), .Y (n_352));
  NAND3X4LVT g7096(.A (csa_tree_ADD_TC_OP_12_groupi_n_38), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_43), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_93), .Y (n_353));
  ADDHX1LVT g7098(.A (\shift_reg[0] [2]), .B (\prod_reg[7] [2]), .CO
       (n_356), .S (n_355));
  ADDHX1LVT g7099(.A (\shift_reg[4] [0]), .B (\shift_reg[3] [0]), .CO
       (n_358), .S (n_357));
  ADDHX1LVT g7100(.A (\prod_reg[3] [4]), .B (\prod_reg[4] [4]), .CO
       (n_359), .S (n_360));
endmodule

