
// Generated by Cadence Genus(TM) Synthesis Solution 23.10-p004_1
// Generated on: Oct  8 2026 21:50:52 -03 (Oct  9 2026 00:50:52 UTC)

// Verification Directory fv/fir_serial_pipe 

module fir_serial_pipe(i_data, i_clock, o_data);
  input [7:0] i_data;
  input i_clock;
  output [18:0] o_data;
  wire [7:0] i_data;
  wire i_clock;
  wire [18:0] o_data;
  wire [7:0] data_in_reg;
  wire [7:0] \shift_reg[0] ;
  wire [15:0] \prod_reg[0] ;
  wire [7:0] \shift_reg[1] ;
  wire [15:0] \prod_reg[1] ;
  wire [7:0] \shift_reg[2] ;
  wire [15:0] \prod_reg[2] ;
  wire [15:0] \prod_reg[3] ;
  wire [15:0] \prod_reg[4] ;
  wire [7:0] \shift_reg[4] ;
  wire [7:0] \shift_reg[5] ;
  wire [15:0] \prod_reg[5] ;
  wire [7:0] \shift_reg[6] ;
  wire [15:0] \prod_reg[6] ;
  wire [15:0] \prod_reg[7] ;
  wire [15:0] \prod[2] ;
  wire [7:0] \shift_reg[3] ;
  wire [15:0] \prod[5] ;
  wire [15:0] \prod[3] ;
  wire [15:0] \prod[4] ;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       csa_tree_ADD_TC_OP_12_groupi_n_0,
       csa_tree_ADD_TC_OP_12_groupi_n_2,
       csa_tree_ADD_TC_OP_12_groupi_n_5,
       csa_tree_ADD_TC_OP_12_groupi_n_6;
  wire csa_tree_ADD_TC_OP_12_groupi_n_7,
       csa_tree_ADD_TC_OP_12_groupi_n_8,
       csa_tree_ADD_TC_OP_12_groupi_n_14,
       csa_tree_ADD_TC_OP_12_groupi_n_16,
       csa_tree_ADD_TC_OP_12_groupi_n_17,
       csa_tree_ADD_TC_OP_12_groupi_n_18,
       csa_tree_ADD_TC_OP_12_groupi_n_19,
       csa_tree_ADD_TC_OP_12_groupi_n_21;
  wire csa_tree_ADD_TC_OP_12_groupi_n_22,
       csa_tree_ADD_TC_OP_12_groupi_n_23,
       csa_tree_ADD_TC_OP_12_groupi_n_24,
       csa_tree_ADD_TC_OP_12_groupi_n_29,
       csa_tree_ADD_TC_OP_12_groupi_n_34,
       csa_tree_ADD_TC_OP_12_groupi_n_43,
       csa_tree_ADD_TC_OP_12_groupi_n_48,
       csa_tree_ADD_TC_OP_12_groupi_n_49;
  wire csa_tree_ADD_TC_OP_12_groupi_n_54,
       csa_tree_ADD_TC_OP_12_groupi_n_55,
       csa_tree_ADD_TC_OP_12_groupi_n_56,
       csa_tree_ADD_TC_OP_12_groupi_n_59,
       csa_tree_ADD_TC_OP_12_groupi_n_62,
       csa_tree_ADD_TC_OP_12_groupi_n_65,
       csa_tree_ADD_TC_OP_12_groupi_n_66,
       csa_tree_ADD_TC_OP_12_groupi_n_67;
  wire csa_tree_ADD_TC_OP_12_groupi_n_70,
       csa_tree_ADD_TC_OP_12_groupi_n_73,
       csa_tree_ADD_TC_OP_12_groupi_n_74,
       csa_tree_ADD_TC_OP_12_groupi_n_75,
       csa_tree_ADD_TC_OP_12_groupi_n_76,
       csa_tree_ADD_TC_OP_12_groupi_n_80,
       csa_tree_ADD_TC_OP_12_groupi_n_87,
       csa_tree_ADD_TC_OP_12_groupi_n_95;
  wire csa_tree_ADD_TC_OP_12_groupi_n_96,
       csa_tree_ADD_TC_OP_12_groupi_n_97,
       csa_tree_ADD_TC_OP_12_groupi_n_98,
       csa_tree_ADD_TC_OP_12_groupi_n_100,
       csa_tree_ADD_TC_OP_12_groupi_n_101,
       csa_tree_ADD_TC_OP_12_groupi_n_104,
       csa_tree_ADD_TC_OP_12_groupi_n_105,
       csa_tree_ADD_TC_OP_12_groupi_n_106;
  wire csa_tree_ADD_TC_OP_12_groupi_n_109,
       csa_tree_ADD_TC_OP_12_groupi_n_112,
       csa_tree_ADD_TC_OP_12_groupi_n_116,
       csa_tree_ADD_TC_OP_12_groupi_n_117,
       csa_tree_ADD_TC_OP_12_groupi_n_118,
       csa_tree_ADD_TC_OP_12_groupi_n_119,
       csa_tree_ADD_TC_OP_12_groupi_n_131,
       csa_tree_ADD_TC_OP_12_groupi_n_158;
  wire csa_tree_ADD_TC_OP_12_groupi_n_159,
       csa_tree_ADD_TC_OP_12_groupi_n_160,
       csa_tree_ADD_TC_OP_12_groupi_n_171,
       csa_tree_ADD_TC_OP_12_groupi_n_174,
       csa_tree_ADD_TC_OP_12_groupi_n_175,
       csa_tree_ADD_TC_OP_12_groupi_n_190,
       csa_tree_ADD_TC_OP_12_groupi_n_191,
       csa_tree_ADD_TC_OP_12_groupi_n_192;
  wire csa_tree_ADD_TC_OP_12_groupi_n_193,
       csa_tree_ADD_TC_OP_12_groupi_n_208,
       csa_tree_ADD_TC_OP_12_groupi_n_209,
       csa_tree_ADD_TC_OP_12_groupi_n_212,
       csa_tree_ADD_TC_OP_12_groupi_n_213,
       csa_tree_ADD_TC_OP_12_groupi_n_228,
       csa_tree_ADD_TC_OP_12_groupi_n_229,
       csa_tree_ADD_TC_OP_12_groupi_n_230;
  wire csa_tree_ADD_TC_OP_12_groupi_n_231,
       csa_tree_ADD_TC_OP_12_groupi_n_233,
       csa_tree_ADD_TC_OP_12_groupi_n_244,
       csa_tree_ADD_TC_OP_12_groupi_n_245,
       csa_tree_ADD_TC_OP_12_groupi_n_246,
       csa_tree_ADD_TC_OP_12_groupi_n_248,
       csa_tree_ADD_TC_OP_12_groupi_n_249,
       csa_tree_ADD_TC_OP_12_groupi_n_260;
  wire csa_tree_ADD_TC_OP_12_groupi_n_261, n_0, n_1, n_3, n_4, n_7,
       n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_114, n_115, n_116, n_117, n_118, n_119, n_120, n_121;
  wire n_122, n_123, n_124, n_125, n_126, n_127, n_128, n_129;
  wire n_130, n_131, n_132, n_133, n_134, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151, n_152, n_153;
  wire n_154, n_155, n_156, n_157, n_158, n_159, n_160, n_161;
  wire n_162, n_170, n_171, n_172, n_173, n_174, n_175, n_363;
  wire n_367, n_368, n_374, n_376, n_377, n_378, n_380, n_381;
  wire n_383, n_384, n_385, n_386, n_389, n_390, n_391, n_392;
  wire n_394, n_396, n_399, n_400, n_401, n_407, n_415, n_416;
  wire n_421, n_428, n_430, n_432, n_433, n_436, n_442, n_443;
  wire n_445, n_446, n_447, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_458, n_468, n_473, n_477, n_480;
  wire n_482, n_488, n_489, n_490, n_491, n_492, n_493, n_496;
  wire n_500, n_501, n_502, n_503, n_504, n_505, n_510, n_511;
  wire n_512, n_520, n_521, n_522, n_523, n_526, n_527, n_529;
  wire n_530, n_531, n_532, n_535, n_536, n_537, n_538, n_539;
  wire n_540, n_542, n_543, n_544, n_545, n_548, n_553, n_559;
  wire n_561, n_562, n_563, n_564, n_565, n_566, n_581, n_583;
  wire n_587, n_596, n_598, n_607, n_608, n_609, n_610, n_611;
  wire n_612, n_613, n_616, n_617, n_618, n_619, n_620, n_624;
  wire n_628, n_637, n_640, n_649, n_650, n_651, n_652, n_653;
  wire n_660, n_662, n_663, n_664, n_667, n_674, n_675, n_676;
  wire n_677, n_678, n_679, n_680, n_681, n_683, n_684, n_685;
  wire n_686, n_687, n_688, n_689, n_690, n_691, n_692, n_693;
  wire n_694, n_695, n_696, n_697, n_698, n_699, n_700, n_701;
  wire n_702, n_703, n_704, n_706, n_707, n_708, n_709, n_710;
  wire n_711, n_713, n_715, n_716, n_718, n_739, n_740, n_741;
  wire n_763, n_789, n_790, n_791, n_793, n_796, n_797, n_798;
  wire n_799, n_800, n_801, n_804, n_816, n_817, n_818, n_821;
  wire n_824, n_825, n_849, n_850, n_852, n_871, n_877, n_878;
  wire n_880, n_883, n_885, n_886, n_887, n_890, n_892, n_893;
  wire n_895, n_897, n_898, n_900, n_901, n_902, n_905, n_906;
  wire n_907, n_908, n_909, n_911, n_912, n_913, n_914, n_915;
  wire n_916, n_917, n_918, n_919, n_920, n_921, n_922, n_923;
  wire n_924, n_925, n_926, n_927, n_928, n_930, n_931, n_932;
  wire n_933, n_936, n_937, n_938, n_941, n_948, n_949, n_951;
  wire n_953, n_954, n_955, n_956, n_957, n_958, n_959, n_960;
  wire n_961, n_962, n_964, n_966, n_968, n_969, n_970, n_971;
  wire n_973, n_974, n_975, n_977, n_978, n_979, n_980, n_981;
  wire n_982, n_983, n_984, n_985, n_986, n_987, n_988, n_989;
  wire n_990, n_992, n_993, n_994, n_998, n_999, n_1001, n_1002;
  wire n_1003, n_1004, n_1006, n_1007, n_1008, n_1014, n_1016, n_1018;
  wire n_1019, n_1020, n_1021, n_1022, n_1024, n_1025, n_1026, n_1027;
  wire n_1028, n_1029, n_1031, n_1032, n_1033, n_1036, n_1037, n_1038;
  wire n_1040, n_1041, n_1043, n_1044, n_1045, n_1046, n_1047, n_1048;
  wire n_1051, n_1052, n_1054, n_1058, n_1059, n_1060, n_1063, n_1064;
  wire n_1065, n_1066, n_1067, n_1070, n_1073, n_1074, n_1075, n_1077;
  wire n_1079, n_1080, n_1081, n_1082, n_1083, n_1084, n_1085, n_1086;
  wire n_1087, n_1088, n_1089, n_1090, n_1091, n_1092, n_1093, n_1094;
  wire n_1095, n_1096, n_1097, n_1098, n_1099, n_1100, n_1101, n_1102;
  wire n_1103, n_1104, n_1105, n_1106, n_1107, n_1108, n_1109, n_1110;
  wire n_1112, n_1113, n_1114, n_1115, n_1116, n_1117, n_1118, n_1119;
  assign o_data[15] = o_data[18];
  assign o_data[16] = o_data[18];
  assign o_data[17] = o_data[18];
  DFFQX2LVT \data_in_reg_reg[0] (.CK (i_clock), .D (i_data[0]), .Q
       (data_in_reg[0]));
  DFFHQX1LVT \data_in_reg_reg[2] (.CK (i_clock), .D (i_data[2]), .Q
       (data_in_reg[2]));
  DFFQX4LVT \data_in_reg_reg[3] (.CK (i_clock), .D (i_data[3]), .Q
       (data_in_reg[3]));
  DFFHQX1LVT \data_in_reg_reg[4] (.CK (i_clock), .D (i_data[4]), .Q
       (data_in_reg[4]));
  DFFHQX1LVT \data_in_reg_reg[5] (.CK (i_clock), .D (i_data[5]), .Q
       (data_in_reg[5]));
  DFFHQX1LVT \data_in_reg_reg[6] (.CK (i_clock), .D (i_data[6]), .Q
       (data_in_reg[6]));
  DFFHQX1LVT \data_in_reg_reg[7] (.CK (i_clock), .D (i_data[7]), .Q
       (data_in_reg[7]));
  DFFHQX1LVT \data_out_reg_reg[0] (.CK (i_clock), .D (n_1118), .Q
       (o_data[0]));
  DFFHQX1LVT \data_out_reg_reg[1] (.CK (i_clock), .D (n_527), .Q
       (o_data[1]));
  DFFHQX1LVT \data_out_reg_reg[2] (.CK (i_clock), .D (n_1022), .Q
       (o_data[2]));
  DFFHQX1LVT \data_out_reg_reg[3] (.CK (i_clock), .D (n_175), .Q
       (o_data[3]));
  DFFHQX1LVT \data_out_reg_reg[4] (.CK (i_clock), .D (n_174), .Q
       (o_data[4]));
  DFFHQX1LVT \data_out_reg_reg[5] (.CK (i_clock), .D (n_173), .Q
       (o_data[5]));
  DFFHQX1LVT \data_out_reg_reg[6] (.CK (i_clock), .D (n_172), .Q
       (o_data[6]));
  DFFHQX1LVT \data_out_reg_reg[7] (.CK (i_clock), .D (n_171), .Q
       (o_data[7]));
  DFFHQX1LVT \data_out_reg_reg[8] (.CK (i_clock), .D (n_170), .Q
       (o_data[8]));
  DFFHQX1LVT \data_out_reg_reg[9] (.CK (i_clock), .D (n_653), .Q
       (o_data[9]));
  DFFHQX1LVT \data_out_reg_reg[10] (.CK (i_clock), .D (n_741), .Q
       (o_data[10]));
  DFFHQX1LVT \data_out_reg_reg[11] (.CK (i_clock), .D (n_667), .Q
       (o_data[11]));
  DFFHQX1LVT \data_out_reg_reg[12] (.CK (i_clock), .D (n_955), .Q
       (o_data[12]));
  DFFHQX1LVT \data_out_reg_reg[13] (.CK (i_clock), .D (n_978), .Q
       (o_data[13]));
  DFFHQX1LVT \data_out_reg_reg[14] (.CK (i_clock), .D (n_566), .Q
       (o_data[14]));
  DFFHQX1LVT \data_out_reg_reg[15] (.CK (i_clock), .D (n_958), .Q
       (o_data[18]));
  DFFQX2LVT \prod_reg_reg[0][0] (.CK (i_clock), .D (data_in_reg[0]), .Q
       (\shift_reg[0] [0]));
  DFFQX2LVT \prod_reg_reg[0][3] (.CK (i_clock), .D (n_30), .Q
       (\prod_reg[0] [3]));
  DFFQX2LVT \prod_reg_reg[0][4] (.CK (i_clock), .D (n_55), .Q
       (\prod_reg[0] [4]));
  DFFHQX4LVT \prod_reg_reg[0][5] (.CK (i_clock), .D (n_71), .Q
       (\prod_reg[0] [5]));
  DFFQX2LVT \prod_reg_reg[0][6] (.CK (i_clock), .D (n_83), .Q
       (\prod_reg[0] [6]));
  DFFQX2LVT \prod_reg_reg[0][7] (.CK (i_clock), .D (n_99), .Q
       (\prod_reg[0] [7]));
  DFFQX2LVT \prod_reg_reg[0][8] (.CK (i_clock), .D (n_115), .Q
       (\prod_reg[0] [8]));
  DFFQX2LVT \prod_reg_reg[1][1] (.CK (i_clock), .D (\shift_reg[0] [0]),
       .Q (\shift_reg[1] [0]));
  DFFHQX4LVT \prod_reg_reg[1][2] (.CK (i_clock), .D (\shift_reg[0]
       [1]), .Q (\shift_reg[1] [1]));
  DFFHQX2LVT \prod_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [2]), .Q (\shift_reg[1] [2]));
  DFFHQX4LVT \prod_reg_reg[1][4] (.CK (i_clock), .D (n_34), .Q
       (\prod_reg[1] [4]));
  DFFQX2LVT \prod_reg_reg[1][5] (.CK (i_clock), .D (n_64), .Q
       (\prod_reg[1] [5]));
  DFFQX2LVT \prod_reg_reg[1][6] (.CK (i_clock), .D (n_79), .Q
       (\prod_reg[1] [6]));
  DFFHQX4LVT \prod_reg_reg[1][7] (.CK (i_clock), .D (n_95), .Q
       (\prod_reg[1] [7]));
  DFFQX2LVT \prod_reg_reg[1][8] (.CK (i_clock), .D (n_111), .Q
       (\prod_reg[1] [8]));
  DFFQX2LVT \prod_reg_reg[1][9] (.CK (i_clock), .D (n_127), .Q
       (\prod_reg[1] [9]));
  MDFFHQX4LVT \prod_reg_reg[1][10] (.CK (i_clock), .D0 (n_37), .D1
       (n_38), .S0 (n_128), .Q (\prod_reg[1] [10]));
  DFFHQX8LVT \prod_reg_reg[2][2] (.CK (i_clock), .D (\shift_reg[1]
       [0]), .Q (\shift_reg[2] [0]));
  DFFQX4LVT \prod_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1] [1]),
       .Q (\shift_reg[2] [1]));
  DFFHQX4LVT \prod_reg_reg[2][4] (.CK (i_clock), .D (n_33), .Q
       (\prod_reg[2] [4]));
  DFFQX2LVT \prod_reg_reg[2][5] (.CK (i_clock), .D (n_62), .Q
       (\prod_reg[2] [5]));
  DFFQX2LVT \prod_reg_reg[2][6] (.CK (i_clock), .D (n_75), .Q
       (\prod_reg[2] [6]));
  DFFQX2LVT \prod_reg_reg[2][7] (.CK (i_clock), .D (n_87), .Q
       (\prod_reg[2] [7]));
  DFFQX2LVT \prod_reg_reg[2][8] (.CK (i_clock), .D (n_105), .Q
       (\prod_reg[2] [8]));
  DFFQX2LVT \prod_reg_reg[2][9] (.CK (i_clock), .D (n_126), .Q
       (\prod_reg[2] [9]));
  DFFQX2LVT \prod_reg_reg[2][10] (.CK (i_clock), .D (n_138), .Q
       (\prod_reg[2] [10]));
  DFFQX2LVT \prod_reg_reg[2][11] (.CK (i_clock), .D (n_137), .Q
       (\prod_reg[2] [11]));
  DFFHQX4LVT \prod_reg_reg[3][4] (.CK (i_clock), .D (n_21), .Q
       (\prod_reg[3] [4]));
  DFFQX2LVT \prod_reg_reg[3][5] (.CK (i_clock), .D (n_42), .Q
       (\prod_reg[3] [5]));
  DFFHQX4LVT \prod_reg_reg[3][6] (.CK (i_clock), .D (n_0), .Q
       (\prod_reg[3] [6]));
  DFFHQX4LVT \prod_reg_reg[3][7] (.CK (i_clock), .D (n_77), .Q
       (\prod_reg[3] [7]));
  DFFHQX4LVT \prod_reg_reg[3][8] (.CK (i_clock), .D (n_93), .Q
       (\prod_reg[3] [8]));
  DFFHQX4LVT \prod_reg_reg[3][9] (.CK (i_clock), .D (n_107), .Q
       (\prod_reg[3] [9]));
  DFFHQX1LVT \prod_reg_reg[3][11] (.CK (i_clock), .D (n_142), .Q
       (\prod_reg[3] [11]));
  DFFQX1LVT \prod_reg_reg[3][12] (.CK (i_clock), .D (n_147), .Q
       (\prod_reg[3] [12]));
  DFFHQX4LVT \prod_reg_reg[4][4] (.CK (i_clock), .D (n_29), .Q
       (\prod_reg[4] [4]));
  DFFHQX4LVT \prod_reg_reg[4][5] (.CK (i_clock), .D (n_49), .Q
       (\prod_reg[4] [5]));
  DFFQX2LVT \prod_reg_reg[4][6] (.CK (i_clock), .D (n_1), .Q
       (\prod_reg[4] [6]));
  DFFHQX4LVT \prod_reg_reg[4][7] (.CK (i_clock), .D (n_81), .Q
       (\prod_reg[4] [7]));
  DFFHQX4LVT \prod_reg_reg[4][8] (.CK (i_clock), .D (n_97), .Q
       (\prod_reg[4] [8]));
  DFFHQX4LVT \prod_reg_reg[4][9] (.CK (i_clock), .D (n_113), .Q
       (\prod_reg[4] [9]));
  DFFHQX1LVT \prod_reg_reg[4][12] (.CK (i_clock), .D (n_151), .Q
       (\prod_reg[4] [12]));
  DFFHQX8LVT \prod_reg_reg[5][2] (.CK (i_clock), .D (\shift_reg[4]
       [0]), .Q (\shift_reg[5] [0]));
  DFFQX2LVT \prod_reg_reg[5][4] (.CK (i_clock), .D (n_51), .Q
       (\prod_reg[5] [4]));
  DFFHQX4LVT \prod_reg_reg[5][5] (.CK (i_clock), .D (n_73), .Q
       (\prod_reg[5] [5]));
  DFFHQX1LVT \prod_reg_reg[5][10] (.CK (i_clock), .D (n_155), .Q
       (\prod_reg[5] [10]));
  DFFQX2LVT \prod_reg_reg[5][11] (.CK (i_clock), .D (n_154), .Q
       (\prod_reg[5] [11]));
  DFFHQX8LVT \prod_reg_reg[6][1] (.CK (i_clock), .D (\shift_reg[5]
       [0]), .Q (\shift_reg[6] [0]));
  DFFQX2LVT \prod_reg_reg[6][4] (.CK (i_clock), .D (n_67), .Q
       (\prod_reg[6] [4]));
  DFFHQX4LVT \prod_reg_reg[6][5] (.CK (i_clock), .D (n_85), .Q
       (\prod_reg[6] [5]));
  DFFQX2LVT \prod_reg_reg[7][0] (.CK (i_clock), .D (\shift_reg[6] [0]),
       .Q (\prod_reg[7] [0]));
  DFFQX2LVT \prod_reg_reg[7][1] (.CK (i_clock), .D (\shift_reg[6] [1]),
       .Q (\prod_reg[7] [1]));
  DFFQX2LVT \prod_reg_reg[7][2] (.CK (i_clock), .D (\shift_reg[6] [2]),
       .Q (\prod_reg[7] [2]));
  DFFHQX1LVT \prod_reg_reg[7][3] (.CK (i_clock), .D (n_69), .Q
       (\prod_reg[7] [3]));
  DFFQX2LVT \prod_reg_reg[7][4] (.CK (i_clock), .D (n_91), .Q
       (\prod_reg[7] [4]));
  DFFQX2LVT \prod_reg_reg[7][5] (.CK (i_clock), .D (n_109), .Q
       (\prod_reg[7] [5]));
  DFFQX2LVT \prod_reg_reg[7][6] (.CK (i_clock), .D (n_124), .Q
       (\prod_reg[7] [6]));
  DFFHQX4LVT \prod_reg_reg[7][7] (.CK (i_clock), .D (n_140), .Q
       (\prod_reg[7] [7]));
  DFFHQX4LVT \prod_reg_reg[7][8] (.CK (i_clock), .D (n_153), .Q
       (\prod_reg[7] [8]));
  DFFHQX2LVT \prod_reg_reg[7][9] (.CK (i_clock), .D (n_162), .Q
       (\prod_reg[7] [9]));
  DFFHQX1LVT \shift_reg_reg[0][3] (.CK (i_clock), .D (data_in_reg[3]),
       .Q (\shift_reg[0] [3]));
  DFFHQX1LVT \shift_reg_reg[0][4] (.CK (i_clock), .D (data_in_reg[4]),
       .Q (\shift_reg[0] [4]));
  DFFHQX1LVT \shift_reg_reg[0][5] (.CK (i_clock), .D (data_in_reg[5]),
       .Q (\shift_reg[0] [5]));
  DFFHQX1LVT \shift_reg_reg[0][6] (.CK (i_clock), .D (data_in_reg[6]),
       .Q (\shift_reg[0] [6]));
  DFFHQX1LVT \shift_reg_reg[0][7] (.CK (i_clock), .D (data_in_reg[7]),
       .Q (\shift_reg[0] [7]));
  DFFHQX1LVT \shift_reg_reg[1][3] (.CK (i_clock), .D (\shift_reg[0]
       [3]), .Q (\shift_reg[1] [3]));
  DFFHQX1LVT \shift_reg_reg[1][4] (.CK (i_clock), .D (\shift_reg[0]
       [4]), .Q (\shift_reg[1] [4]));
  DFFHQX1LVT \shift_reg_reg[1][5] (.CK (i_clock), .D (\shift_reg[0]
       [5]), .Q (\shift_reg[1] [5]));
  DFFHQX1LVT \shift_reg_reg[1][6] (.CK (i_clock), .D (\shift_reg[0]
       [6]), .Q (\shift_reg[1] [6]));
  DFFHQX1LVT \shift_reg_reg[1][7] (.CK (i_clock), .D (\shift_reg[0]
       [7]), .Q (\prod[2] [13]));
  DFFQX1LVT \shift_reg_reg[2][2] (.CK (i_clock), .D (n_883), .Q
       (\shift_reg[2] [2]));
  DFFHQX1LVT \shift_reg_reg[2][3] (.CK (i_clock), .D (\shift_reg[1]
       [3]), .Q (\shift_reg[2] [3]));
  DFFHQX1LVT \shift_reg_reg[2][4] (.CK (i_clock), .D (\shift_reg[1]
       [4]), .Q (\shift_reg[2] [4]));
  DFFHQX1LVT \shift_reg_reg[2][5] (.CK (i_clock), .D (\shift_reg[1]
       [5]), .Q (\shift_reg[2] [5]));
  DFFHQX1LVT \shift_reg_reg[2][6] (.CK (i_clock), .D (\shift_reg[1]
       [6]), .Q (\shift_reg[2] [6]));
  DFFQX4LVT \shift_reg_reg[3][1] (.CK (i_clock), .D (\shift_reg[2]
       [1]), .Q (\shift_reg[3] [1]));
  DFFQX2LVT \shift_reg_reg[3][2] (.CK (i_clock), .D (\shift_reg[2]
       [2]), .Q (\shift_reg[3] [2]));
  DFFHQX1LVT \shift_reg_reg[3][3] (.CK (i_clock), .D (\shift_reg[2]
       [3]), .Q (\shift_reg[3] [3]));
  DFFHQX1LVT \shift_reg_reg[3][4] (.CK (i_clock), .D (\shift_reg[2]
       [4]), .Q (\shift_reg[3] [4]));
  DFFHQX1LVT \shift_reg_reg[3][5] (.CK (i_clock), .D (\shift_reg[2]
       [5]), .Q (\shift_reg[3] [5]));
  DFFHQX1LVT \shift_reg_reg[3][6] (.CK (i_clock), .D (\shift_reg[2]
       [6]), .Q (\shift_reg[3] [6]));
  DFFHQX1LVT \shift_reg_reg[4][1] (.CK (i_clock), .D (\shift_reg[3]
       [1]), .Q (\shift_reg[4] [1]));
  DFFHQX1LVT \shift_reg_reg[4][2] (.CK (i_clock), .D (\shift_reg[3]
       [2]), .Q (\shift_reg[4] [2]));
  DFFHQX1LVT \shift_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3]
       [3]), .Q (\shift_reg[4] [3]));
  DFFHQX1LVT \shift_reg_reg[4][4] (.CK (i_clock), .D (\shift_reg[3]
       [4]), .Q (\shift_reg[4] [4]));
  DFFHQX1LVT \shift_reg_reg[4][5] (.CK (i_clock), .D (\shift_reg[3]
       [5]), .Q (\shift_reg[4] [5]));
  DFFHQX1LVT \shift_reg_reg[4][6] (.CK (i_clock), .D (\shift_reg[3]
       [6]), .Q (\shift_reg[4] [6]));
  DFFHQX1LVT \shift_reg_reg[5][2] (.CK (i_clock), .D (\shift_reg[4]
       [2]), .Q (\shift_reg[5] [2]));
  DFFHQX1LVT \shift_reg_reg[5][4] (.CK (i_clock), .D (\shift_reg[4]
       [4]), .Q (\shift_reg[5] [4]));
  DFFHQX1LVT \shift_reg_reg[5][5] (.CK (i_clock), .D (\shift_reg[4]
       [5]), .Q (\shift_reg[5] [5]));
  DFFHQX1LVT \shift_reg_reg[5][6] (.CK (i_clock), .D (\shift_reg[4]
       [6]), .Q (\shift_reg[5] [6]));
  DFFHQX1LVT \shift_reg_reg[6][4] (.CK (i_clock), .D (\shift_reg[5]
       [4]), .Q (\shift_reg[6] [4]));
  DFFHQX1LVT \shift_reg_reg[6][5] (.CK (i_clock), .D (\shift_reg[5]
       [5]), .Q (\shift_reg[6] [5]));
  DFFHQX1LVT \shift_reg_reg[6][6] (.CK (i_clock), .D (\shift_reg[5]
       [6]), .Q (\shift_reg[6] [6]));
  DFFHQX1LVT \shift_reg_reg[6][7] (.CK (i_clock), .D (\prod_reg[5]
       [12]), .Q (\shift_reg[6] [7]));
  INVX2LVT g5290(.A (n_161), .Y (n_162));
  ADDFX1LVT g5291__2398(.A (\shift_reg[6] [6]), .B (n_18), .CI (n_156),
       .CO (n_160), .S (n_161));
  INVX2LVT g5294(.A (n_158), .Y (n_159));
  ADDFX1LVT g5295__5107(.A (\shift_reg[5] [6]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_18), .CI (n_150), .CO (n_157),
       .S (n_158));
  INVX1LVT g5300(.A (n_152), .Y (n_156));
  ADDFX1LVT g5301__6260(.A (\shift_reg[4] [6]), .B (\prod[5] [13]), .CI
       (n_143), .CO (n_154), .S (n_155));
  ADDFX1LVT g5302__4319(.A (\shift_reg[6] [7]), .B (n_65), .CI (n_139),
       .CO (n_152), .S (n_153));
  CLKXOR2X1LVT g5305__8428(.A (n_52), .B (n_145), .Y (n_151));
  INVX1LVT g5306(.A (n_148), .Y (n_150));
  ADDFX1LVT g5307__5526(.A (n_56), .B (\prod_reg[5] [12]), .CI (n_134),
       .CO (n_148), .S (n_149));
  CLKXOR2X1LVT g5309__6783(.A (n_47), .B (n_141), .Y (n_147));
  ADDFX1LVT g5310__3680(.A (\shift_reg[3] [5]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_16), .CI (n_129), .CO (n_145),
       .S (n_146));
  ADDFX1LVT g5316__1617(.A (\shift_reg[4] [5]), .B (\prod[5] [13]), .CI
       (n_119), .CO (n_143), .S (n_144));
  ADDFX1LVT g5317__2802(.A (\shift_reg[2] [5]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .CI (n_121), .CO (n_141),
       .S (n_142));
  ADDFX1LVT g5318__1705(.A (\shift_reg[6] [7]), .B (n_60), .CI (n_123),
       .CO (n_139), .S (n_140));
  ADDFX1LVT g5319__5122(.A (\prod[2] [13]), .B (\shift_reg[1] [6]), .CI
       (n_125), .CO (n_137), .S (n_138));
  INVX1LVT g5325(.A (n_133), .Y (n_136));
  ADDFX1LVT g5326__8246(.A (n_57), .B (\prod_reg[5] [12]), .CI (n_116),
       .CO (n_134), .S (n_135));
  ADDFX1LVT g5327__7098(.A (data_in_reg[6]), .B (n_13), .CI (n_118),
       .CO (n_132), .S (n_133));
  AOI21X1LVT g5329__6131(.A0 (n_28), .A1 (n_128), .B0 (\shift_reg[0]
       [7]), .Y (n_131));
  ADDFX1LVT g5330__1881(.A (\shift_reg[3] [4]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_16), .CI (n_112), .CO (n_129),
       .S (n_130));
  ADDFX1LVT g5336__5115(.A (\shift_reg[0] [7]), .B (n_23), .CI (n_110),
       .CO (n_128), .S (n_127));
  ADDFX1LVT g5337__7482(.A (\prod[2] [13]), .B (\shift_reg[1] [5]), .CI
       (n_104), .CO (n_125), .S (n_126));
  ADDFX1LVT g5338__4733(.A (\shift_reg[6] [6]), .B (n_11), .CI (n_108),
       .CO (n_123), .S (n_124));
  ADDFX1LVT g5339__6161(.A (\shift_reg[2] [4]), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .CI (n_106), .CO (n_121),
       .S (n_122));
  ADDFX1LVT g5340__9315(.A (\shift_reg[4] [6]), .B (\shift_reg[4] [4]),
       .CI (n_102), .CO (n_119), .S (n_120));
  INVX1LVT g5343(.A (n_114), .Y (n_118));
  ADDFX1LVT g5344__9945(.A (\shift_reg[5] [6]), .B (n_10), .CI (n_100),
       .CO (n_116), .S (n_117));
  ADDFX1LVT g5345__2883(.A (data_in_reg[7]), .B (n_14), .CI (n_98), .CO
       (n_114), .S (n_115));
  ADDFX1LVT g5347__2346(.A (\shift_reg[3] [3]), .B (n_46), .CI (n_96),
       .CO (n_112), .S (n_113));
  ADDFX1LVT g5353__1666(.A (\shift_reg[0] [7]), .B (n_24), .CI (n_94),
       .CO (n_110), .S (n_111));
  ADDFX1LVT g5354__7410(.A (\shift_reg[6] [5]), .B (n_3), .CI (n_90),
       .CO (n_108), .S (n_109));
  ADDFX1LVT g5355__6417(.A (\shift_reg[2] [3]), .B (n_35), .CI (n_92),
       .CO (n_106), .S (n_107));
  ADDFX1LVT g5356__5477(.A (\shift_reg[1] [6]), .B (\shift_reg[1] [4]),
       .CI (n_86), .CO (n_104), .S (n_105));
  ADDFX1LVT g5357__2398(.A (\shift_reg[4] [5]), .B (\shift_reg[4] [3]),
       .CI (n_88), .CO (n_102), .S (n_103));
  ADDFX1LVT g5360__5107(.A (\shift_reg[5] [5]), .B (n_41), .CI (n_84),
       .CO (n_100), .S (n_101));
  ADDFX1LVT g5361__6260(.A (data_in_reg[7]), .B (n_19), .CI (n_82), .CO
       (n_98), .S (n_99));
  ADDFX1LVT g5363__4319(.A (\shift_reg[3] [2]), .B (n_44), .CI (n_80),
       .CO (n_96), .S (n_97));
  ADDFX1LVT g5369__8428(.A (\shift_reg[0] [6]), .B (n_22), .CI (n_78),
       .CO (n_94), .S (n_95));
  ADDFX1LVT g5370__5526(.A (\shift_reg[2] [2]), .B (n_40), .CI (n_76),
       .CO (n_92), .S (n_93));
  ADDFHX2LVT g5371__6783(.A (\shift_reg[6] [4]), .B (n_8), .CI (n_68),
       .CO (n_90), .S (n_91));
  ADDFX1LVT g5372__3680(.A (\shift_reg[4] [2]), .B (\shift_reg[4] [4]),
       .CI (n_72), .CO (n_88), .S (n_89));
  ADDFX1LVT g5373__1617(.A (\shift_reg[1] [5]), .B (\shift_reg[1] [3]),
       .CI (n_74), .CO (n_86), .S (n_87));
  ADDFHX1LVT g5376__2802(.A (\shift_reg[5] [4]), .B (n_4), .CI (n_59),
       .CO (n_84), .S (n_85));
  ADDFX1LVT g5377__1705(.A (data_in_reg[6]), .B (n_15), .CI (n_70), .CO
       (n_82), .S (n_83));
  ADDFX1LVT g5379__5122(.A (\shift_reg[3] [1]), .B (n_43), .CI (n_66),
       .CO (n_80), .S (n_81));
  ADDFX1LVT g5385__8246(.A (\shift_reg[0] [5]), .B (n_12), .CI (n_63),
       .CO (n_78), .S (n_79));
  ADDFX1LVT g5386__7098(.A (\shift_reg[2] [1]), .B (n_39), .CI (n_58),
       .CO (n_76), .S (n_77));
  ADDFX1LVT g5387__6131(.A (n_883), .B (\shift_reg[1] [4]), .CI (n_61),
       .CO (n_74), .S (n_75));
  ADDFX1LVT g5388__1881(.A (\shift_reg[4] [1]), .B (\shift_reg[4] [3]),
       .CI (n_50), .CO (n_72), .S (n_73));
  ADDFX1LVT g5391__5115(.A (data_in_reg[5]), .B (n_20), .CI (n_54), .CO
       (n_70), .S (n_71));
  OAI21XLLVT g5393__7482(.A0 (\shift_reg[6] [0]), .A1 (n_11), .B0
       (n_68), .Y (n_69));
  OAI21XLLVT g5397__4733(.A0 (\shift_reg[5] [0]), .A1 (n_10), .B0
       (n_59), .Y (n_67));
  AOI2BB1X4LVT g5399__6161(.A0N (\shift_reg[3] [0]), .A1N (n_45), .B0
       (\shift_reg[3] [3]), .Y (n_66));
  NAND2X4LVT g5400__9315(.A (\shift_reg[6] [0]), .B (n_11), .Y (n_68));
  INVX1LVT g5402(.A (\shift_reg[6] [5]), .Y (n_65));
  ADDFX1LVT g5403__9945(.A (\shift_reg[0] [4]), .B (n_7), .CI (n_31),
       .CO (n_63), .S (n_64));
  ADDFX1LVT g5404__2883(.A (\shift_reg[1] [1]), .B (\shift_reg[1] [3]),
       .CI (n_32), .CO (n_61), .S (n_62));
  INVX1LVT g5409(.A (\shift_reg[6] [4]), .Y (n_60));
  AOI2BB1X4LVT g5412__2346(.A0N (\shift_reg[2] [0]), .A1N (n_36), .B0
       (\shift_reg[2] [3]), .Y (n_58));
  NAND2X6LVT g5414__1666(.A (\shift_reg[5] [0]), .B (n_10), .Y (n_59));
  INVX1LVT g5417(.A (\shift_reg[5] [4]), .Y (n_57));
  INVX1LVT g5418(.A (\shift_reg[5] [5]), .Y (n_56));
  ADDFHX2LVT g5419__7410(.A (data_in_reg[4]), .B (n_9), .CI (n_25), .CO
       (n_54), .S (n_55));
  XNOR2X1LVT g5425__6417(.A (\shift_reg[3] [3]), .B (\shift_reg[3]
       [0]), .Y (n_53));
  XNOR2X1LVT g5426__5477(.A (n_46), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_16), .Y (n_52));
  ADDHX1LVT g5429__2398(.A (\shift_reg[4] [2]), .B (\shift_reg[4] [0]),
       .CO (n_50), .S (n_51));
  AOI21X1LVT g5434__5107(.A0 (\shift_reg[3] [2]), .A1 (n_27), .B0
       (n_45), .Y (n_49));
  XNOR2X1LVT g5435__6260(.A (\shift_reg[2] [3]), .B (\shift_reg[2]
       [0]), .Y (n_48));
  XNOR2X1LVT g5436__4319(.A (n_35), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .Y (n_47));
  INVX1 g5438(.A (\shift_reg[3] [6]), .Y (n_46));
  INVX1LVT g5443(.A (\shift_reg[3] [5]), .Y (n_44));
  INVX1LVT g5444(.A (\shift_reg[3] [4]), .Y (n_43));
  AOI21X1LVT g5445__8428(.A0 (\shift_reg[2] [2]), .A1 (n_17), .B0
       (n_36), .Y (n_42));
  NOR2X6LVT g5446__5526(.A (\shift_reg[3] [2]), .B (n_27), .Y (n_45));
  INVX1LVT g5450(.A (\shift_reg[5] [2]), .Y (n_41));
  INVX1LVT g5451(.A (\shift_reg[2] [5]), .Y (n_40));
  INVX1LVT g5452(.A (\shift_reg[2] [4]), .Y (n_39));
  INVX1LVT g5458(.A (n_37), .Y (n_38));
  INVX1 g5459(.A (\shift_reg[2] [6]), .Y (n_35));
  OAI21X1LVT g5460__6783(.A0 (n_22), .A1 (\shift_reg[0] [0]), .B0
       (n_31), .Y (n_34));
  XNOR2X1LVT g5461__3680(.A (\shift_reg[0] [6]), .B (\shift_reg[0]
       [7]), .Y (n_37));
  NOR2X6LVT g5462__1617(.A (\shift_reg[2] [2]), .B (n_17), .Y (n_36));
  ADDHX1LVT g5466__2802(.A (n_883), .B (\shift_reg[1] [0]), .CO (n_32),
       .S (n_33));
  OAI21X1LVT g5472__1705(.A0 (data_in_reg[0]), .A1 (n_15), .B0 (n_25),
       .Y (n_30));
  AOI21X1LVT g5473__5122(.A0 (\shift_reg[3] [0]), .A1 (\shift_reg[3]
       [1]), .B0 (n_26), .Y (n_29));
  NAND2X2LVT g5474__8246(.A (n_22), .B (\shift_reg[0] [0]), .Y (n_31));
  INVX1LVT g5477(.A (\shift_reg[0] [6]), .Y (n_28));
  INVX1LVT g5484(.A (n_27), .Y (n_26));
  INVX1LVT g5485(.A (\shift_reg[0] [4]), .Y (n_24));
  INVX1LVT g5486(.A (\shift_reg[0] [5]), .Y (n_23));
  INVX2LVT g5487(.A (\shift_reg[0] [3]), .Y (n_22));
  AOI21X1LVT g5488__7098(.A0 (\shift_reg[2] [0]), .A1 (\shift_reg[2]
       [1]), .B0 (n_16), .Y (n_21));
  OR2X6LVT g5489__6131(.A (\shift_reg[3] [1]), .B (\shift_reg[3] [0]),
       .Y (n_27));
  NAND2X6LVT g5491__1881(.A (data_in_reg[0]), .B (n_15), .Y (n_25));
  INVX1LVT g5495(.A (data_in_reg[2]), .Y (n_20));
  INVX1LVT g5497(.A (data_in_reg[4]), .Y (n_19));
  INVX1LVT g5498(.A (\shift_reg[6] [7]), .Y (n_18));
  INVX1LVT g5521(.A (n_17), .Y (n_16));
  CLKINVX4LVT g5522(.A (data_in_reg[3]), .Y (n_15));
  INVX1LVT g5523(.A (data_in_reg[5]), .Y (n_14));
  INVX1LVT g5524(.A (data_in_reg[7]), .Y (n_13));
  OR2X6LVT g5532__5115(.A (\shift_reg[2] [1]), .B (\shift_reg[2] [0]),
       .Y (n_17));
  DFFX1LVT \data_in_reg_reg[1] (.CK (i_clock), .D (i_data[1]), .Q
       (data_in_reg[1]), .QN (n_9));
  DFFX1LVT \prod_reg_reg[0][1] (.CK (i_clock), .D (data_in_reg[1]), .Q
       (\shift_reg[0] [1]), .QN (n_7));
  DFFX4LVT \prod_reg_reg[2][12] (.CK (i_clock), .D (\prod[2] [13]), .Q
       (\prod[3] [14]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_24));
  DFFX1LVT \prod_reg_reg[3][13] (.CK (i_clock), .D (\prod[3] [14]), .Q
       (\prod[4] [14]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_16));
  DFFX4LVT \prod_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4] [1]),
       .Q (\shift_reg[5] [1]), .QN (n_4));
  DFFX1LVT \prod_reg_reg[5][12] (.CK (i_clock), .D (\prod[5] [13]), .Q
       (\prod_reg[5] [12]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_18));
  DFFX1LVT \prod_reg_reg[6][2] (.CK (i_clock), .D (\shift_reg[5] [1]),
       .Q (\shift_reg[6] [1]), .QN (n_8));
  DFFX4LVT \prod_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5] [2]),
       .Q (\shift_reg[6] [2]), .QN (n_3));
  DFFX4LVT \shift_reg_reg[5][3] (.CK (i_clock), .D (\shift_reg[4] [3]),
       .Q (\shift_reg[5] [3]), .QN (n_10));
  DFFX4LVT \shift_reg_reg[6][3] (.CK (i_clock), .D (\shift_reg[5] [3]),
       .Q (\shift_reg[6] [3]), .QN (n_11));
  CLKXOR2X1LVT g2__7482(.A (n_53), .B (n_45), .Y (n_1));
  CLKXOR2X1LVT g5577__4733(.A (n_48), .B (n_36), .Y (n_0));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_001_0__6161(.A
       (\shift_reg[1] [0]), .B (\prod_reg[7] [1]), .CI
       (\shift_reg[6] [0]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_231),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_233));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_002_0__9315(.A
       (\shift_reg[5] [0]), .B (\shift_reg[1] [1]), .CI
       (\shift_reg[2] [0]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_230),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_249));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_0__2883(.A
       (\prod_reg[0] [3]), .B (\shift_reg[5] [1]), .CI
       (\shift_reg[1] [2]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_229),
       .S (csa_tree_ADD_TC_OP_12_groupi_n_228));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_006_1__1705(.A
       (\prod_reg[7] [6]), .B (\prod_reg[1] [6]), .CI (\prod_reg[2]
       [6]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_213), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_212));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_1__5115(.A
       (\prod_reg[7] [7]), .B (\prod_reg[1] [7]), .CI (\prod_reg[2]
       [7]), .CO (csa_tree_ADD_TC_OP_12_groupi_n_209), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_208));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_007_3__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_213), .B (n_496), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_208), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_175), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_174));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_008_3__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_209), .B (n_433), .CI (n_391),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_248), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_171));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_011_1__8246(.A
       (\prod_reg[3] [11]), .B (csa_tree_ADD_TC_OP_12_groupi_n_17), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_14), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_193), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_192));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_0__5115(.A
       (\prod_reg[4] [12]), .B (\prod_reg[3] [12]), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_18), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_191), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_190));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_2__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_190), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_193), .CI (n_1067), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_160), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_159));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_012_3__6161(.A
       (n_1114), .B (csa_tree_ADD_TC_OP_12_groupi_n_159), .CI (n_1109),
       .CO (csa_tree_ADD_TC_OP_12_groupi_n_245), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_244));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_0__9315(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_23), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_16), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_191), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_261), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_158));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_013_1__9945(.A
       (n_1113), .B (csa_tree_ADD_TC_OP_12_groupi_n_158), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_160), .CO
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .S
       (csa_tree_ADD_TC_OP_12_groupi_n_260));
  NAND2X8LVT csa_tree_ADD_TC_OP_12_groupi_g3652__6783(.A (n_975), .B
       (n_660), .Y (csa_tree_ADD_TC_OP_12_groupi_n_131));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3656__1705(.A (n_763), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_8), .Y (n_170));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3657__5122(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_6), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_116), .Y (n_171));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3664__4733(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_112), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_117), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_119));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3665__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_87), .B (n_975), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_118));
  NOR2X8LVT csa_tree_ADD_TC_OP_12_groupi_g3666__9315(.A (n_1090), .B
       (n_975), .Y (csa_tree_ADD_TC_OP_12_groupi_n_117));
  AOI21X2LVT csa_tree_ADD_TC_OP_12_groupi_g3667__9945(.A0 (n_473), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_105), .B0 (n_504), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_116));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3670__2346(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_7), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_105), .Y (n_172));
  NAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3671__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_98), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_106), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_112));
  OAI21X2LVT csa_tree_ADD_TC_OP_12_groupi_g3674__5477(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_97), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_59), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_109));
  NAND2X8LVT csa_tree_ADD_TC_OP_12_groupi_g3677__6260(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .B (n_587), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_106));
  CLKBUFX2LVT csa_tree_ADD_TC_OP_12_groupi_g3678(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_104), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_105));
  NAND2X8LVT csa_tree_ADD_TC_OP_12_groupi_g3679__4319(.A (n_1098), .B
       (n_821), .Y (csa_tree_ADD_TC_OP_12_groupi_n_104));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3680__8428(.A (n_1032), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_0), .Y (n_173));
  NOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3682__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_87), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_101));
  INVX4LVT csa_tree_ADD_TC_OP_12_groupi_g3683(.A (n_587), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_100));
  CLKAND2X3LVT csa_tree_ADD_TC_OP_12_groupi_g3686__1617(.A (n_1091), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_75), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_98));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g3687(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_97), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_96));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3688__2802(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_73), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_74), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_97));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g3689(.A (n_368), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_95));
  OR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3703__6161(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_67), .B (n_1090), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_87));
  INVX3LVT csa_tree_ADD_TC_OP_12_groupi_g3707(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_75), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_76));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3708__9315(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_67), .B (n_1091), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_74));
  NAND2X2LVT csa_tree_ADD_TC_OP_12_groupi_g3713__2883(.A (n_1091), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_62), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_80));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3715__1666(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_73), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_67), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_75));
  CLKINVX12LVT csa_tree_ADD_TC_OP_12_groupi_g3717(.A (n_801), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_70));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g3720(.A (n_363), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_65));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g3721(.A (n_1090), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_62));
  AND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3723__7410(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_260), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_245), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_73));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3728__6260(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_260), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_245), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_67));
  NOR2X8LVT csa_tree_ADD_TC_OP_12_groupi_g3729__4319(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_49), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_48), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_66));
  INVX2LVT csa_tree_ADD_TC_OP_12_groupi_g3734(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_54), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_55));
  NAND2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3738__3680(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_261), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_59));
  NOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3742__5122(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_261), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_246), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_56));
  NAND2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3743__8246(.A (n_895), .B
       (n_442), .Y (csa_tree_ADD_TC_OP_12_groupi_n_54));
  BUFX3LVT csa_tree_ADD_TC_OP_12_groupi_g3748(.A (n_455), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_49));
  BUFX3LVT csa_tree_ADD_TC_OP_12_groupi_g3749(.A (n_1027), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_48));
  XNOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3755__4733(.A (n_1021), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_43), .Y (n_175));
  OR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3759__9945(.A (n_1019), .B
       (n_1018), .Y (csa_tree_ADD_TC_OP_12_groupi_n_43));
  AOI22X2LVT csa_tree_ADD_TC_OP_12_groupi_g3769__5107(.A0
       (csa_tree_ADD_TC_OP_12_groupi_n_19), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_21), .B0 (\shift_reg[3] [0]),
       .B1 (\shift_reg[4] [0]), .Y (csa_tree_ADD_TC_OP_12_groupi_n_34));
  NOR2X2LVT csa_tree_ADD_TC_OP_12_groupi_g3775__6783(.A
       (csa_tree_ADD_TC_OP_12_groupi_n_19), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_21), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_29));
  NAND2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g3793__1705(.AN (n_637), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_65), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_8));
  NOR2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g3794__5122(.AN (n_473), .B
       (n_504), .Y (csa_tree_ADD_TC_OP_12_groupi_n_7));
  NOR2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g3795__8246(.AN (n_1040), .B
       (n_1041), .Y (csa_tree_ADD_TC_OP_12_groupi_n_6));
  NAND2BX2LVT csa_tree_ADD_TC_OP_12_groupi_g3796__7098(.AN (n_1091), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_76), .Y
       (csa_tree_ADD_TC_OP_12_groupi_n_5));
  CLKXOR2X1LVT csa_tree_ADD_TC_OP_12_groupi_g3798__1881(.A (n_817), .B
       (n_1031), .Y (n_174));
  NOR2BX4LVT csa_tree_ADD_TC_OP_12_groupi_g3799__5115(.AN (n_1021), .B
       (n_1019), .Y (csa_tree_ADD_TC_OP_12_groupi_n_2));
  NAND2BX1LVT csa_tree_ADD_TC_OP_12_groupi_g3801__4733(.AN (n_1045), .B
       (n_716), .Y (csa_tree_ADD_TC_OP_12_groupi_n_0));
  CLKAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3730__5579(.A (n_455), .B
       (n_1027), .Y (n_363));
  CLKINVX4LVT csa_tree_ADD_TC_OP_12_groupi_g5583(.A (n_367), .Y
       (n_368));
  OAI21X4LVT csa_tree_ADD_TC_OP_12_groupi_g3691__1705_dup(.A0 (n_799),
       .A1 (n_363), .B0 (n_801), .Y (n_367));
  OR2X1LVT g137(.A (\prod_reg[6] [7]), .B (\prod_reg[5] [7]), .Y
       (n_374));
  NOR2X1LVT g138(.A (n_376), .B (n_377), .Y (n_378));
  XOR2X4LVT g134(.A (n_380), .B (n_500), .Y (n_381));
  OAI22X2LVT g136(.A0 (\prod_reg[6] [7]), .A1 (n_377), .B0
       (\prod_reg[5] [7]), .B1 (n_376), .Y (n_380));
  OR2X1LVT g5589(.A (\prod_reg[6] [9]), .B (\prod_reg[5] [9]), .Y
       (n_383));
  ADDFHX1LVT g5590(.A (\prod_reg[4] [8]), .B (\prod_reg[3] [8]), .CI
       (\prod_reg[0] [8]), .CO (n_384), .S (n_391));
  CLKXOR2X1LVT g5592(.A (n_389), .B (n_384), .Y (n_390));
  OAI22X2LVT g5593(.A0 (\prod_reg[6] [9]), .A1 (n_386), .B0
       (\prod_reg[5] [9]), .B1 (n_385), .Y (n_389));
  ADDFHX2LVT g250(.A (csa_tree_ADD_TC_OP_12_groupi_n_29), .B (n_898),
       .CI (csa_tree_ADD_TC_OP_12_groupi_n_229), .CO (n_399), .S
       (n_392));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_003_1__5597(.A
       (\shift_reg[2] [1]), .B (\prod_reg[7] [3]), .CI
       (\shift_reg[6] [2]), .CO (n_394), .S (n_428));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_1__5599(.A
       (\prod_reg[2] [4]), .B (\prod_reg[5] [4]), .CI (\prod_reg[6]
       [4]), .CO (n_407), .S (n_396));
  INVX2LVT g249(.A (n_399), .Y (n_400));
  ADDFX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_005_1__5600(.A
       (\prod_reg[7] [5]), .B (\prod_reg[1] [5]), .CI (\prod_reg[2]
       [5]), .CO (n_430), .S (n_401));
  OR2X1LVT g238(.A (n_979), .B (n_1002), .Y (n_416));
  BUFX2LVT g248(.A (n_401), .Y (n_421));
  ADDFHX1LVT g72(.A (\prod_reg[7] [8]), .B (\prod_reg[2] [8]), .CI
       (\prod_reg[1] [8]), .CO (n_432), .S (n_433));
  BUFX6LVT g5605(.A (n_796), .Y (n_436));
  CLKINVX4LVT g121(.A (n_1051), .Y (n_442));
  OAI21X4LVT g125(.A0 (n_443), .A1 (n_446), .B0 (n_447), .Y (n_448));
  INVX2LVT g132(.A (n_793), .Y (n_443));
  NOR2X4LVT g128(.A (n_948), .B (n_445), .Y (n_446));
  BUFX3LVT g131(.A (n_925), .Y (n_445));
  NAND2X4LVT g130(.A (n_948), .B (n_445), .Y (n_447));
  OAI21X4LVT g5607(.A0 (n_450), .A1 (n_453), .B0 (n_454), .Y (n_455));
  BUFX2LVT g5608(.A (n_449), .Y (n_450));
  XNOR3X1LVT g5609(.A (n_902), .B (n_381), .C (n_971), .Y (n_449));
  NOR2X2LVT g5610(.A (n_451), .B (n_452), .Y (n_453));
  BUFX2LVT g5611(.A (csa_tree_ADD_TC_OP_12_groupi_n_174), .Y (n_451));
  BUFX2LVT g5612(.A (n_988), .Y (n_452));
  NAND2X2LVT g5613(.A (n_451), .B (n_452), .Y (n_454));
  BUFX3LVT g5617(.A (n_902), .Y (n_458));
  OR2X6LVT g19(.A (n_607), .B (n_970), .Y (n_473));
  OAI21X4LVT g5619(.A0 (n_477), .A1 (n_1026), .B0 (n_1025), .Y (n_480));
  CLKBUFX2LVT g5620(.A (n_1088), .Y (n_477));
  INVX2LVT g5626(.A (csa_tree_ADD_TC_OP_12_groupi_n_175), .Y (n_482));
  AO21X1LVT g5631(.A0 (n_488), .A1 (n_489), .B0 (n_492), .Y (n_493));
  OR2X1LVT g5632(.A (\prod_reg[6] [8]), .B (\prod_reg[5] [8]), .Y
       (n_488));
  ADDFHX1LVT g5633(.A (\prod_reg[4] [7]), .B (\prod_reg[3] [7]), .CI
       (\prod_reg[0] [7]), .CO (n_489), .S (n_496));
  NOR2X1LVT g5634(.A (n_490), .B (n_491), .Y (n_492));
  ADDFHX2LVT g92(.A (\prod_reg[4] [6]), .B (\prod_reg[3] [6]), .CI
       (\prod_reg[0] [6]), .CO (n_500), .S (n_501));
  AOI21X4LVT g5639(.A0 (n_502), .A1 (n_1040), .B0 (n_1041), .Y (n_503));
  CLKAND2X3LVT g31(.A (n_607), .B (n_970), .Y (n_502));
  BUFX2LVT g30(.A (n_502), .Y (n_504));
  NOR2X1LVT g5641(.A (\prod_reg[5] [6]), .B (\prod_reg[6] [6]), .Y
       (n_505));
  OAI22X2LVT g5645(.A0 (\prod_reg[6] [6]), .A1 (n_510), .B0
       (\prod_reg[5] [6]), .B1 (n_511), .Y (n_512));
  OAI21X4LVT g5648(.A0 (n_520), .A1 (n_521), .B0 (n_522), .Y (n_523));
  NOR2X1LVT g5649(.A (\shift_reg[0] [1]), .B (n_1119), .Y (n_520));
  INVX2LVT g5650(.A (csa_tree_ADD_TC_OP_12_groupi_n_233), .Y (n_521));
  NAND2X1LVT g5651(.A (\shift_reg[0] [1]), .B (n_1119), .Y (n_522));
  XNOR2X1LVT g5652(.A (n_521), .B (n_526), .Y (n_527));
  CLKXOR2X1LVT g5653(.A (\shift_reg[0] [1]), .B (n_1119), .Y (n_526));
  OR2X1LVT g5655(.A (n_428), .B (n_530), .Y (n_531));
  INVX2LVT g5657(.A (n_529), .Y (n_530));
  INVX3LVT g5658(.A (csa_tree_ADD_TC_OP_12_groupi_n_228), .Y (n_529));
  ADDFX1LVT g5659(.A (n_905), .B (csa_tree_ADD_TC_OP_12_groupi_n_34),
       .CI (csa_tree_ADD_TC_OP_12_groupi_n_230), .CO (n_540), .S
       (n_532));
  CLKMX2X3LVT g5661(.A (n_538), .B (n_537), .S0 (n_532), .Y (n_539));
  INVX3LVT g5662(.A (n_537), .Y (n_538));
  NOR2X4LVT g5663(.A (n_535), .B (n_536), .Y (n_537));
  NOR2X4LVT g5664(.A (n_529), .B (n_428), .Y (n_535));
  CLKAND2X6LVT g5665(.A (n_529), .B (n_428), .Y (n_536));
  INVX2LVT g5667(.A (n_880), .Y (n_542));
  NOR2X4LVT g5669(.A (n_543), .B (n_544), .Y (n_545));
  BUFX2LVT g5670(.A (n_540), .Y (n_543));
  BUFX3LVT g5671(.A (n_392), .Y (n_544));
  XOR3X1LVT g5673(.A (n_540), .B (n_392), .C (n_880), .Y (n_548));
  NAND2X1LVT g5680(.A (n_1002), .B (n_979), .Y (n_559));
  OAI22X4LVT g397(.A0 (n_561), .A1 (n_564), .B0 (n_562), .B1 (n_565),
       .Y (n_566));
  NOR3X8LVT g401(.A (csa_tree_ADD_TC_OP_12_groupi_n_87), .B (n_763), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_100), .Y (n_561));
  OAI21X4LVT g399(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_87), .A1 (n_975),
       .B0 (n_563), .Y (n_564));
  CLKAND2X6LVT g400(.A (n_562), .B (csa_tree_ADD_TC_OP_12_groupi_n_97),
       .Y (n_563));
  NOR2BX2LVT g402(.AN (csa_tree_ADD_TC_OP_12_groupi_n_59), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_56), .Y (n_562));
  NOR3X6LVT g398(.A (csa_tree_ADD_TC_OP_12_groupi_n_96), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_118), .C (n_561), .Y (n_565));
  OAI21X4LVT g90(.A0 (n_799), .A1 (n_363), .B0 (n_801), .Y (n_581));
  CLKINVX8LVT g91(.A (n_1008), .Y (n_583));
  NOR2X8LVT g89(.A (n_583), .B (n_825), .Y (n_587));
  CLKINVX6LVT g96(.A (n_1075), .Y (n_596));
  CLKMX2X2LVT g98(.A (n_400), .B (n_399), .S0 (n_628), .Y (n_598));
  OAI2BB1X4LVT g5690(.A0N (n_416), .A1N (n_598), .B0 (n_559), .Y
       (n_607));
  NAND2BX2LVT g164(.AN (n_610), .B (n_612), .Y (n_613));
  NOR2X1LVT g177(.A (n_608), .B (n_609), .Y (n_610));
  CLKINVX4LVT g178(.A (\prod_reg[6] [5]), .Y (n_608));
  CLKINVX6LVT g179(.A (\prod_reg[5] [5]), .Y (n_609));
  OAI21X1LVT g168(.A0 (\prod_reg[5] [5]), .A1 (\prod_reg[6] [5]), .B0
       (n_611), .Y (n_612));
  NOR2X4LVT g173(.A (n_886), .B (n_885), .Y (n_611));
  NOR2X6LVT g5692(.A (n_620), .B (n_893), .Y (n_624));
  NOR2X2LVT g167(.A (n_616), .B (n_619), .Y (n_620));
  NOR2X2LVT g174(.A (n_886), .B (n_885), .Y (n_616));
  NOR2X4LVT g171(.A (n_617), .B (n_618), .Y (n_619));
  NOR2X4LVT g176(.A (\prod_reg[6] [5]), .B (n_609), .Y (n_617));
  NOR2X4LVT g175(.A (\prod_reg[5] [5]), .B (n_608), .Y (n_618));
  CLKXOR2X1LVT g161(.A (n_401), .B (n_624), .Y (n_628));
  CLKBUFX3LVT g5696(.A (csa_tree_ADD_TC_OP_12_groupi_n_66), .Y (n_637));
  NOR2X4LVT g82(.A (csa_tree_ADD_TC_OP_12_groupi_n_66), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_70), .Y (n_640));
  OAI22X4LVT g210(.A0 (n_650), .A1 (n_651), .B0 (n_649), .B1 (n_652),
       .Y (n_653));
  NAND2X1LVT g212(.A (csa_tree_ADD_TC_OP_12_groupi_n_65), .B (n_649),
       .Y (n_650));
  NOR2X4LVT g213(.A (n_799), .B (csa_tree_ADD_TC_OP_12_groupi_n_70), .Y
       (n_649));
  NOR2X4LVT g214(.A (n_637), .B (n_763), .Y (n_651));
  NOR2BX4LVT g211(.AN (csa_tree_ADD_TC_OP_12_groupi_n_65), .B (n_651),
       .Y (n_652));
  NAND2X4LVT g338(.A (n_957), .B (n_587), .Y (n_660));
  OAI22X4LVT g215(.A0 (n_662), .A1 (n_664), .B0 (n_663), .B1 (n_1105),
       .Y (n_667));
  NOR2X4LVT g219(.A (n_763), .B (n_1007), .Y (n_662));
  NAND2X4LVT g217(.A (n_663), .B (n_1006), .Y (n_664));
  NOR2BX2LVT g218(.AN (n_1093), .B (n_1095), .Y (n_663));
  NAND2X6LVT g433(.A (n_688), .B (n_699), .Y (n_700));
  NAND2X8LVT g437(.A (n_676), .B (n_687), .Y (n_688));
  INVX3LVT g443(.A (n_675), .Y (n_676));
  CLKINVX6LVT g444(.A (n_674), .Y (n_675));
  ADDFHX2LVT g445(.A (\prod_reg[7] [9]), .B (\prod_reg[1] [9]), .CI
       (\prod_reg[2] [9]), .CO (n_674), .S (n_708));
  CLKINVX8LVT g441(.A (n_686), .Y (n_687));
  NOR2X8LVT g447(.A (n_681), .B (n_685), .Y (n_686));
  AOI21X4LVT g449(.A0 (n_680), .A1 (n_678), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_22), .Y (n_681));
  NAND2X8LVT g458(.A (\prod_reg[4] [10]), .B (n_677), .Y (n_678));
  NAND2X8LVT g462(.A (\prod_reg[3] [10]), .B (n_679), .Y (n_680));
  NOR3X6LVT g448(.A (\prod_reg[0] [10]), .B (n_683), .C (n_684), .Y
       (n_685));
  INVX4LVT g457(.A (n_678), .Y (n_683));
  INVX3LVT g461(.A (n_680), .Y (n_684));
  NAND2X6LVT g435(.A (n_697), .B (n_698), .Y (n_699));
  CLKINVX8LVT g442(.A (n_696), .Y (n_697));
  NOR2X8LVT g451(.A (n_693), .B (n_695), .Y (n_696));
  NOR3X4LVT g453(.A (\prod_reg[2] [10]), .B (n_690), .C (n_692), .Y
       (n_693));
  NOR2X4LVT g460(.A (\prod_reg[7] [10]), .B (n_689), .Y (n_690));
  INVX3LVT g469(.A (\prod_reg[1] [10]), .Y (n_689));
  NOR2X4LVT g459(.A (\prod_reg[1] [10]), .B (n_691), .Y (n_692));
  NOR2BX4LVT g452(.AN (\prod_reg[2] [10]), .B (n_694), .Y (n_695));
  NOR2X4LVT g456(.A (n_690), .B (n_692), .Y (n_694));
  NAND2X6LVT g438(.A (n_675), .B (n_686), .Y (n_698));
  AOI31X4LVT g436(.A0 (n_675), .A1 (n_687), .A2 (n_696), .B0 (n_701),
       .Y (n_702));
  NOR3X4LVT g440(.A (n_675), .B (n_687), .C (n_697), .Y (n_701));
  AOI2BB1X4LVT g434(.A0N (n_696), .A1N (n_688), .B0 (n_703), .Y
       (n_704));
  NOR3X4LVT g439(.A (n_676), .B (n_687), .C (n_696), .Y (n_703));
  AO21X1LVT g454(.A0 (\prod_reg[1] [10]), .A1 (\prod_reg[2] [10]), .B0
       (n_706), .Y (n_707));
  AOI2BB1X1LVT g455(.A0N (\prod_reg[1] [10]), .A1N (\prod_reg[2] [10]),
       .B0 (\prod_reg[7] [10]), .Y (n_706));
  NAND2BX1LVT g446(.AN (n_709), .B (n_710), .Y (n_711));
  NOR2X1LVT g463(.A (n_677), .B (n_679), .Y (n_709));
  OAI21X2LVT g450(.A0 (\prod_reg[4] [10]), .A1 (\prod_reg[3] [10]), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_22), .Y (n_710));
  CLKINVX4LVT g52(.A (n_715), .Y (n_716));
  NOR2X8LVT g53(.A (n_713), .B (n_1046), .Y (n_715));
  CLKAND2X3LVT g57(.A (n_598), .B (n_596), .Y (n_713));
  NAND2X4LVT g56(.A (n_596), .B (n_598), .Y (n_718));
  OAI22X4LVT g5716(.A0 (n_890), .A1 (n_739), .B0 (n_1106), .B1 (n_740),
       .Y (n_741));
  NAND2X4LVT g5718(.A (csa_tree_ADD_TC_OP_12_groupi_n_95), .B (n_1106),
       .Y (n_739));
  NOR2BX4LVT g5721(.AN (csa_tree_ADD_TC_OP_12_groupi_n_95), .B (n_890),
       .Y (n_740));
  CLKINVX12LVT g7(.A (n_957), .Y (n_763));
  ADDFHX1LVT g5736(.A (\prod_reg[4] [5]), .B (\prod_reg[0] [5]), .CI
       (\prod_reg[3] [5]), .CO (n_790), .S (n_789));
  CLKXOR2X1LVT g5737(.A (n_512), .B (n_790), .Y (n_791));
  ADDFHX2LVT g5739(.A (n_432), .B (n_708), .CI (n_933), .CO (n_793), .S
       (n_553));
  OAI21X4LVT g5740(.A0 (n_482), .A1 (n_1086), .B0 (n_1087), .Y (n_468));
  ADDFHX2LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_009_4__5741(.A
       (n_390), .B (n_493), .CI (csa_tree_ADD_TC_OP_12_groupi_n_248),
       .CO (n_796), .S (n_797));
  CLKAND2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3724__5742(.A (n_480), .B
       (n_798), .Y (n_799));
  XOR3X1LVT g5743(.A (n_553), .B (n_468), .C (n_797), .Y (n_798));
  OR2X6LVT g5744(.A (n_480), .B (n_800), .Y (n_801));
  XOR3X1LVT g64_dup(.A (n_553), .B (n_468), .C (n_797), .Y (n_800));
  NAND2X2LVT g5749(.A (n_458), .B (n_381), .Y (n_804));
  NOR2X4LVT csa_tree_ADD_TC_OP_12_groupi_g3762__5755(.A (n_897), .B
       (n_1028), .Y (n_816));
  NOR2X6LVT csa_tree_ADD_TC_OP_12_groupi_g3756__5756(.A (n_1018), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_2), .Y (n_817));
  NOR2X8LVT g5759(.A (n_816), .B (n_817), .Y (n_818));
  NAND2X8LVT g5760(.A (n_818), .B (n_716), .Y (n_821));
  CLKINVX6LVT g9(.A (n_824), .Y (n_825));
  NOR2X6LVT g10(.A (csa_tree_ADD_TC_OP_12_groupi_n_70), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_66), .Y (n_824));
  NAND2X4LVT g5776(.A (n_849), .B (n_1075), .Y (n_850));
  MXI2X2LVT g5777(.A (n_400), .B (n_399), .S0 (n_628), .Y (n_849));
  NAND2X4LVT g5778(.A (n_850), .B (n_718), .Y (n_852));
  CLKAND2X6LVT g69(.A (csa_tree_ADD_TC_OP_12_groupi_n_76), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_117), .Y (n_871));
  ADDFHX1LVT csa_tree_ADD_TC_OP_12_groupi_cdnfadd_004_0__5791(.A
       (\prod_reg[1] [4]), .B (\prod_reg[7] [4]), .CI (\prod_reg[0]
       [4]), .CO (n_877), .S (n_878));
  ADDFHX2LVT g5792(.A (n_394), .B (n_878), .CI (n_396), .CO (n_415), .S
       (n_880));
  DFFX1 \prod_reg_reg[4][13] (.CK (i_clock), .D (\prod[4] [14]), .Q
       (\prod[5] [13]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_23));
  DFFX4LVT \prod_reg_reg[4][3] (.CK (i_clock), .D (\shift_reg[3] [0]),
       .Q (\shift_reg[4] [0]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_21));
  DFFX4LVT \prod_reg_reg[3][3] (.CK (i_clock), .D (\shift_reg[2] [0]),
       .Q (\shift_reg[3] [0]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_19));
  DFFX1LVT \prod_reg_reg[1][11] (.CK (i_clock), .D (n_131), .Q
       (\prod_reg[1] [11]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_17));
  DFFX1LVT \prod_reg_reg[4][11] (.CK (i_clock), .D (n_146), .Q
       (\prod_reg[4] [11]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_14));
  DFFX4LVT \prod_reg_reg[6][7] (.CK (i_clock), .D (n_117), .Q
       (\prod_reg[6] [7]), .QN (n_376));
  DFFX4LVT \prod_reg_reg[5][7] (.CK (i_clock), .D (n_103), .Q
       (\prod_reg[5] [7]), .QN (n_377));
  DFFX1LVT \prod_reg_reg[6][9] (.CK (i_clock), .D (n_149), .Q
       (\prod_reg[6] [9]), .QN (n_385));
  DFFX1LVT \prod_reg_reg[5][9] (.CK (i_clock), .D (n_144), .Q
       (\prod_reg[5] [9]), .QN (n_386));
  DFFX1LVT \prod_reg_reg[6][8] (.CK (i_clock), .D (n_135), .Q
       (\prod_reg[6] [8]), .QN (n_490));
  DFFX1LVT \prod_reg_reg[5][8] (.CK (i_clock), .D (n_120), .Q
       (\prod_reg[5] [8]), .QN (n_491));
  DFFX4LVT \prod_reg_reg[5][6] (.CK (i_clock), .D (n_89), .Q
       (\prod_reg[5] [6]), .QN (n_510));
  DFFX4LVT \prod_reg_reg[6][6] (.CK (i_clock), .D (n_101), .Q
       (\prod_reg[6] [6]), .QN (n_511));
  DFFX4LVT \prod_reg_reg[3][10] (.CK (i_clock), .D (n_122), .Q
       (\prod_reg[3] [10]), .QN (n_677));
  DFFX4LVT \prod_reg_reg[4][10] (.CK (i_clock), .D (n_130), .Q
       (\prod_reg[4] [10]), .QN (n_679));
  BUFX3LVT g2(.A (\shift_reg[1] [2]), .Y (n_883));
  CLKINVX4LVT g85(.A (\prod_reg[3] [4]), .Y (n_885));
  CLKINVX4LVT g5825(.A (\prod_reg[4] [4]), .Y (n_886));
  NOR2BX4LVT g5826(.AN (n_640), .B (n_763), .Y (n_890));
  NOR2BX2LVT g5828(.AN (n_624), .B (n_421), .Y (n_892));
  CLKAND2X2LVT g5829(.A (n_616), .B (n_619), .Y (n_893));
  ADDFHX2LVT g5831(.A (n_553), .B (n_468), .CI (n_797), .CO (n_895), .S
       (UNCONNECTED));
  AO22X2LVT g5833(.A0 (n_531), .A1 (n_532), .B0 (n_428), .B1 (n_530),
       .Y (n_897));
  AOI21X4LVT g5834(.A0 (n_885), .A1 (n_886), .B0 (n_611), .Y (n_898));
  OR2X6LVT g5835(.A (n_1112), .B (n_1052), .Y (n_900));
  OAI2BB1X4LVT g5836(.A0N (\prod_reg[6] [6]), .A1N (\prod_reg[5] [6]),
       .B0 (n_901), .Y (n_902));
  NAND2BX4LVT g5837(.AN (n_505), .B (n_790), .Y (n_901));
  ADDHX1LVT g5840(.A (\prod_reg[7] [2]), .B (\shift_reg[0] [2]), .CO
       (n_905), .S (n_906));
  DFFX2LVT \prod_reg_reg[0][2] (.CK (i_clock), .D (data_in_reg[2]), .Q
       (\shift_reg[0] [2]), .QN (n_12));
  OAI21X4LVT g165(.A0 (n_911), .A1 (n_917), .B0 (n_918), .Y (n_919));
  NOR2X2LVT g182(.A (n_908), .B (\prod_reg[6] [10]), .Y (n_911));
  CLKINVX4LVT g190(.A (n_907), .Y (n_908));
  CLKINVX4LVT g191(.A (\prod_reg[5] [10]), .Y (n_907));
  NOR2X8LVT g170(.A (n_914), .B (n_916), .Y (n_917));
  NOR2X2LVT g5843(.A (n_912), .B (n_913), .Y (n_914));
  CLKINVX6LVT g186(.A (\prod_reg[3] [9]), .Y (n_912));
  CLKINVX6LVT g196(.A (\prod_reg[4] [9]), .Y (n_913));
  AOI21X4LVT g5844(.A0 (n_912), .A1 (n_913), .B0 (n_915), .Y (n_916));
  NAND2X1LVT g183(.A (\prod_reg[6] [10]), .B (n_908), .Y (n_918));
  NAND2X6LVT g166(.A (n_923), .B (n_924), .Y (n_925));
  NAND2X4LVT g5845(.A (n_922), .B (n_917), .Y (n_923));
  NAND2X6LVT g5846(.A (n_920), .B (n_921), .Y (n_922));
  NAND2X4LVT g181(.A (n_909), .B (n_908), .Y (n_920));
  NAND2X4LVT g180(.A (n_907), .B (\prod_reg[6] [10]), .Y (n_921));
  OR2X6LVT g5847(.A (n_922), .B (n_917), .Y (n_924));
  NAND2X4LVT g169(.A (n_928), .B (n_932), .Y (n_933));
  NOR2X4LVT g172(.A (n_926), .B (n_927), .Y (n_928));
  NOR3X4LVT g5848(.A (n_912), .B (n_913), .C (n_915), .Y (n_926));
  NOR3X4LVT g5849(.A (\prod_reg[3] [9]), .B (n_915), .C
       (\prod_reg[4] [9]), .Y (n_927));
  NOR2X4LVT g5850(.A (n_930), .B (n_931), .Y (n_932));
  NOR3X4LVT g5851(.A (n_912), .B (\prod_reg[4] [9]), .C
       (\prod_reg[0] [9]), .Y (n_930));
  NOR3X4LVT g5852(.A (\prod_reg[3] [9]), .B (n_913), .C
       (\prod_reg[0] [9]), .Y (n_931));
  OAI21X4LVT g5853(.A0 (n_936), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_106), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_5), .Y (n_937));
  NAND2X4LVT g20(.A (csa_tree_ADD_TC_OP_12_groupi_n_76), .B (n_957), .Y
       (n_936));
  XOR3X1LVT g122(.A (csa_tree_ADD_TC_OP_12_groupi_n_192), .B (n_919),
       .C (n_700), .Y (n_938));
  BUFX2LVT g124(.A (csa_tree_ADD_TC_OP_12_groupi_n_192), .Y (n_941));
  XNOR3X1LVT g5860(.A (n_948), .B (n_925), .C (n_793), .Y (n_949));
  OAI2BB1X4LVT g54(.A0N (n_383), .A1N (n_384), .B0 (n_1101), .Y
       (n_948));
  NAND2X8LVT g15(.A (csa_tree_ADD_TC_OP_12_groupi_n_98), .B (n_763), .Y
       (n_951));
  OAI22X4LVT g13(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_80), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_131), .B0 (n_953), .B1 (n_954),
       .Y (n_955));
  INVX1LVT g5862(.A (csa_tree_ADD_TC_OP_12_groupi_n_80), .Y (n_953));
  CLKINVX4LVT g5863(.A (csa_tree_ADD_TC_OP_12_groupi_n_131), .Y
       (n_954));
  NAND2X8LVT g24(.A (n_956), .B (n_503), .Y (n_957));
  NAND3X8LVT g5864(.A (n_1040), .B (n_473), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_104), .Y (n_956));
  AOI21X4LVT g16(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_131), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_101), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_109), .Y (n_958));
  INVX3LVT g203(.A (n_959), .Y (n_960));
  ADDFHX2LVT g204(.A (n_430), .B (n_501), .CI
       (csa_tree_ADD_TC_OP_12_groupi_n_212), .CO (n_971), .S (n_959));
  NOR2X4LVT g205(.A (n_961), .B (n_1104), .Y (n_964));
  NOR2X4LVT g207(.A (n_400), .B (n_892), .Y (n_961));
  BUFX2LVT g1(.A (n_624), .Y (n_962));
  CLKINVX6LVT g201(.A (n_989), .Y (n_966));
  CLKXOR2X2LVT g199(.A (n_989), .B (n_969), .Y (n_970));
  OAI22X4LVT g200(.A0 (n_959), .A1 (n_964), .B0 (n_960), .B1 (n_968),
       .Y (n_969));
  OR2X6LVT g206(.A (n_961), .B (n_1104), .Y (n_968));
  NOR2X8LVT g29(.A (n_973), .B (n_974), .Y (n_975));
  OAI21X4LVT g5865(.A0 (n_1094), .A1
       (csa_tree_ADD_TC_OP_12_groupi_n_54), .B0 (n_1093), .Y (n_973));
  NOR2X6LVT g5866(.A (n_581), .B (n_583), .Y (n_974));
  NAND2X6LVT g28(.A (n_1100), .B (n_977), .Y (n_978));
  NOR2X6LVT g5868(.A (n_937), .B (n_871), .Y (n_977));
  BUFX2LVT g5869(.A (n_415), .Y (n_979));
  ADDFHX2LVT g5870(.A (n_791), .B (n_613), .CI (n_987), .CO (n_988), .S
       (n_989));
  OAI21X4LVT g5871(.A0 (n_980), .A1 (n_983), .B0 (n_986), .Y (n_987));
  CLKINVX4LVT g153(.A (n_789), .Y (n_980));
  CLKAND2X6LVT g5872(.A (n_981), .B (n_982), .Y (n_983));
  CLKINVX4LVT g150(.A (n_407), .Y (n_981));
  CLKINVX6LVT g148(.A (n_877), .Y (n_982));
  NAND2X6LVT g146(.A (n_984), .B (n_985), .Y (n_986));
  CLKINVX8LVT g147(.A (n_982), .Y (n_984));
  CLKINVX6LVT g149(.A (n_981), .Y (n_985));
  INVX3LVT g154(.A (n_415), .Y (n_990));
  NOR2X6LVT g5874(.A (n_1107), .B (n_998), .Y (n_999));
  NAND2X6LVT g142(.A (n_992), .B (n_993), .Y (n_994));
  NAND2X6LVT g143(.A (n_982), .B (n_985), .Y (n_992));
  NAND2X6LVT g145(.A (n_981), .B (n_984), .Y (n_993));
  NOR2X4LVT g140(.A (n_980), .B (n_994), .Y (n_998));
  CLKAND2X3LVT g135(.A (n_990), .B (n_999), .Y (n_1001));
  INVX2LVT g5875(.A (n_999), .Y (n_1002));
  INVX2LVT g48(.A (n_1003), .Y (n_1004));
  NOR2X4LVT g49(.A (n_895), .B (n_442), .Y (n_1003));
  AOI21X4LVT g44(.A0 (n_1004), .A1 (n_368), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .Y (n_1006));
  NAND2X2LVT g45(.A (n_1004), .B (n_640), .Y (n_1007));
  NOR2X6LVT g47(.A (n_1094), .B (n_1003), .Y (n_1008));
  CLKAND2X2LVT g5877(.A (n_1110), .B (n_539), .Y (n_1018));
  BUFX2LVT g5880(.A (n_906), .Y (n_1014));
  OA21X1LVT g5881(.A0 (\shift_reg[6] [1]), .A1 (n_1014), .B0
       (csa_tree_ADD_TC_OP_12_groupi_n_231), .Y (n_1016));
  NOR2X4LVT g5882(.A (n_1110), .B (n_539), .Y (n_1019));
  ADDFHX2LVT g5883(.A (csa_tree_ADD_TC_OP_12_groupi_n_249), .B
       (n_1020), .CI (n_523), .CO (n_1021), .S (n_1022));
  XOR3X1LVT g5884(.A (\shift_reg[6] [1]), .B (n_906), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_231), .Y (n_1020));
  NAND2X2LVT g5885(.A (csa_tree_ADD_TC_OP_12_groupi_n_171), .B
       (n_1024), .Y (n_1025));
  BUFX3LVT g74(.A (n_1117), .Y (n_1024));
  NOR2X4LVT g73(.A (csa_tree_ADD_TC_OP_12_groupi_n_171), .B (n_1024),
       .Y (n_1026));
  XNOR3X1LVT g71(.A (csa_tree_ADD_TC_OP_12_groupi_n_171), .B (n_1117),
       .C (n_1088), .Y (n_1027));
  BUFX6LVT g5886(.A (n_548), .Y (n_1028));
  NAND2X6LVT g5888(.A (n_897), .B (n_1028), .Y (n_1029));
  NAND2BX1LVT g21(.AN (n_816), .B (n_1096), .Y (n_1031));
  NAND2BX1LVT g5889(.AN (n_818), .B (n_1096), .Y (n_1032));
  NAND2X8LVT g5890(.A (n_1038), .B (n_1102), .Y (n_1040));
  NOR2X8LVT g5891(.A (n_1036), .B (n_1037), .Y (n_1038));
  NOR2X4LVT g5892(.A (n_1033), .B (n_1108), .Y (n_1036));
  INVX2LVT g5893(.A (n_449), .Y (n_1033));
  CLKAND2X3LVT g5896(.A (n_1033), .B (n_1108), .Y (n_1037));
  NOR2X4LVT g50(.A (n_1038), .B (n_1102), .Y (n_1041));
  CLKAND2X6LVT g26(.A (n_1044), .B (n_852), .Y (n_1045));
  INVX2LVT g5898(.A (n_1043), .Y (n_1044));
  AOI2BB1X4LVT g5899(.A0N (n_545), .A1N (n_542), .B0 (n_1103), .Y
       (n_1043));
  NAND2X6LVT g27(.A (n_1043), .B (n_850), .Y (n_1046));
  BUFX2LVT g5901(.A (n_1047), .Y (n_1048));
  NAND2X6LVT g70(.A (n_702), .B (n_704), .Y (n_1047));
  XOR3X1LVT g65(.A (n_1047), .B (n_796), .C (n_949), .Y (n_1051));
  AND2X1LVT g67(.A (n_436), .B (n_1048), .Y (n_1052));
  INVX3LVT g5904(.A (\prod_reg[4] [11]), .Y (n_1054));
  OAI21X1LVT g185(.A0 (csa_tree_ADD_TC_OP_12_groupi_n_24), .A1
       (n_1058), .B0 (n_1059), .Y (n_1060));
  INVX1LVT g197(.A (n_1054), .Y (n_1058));
  ADDFHX2LVT g189(.A (\prod_reg[2] [11]), .B (\prod_reg[5] [11]), .CI
       (n_887), .CO (n_1059), .S (n_1070));
  OAI22X4LVT g184(.A0 (n_1064), .A1 (n_1059), .B0 (n_1065), .B1
       (n_1066), .Y (n_1067));
  AOI2BB1X4LVT g5906(.A0N (n_1054), .A1N
       (csa_tree_ADD_TC_OP_12_groupi_n_24), .B0 (n_1063), .Y (n_1064));
  NOR2X2LVT g5907(.A (\prod_reg[4] [11]), .B (\prod[3] [14]), .Y
       (n_1063));
  INVX2LVT g5909(.A (n_1059), .Y (n_1065));
  INVX2LVT g5910(.A (n_1064), .Y (n_1066));
  XOR3X1LVT g5915(.A (n_1070), .B (n_707), .C (n_711), .Y (n_1073));
  NOR2X8LVT g5916(.A (n_1074), .B (n_1001), .Y (n_1075));
  NOR2X4LVT g5917(.A (n_990), .B (n_999), .Y (n_1074));
  NAND2X8LVT g35(.A (n_1080), .B (n_1083), .Y (n_1084));
  NAND2X4LVT g37(.A (n_1115), .B (n_1079), .Y (n_1080));
  NOR2X2LVT g40(.A (\prod_reg[5] [8]), .B (n_490), .Y (n_1077));
  BUFX6LVT g5918(.A (n_489), .Y (n_1079));
  NAND2X6LVT g36(.A (n_1081), .B (n_1082), .Y (n_1083));
  INVX2LVT g38(.A (n_1115), .Y (n_1081));
  CLKINVX4LVT g42(.A (n_1079), .Y (n_1082));
  NOR2BX2LVT g5919(.AN (n_1085), .B (n_1084), .Y (n_1086));
  AOI21X2LVT g5920(.A0 (n_374), .A1 (n_500), .B0 (n_378), .Y (n_1085));
  NAND2BX2LVT g5921(.AN (n_1085), .B (n_1084), .Y (n_1087));
  XOR3X1LVT g5922(.A (n_1085), .B (n_1084), .C
       (csa_tree_ADD_TC_OP_12_groupi_n_175), .Y (n_1088));
  NOR2X6LVT g86(.A (n_1089), .B (csa_tree_ADD_TC_OP_12_groupi_n_244),
       .Y (n_1090));
  ADDFHX2LVT g5923(.A (n_1073), .B (n_448), .CI (n_938), .CO (n_1089),
       .S (n_1092));
  NAND2X4LVT g87(.A (n_1089), .B (csa_tree_ADD_TC_OP_12_groupi_n_244),
       .Y (n_1091));
  NAND2X4LVT g5924(.A (n_900), .B (n_1092), .Y (n_1093));
  BUFX2LVT g5925(.A (n_1094), .Y (n_1095));
  NOR2X8LVT g88(.A (n_900), .B (n_1092), .Y (n_1094));
  BUFX2LVT g5926(.A (n_1029), .Y (n_1096));
  NOR2X6LVT g5927(.A (n_1045), .B (n_1097), .Y (n_1098));
  NOR2X4LVT g5928(.A (n_1029), .B (n_715), .Y (n_1097));
  NOR2X6LVT g5929(.A (csa_tree_ADD_TC_OP_12_groupi_n_119), .B (n_1099),
       .Y (n_1100));
  NOR2X6LVT g5930(.A (csa_tree_ADD_TC_OP_12_groupi_n_117), .B (n_951),
       .Y (n_1099));
  DFFX2LVT \prod_reg_reg[0][10] (.CK (i_clock), .D (n_132), .Q
       (\prod_reg[0] [10]), .QN (csa_tree_ADD_TC_OP_12_groupi_n_22));
  DFFX4LVT \prod_reg_reg[7][10] (.CK (i_clock), .D (n_160), .Q
       (\prod_reg[7] [10]), .QN (n_691));
  DFFX1LVT \prod_reg_reg[6][11] (.CK (i_clock), .D (n_157), .Q
       (\prod_reg[6] [11]), .QN (n_887));
  DFFX1LVT \prod_reg_reg[6][10] (.CK (i_clock), .D (n_159), .Q
       (\prod_reg[6] [10]), .QN (n_909));
  DFFX4LVT \prod_reg_reg[0][9] (.CK (i_clock), .D (n_136), .Q
       (\prod_reg[0] [9]), .QN (n_915));
  OR2X1LVT g5941(.A (n_385), .B (n_386), .Y (n_1101));
  ADDFHX2LVT g5942(.A (n_960), .B (n_964), .CI (n_966), .CO (n_1102),
       .S (UNCONNECTED0));
  AND2X2LVT g5943(.A (n_543), .B (n_544), .Y (n_1103));
  NOR2BX2LVT g5944(.AN (n_421), .B (n_962), .Y (n_1104));
  NOR2BX4LVT g5945(.AN (n_1006), .B (n_662), .Y (n_1105));
  NOR2BX4LVT g5946(.AN (n_1004), .B
       (csa_tree_ADD_TC_OP_12_groupi_n_55), .Y (n_1106));
  CLKAND2X3LVT g5947(.A (n_980), .B (n_994), .Y (n_1107));
  XNOR2X2LVT g5948(.A (csa_tree_ADD_TC_OP_12_groupi_n_174), .B (n_988),
       .Y (n_1108));
  ADDFHX1LVT g5949(.A (n_941), .B (n_919), .CI (n_700), .CO (n_1109),
       .S (UNCONNECTED1));
  AO21X1LVT g5950(.A0 (n_1014), .A1 (\shift_reg[6] [1]), .B0 (n_1016),
       .Y (n_1110));
  AOI2BB1X2LVT g5952(.A0N (n_1048), .A1N (n_436), .B0 (n_949), .Y
       (n_1112));
  OAI21X1LVT g5953(.A0 (n_1054), .A1 (\prod[3] [14]), .B0 (n_1060), .Y
       (n_1113));
  ADDFX1LVT g5954(.A (n_707), .B (n_711), .CI (n_1070), .CO (n_1114),
       .S (UNCONNECTED2));
  AOI2BB1X4LVT g5955(.A0N (n_491), .A1N (\prod_reg[6] [8]), .B0
       (n_1077), .Y (n_1115));
  NAND2X4LVT g5956(.A (n_1116), .B (n_804), .Y (n_1117));
  OAI21X4LVT g3(.A0 (n_458), .A1 (n_381), .B0 (n_971), .Y (n_1116));
  ADDHX2LVT g5957(.A (\shift_reg[0] [0]), .B (\prod_reg[7] [0]), .CO
       (n_1119), .S (n_1118));
endmodule

